### ISSUE TITLE
Make EventFlow Test Helpers usable in projects that implement EventFlow

### ISSUE THREAD

**Issue by JC008** [eventflow/EventFlow#104]
Getting a testing system up in EventFlow can be intimidating and time consuming, event if you understand the basics. Ensuring that existing test helpers are usable by projects implementing EventFlow, overall adoption rates and implementation quality in downstream projects will be improved.

Example:
In `EventFlow.MsSql.Tests.Helpers` the `MsSqlHelper` helper class does not allow for explicit database names and `TestDatabase` drops the database as it is designed for use in unit tests and not  integration tests. A `bool transient` option can be added to indicated if a database should be dropped after a test to allow the developer to use a growing set of event stream data.

**Comment by rasmus** [comment]
@JC008 Same as in #5?

But if you want to test your domain, you should try to do it using the in-memory event store. Setting up e.g. the MSSQL event store takes too long if you want to have a lot of different tests. I suggest the following.

- Use the in-memory event store
- Create [queries](https://github.com/rasmus/EventFlow/blob/develop/Documentation/Queries.md)
- In your comprehensive domain tests, create and use in-memory query handlers
- Create the "read" query handlers for e.g. MSSQL read models, and test those separately

This will enable you to test your commands, aggregates, domain services, events and all that faster and will help you keep a bit cleaner code base.

**Comment by JC008** [comment]
@rasmus Yes it is the same as #5. Thanks for the guidance on testing, but in non unit tests

* I want to `eye ball` the sql database for use in development discussions
* have the option of retaining the sql database as artefact on test failure
* use a growing stream of data with behavior tests for `what if` / `what now` when design the system
* run integration tests on different machines in a coordinated fashion

Maybe my comments re an external guide in https://github.com/rasmus/EventFlow/pull/103#issuecomment-135271151 applies here.

**Comment by JC008** [comment]
@rasmus 

Retaining the result sql db also useful for observing the behavior and output in EventFlow e.g. in read models.

**Comment by rasmus** [comment]
@JC008 Makes sense. I our setup is a bit simpler as we merely have a listener that logs all the events and dumps them to a log in the event of test failure but I can understand the need.

**Comment by rasmus** [comment]
Done - https://www.nuget.org/packages/EventFlow.TestHelpers/
