### ISSUE TITLE
MongoDB support as event store

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#112]
Try out another event store

**Comment by rasmus** [comment]
nope

**Comment by andrei-tatar** [comment]
@rasmus Was there a reason why a MongoDB implementation is not provided? I was thinking of implementing my own but maybe I'm missing something.

**Comment by rasmus** [comment]
@andrei-tatar no reason. I don't have the experience with MongoDB to provide one that I can support

**Comment by andrei-tatar** [comment]
OK, good to know. Thanks!

**Comment by janfeyen** [comment]
Hi
I have implemented readstore and snapshot store for mongoDB and a readstore for firebase
I haven't had the time yet to add it to this project and create a pull request but more than happy to help you/share the code

**Comment by rasmus** [comment]
@janfeyen If you are interested I can add those two as separate repos in the eventflow org and make you maintainer of those? I'm planning to move the different read stores and event stores to separate repos to make it easier to maintain in the future

**Comment by janfeyen** [comment]
@rasmus yep, let's do that

**Comment by rasmus** [comment]
@janfeyen you should have an invite

**Comment by janfeyen** [comment]
@rasmus thanks, just committed my code
I removed the test project for now as it depends on your test helper but it's not part of your EventFlow nuget package.
any suggestions? I'd like to include it at one stage. It's based on your thingy and thingy message tests.

I'll work on the documentation later today.

Also, never created a nuget package before, will read up on it as well today

**Comment by janfeyen** [comment]
Hi @andrei-tatar, @rasmus  , you can install the package EventFlow.MongoDB for mongoDB read stores.
Setting up the readstores works simular to other readstores

1. Configure the DB
`ConfigureMongoDb`

2. decorate your readmodel
`[MongoDbCollectionName("core.accounts")]
public class AccountReadModel : IMongoDbReadModel, 
        IAmReadModelFor<AccountAggregate, AccountId, AccountCreated>,
...`
3. Register your readmodel
`UseMongoDbReadModel`

I'll work on the docs soon.

**Comment by janfeyen** [comment]
can you also add warren-pieterse (qubit) to the 2 repositories?
He's my colleague and will assist in maintaining the repositories
Thanks

2017-06-16 20:52 GMT+02:00 Rasmus Mikkelsen <notifications@github.com>:

**Comment by rasmus** [comment]
@janfeyen I have been thing about providing a test suite NuGet for EventFlow projects to help develop packagers, storage and read models. It would contain the test domain and the helpers. Would that make sense?

**Comment by janfeyen** [comment]
@rasmus yes ... that would help

**Comment by edwardwilson** [comment]
This issue talks about adding mongodb as an event store; I have a pull request in the repo adding this feature but I'm afraid it seems to have gotten forgotten about for some time now. Is there anyone here that could review?
@rasmus

**Comment by rasmus** [comment]
@edwardwilson I haven't been watching the other repo, sorry. I'll add you as a maintainer as well as it doesn't seem like @janfeyen and @edwardwilson are maintaining.
