### ISSUE TITLE
Configurable background jobs

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#121]
As an integrated part of EventFlow, it should be possible to create background jobs. These could be used for several things.
- Better transient fault handling
- Fire and forget commands
- Delayed execution

Several methods could be used, but as the "core" of EventFlow doesn't have background jobs, the feature should be disabled by default and left as a configuration option.

These could be used for implementing the jobs.
- RabbitMQ
- Hangfire

**Comment by JC008** [comment]
[BeanStalkD](http://kr.github.io/beanstalkd/) and [Akka.net](http://getakka.net/) could be useful implementations too.

**Comment by rasmus** [comment]
Thanks

**Comment by rasmus** [comment]
Closing, implemented Hangfire for now
