### ISSUE TITLE
please add write model in Simple example 

### ISSUE THREAD

**Issue by Cuiqs76** [eventflow/EventFlow#246]
Please add write model in Simple example .

**Comment by rasmus** [comment]
@Cuiqs76 I updated the README in #247 and its merged, have a look

**Comment by Cuiqs76** [comment]
I use  .UseEventStoreEventStore(ip,connectionSettings) and  use commandhandler as below
` public override Task ExecuteAsync(NonconformityGroupTypeAggregate aggregate, NonconformityGroupTypeCreateCommand command, CancellationToken cancellationToken)
        {
            aggregate.Create(command.Code,command.Name,command.Description);
         
            return Task.FromResult(0);
        }

but not save to evntstore.  what i missed?

**Comment by rasmus** [comment]
@Cuiqs76 What does the log output if you set it to debug? I also recommend you write a test that tests your domain code using the default in-memory event store. That way you can limit the amount of factors that could cause your problem
