### ISSUE TITLE
[Question] How to integrate Readmodel with Sql Server

### ISSUE THREAD

**Issue by taufikfadjar** [eventflow/EventFlow#259]
I already has run scenario test using InMemory data then try to presist some data based that scenario.  

 Here is what I did :
1. Create EF code first and follow some spec like table name (readmodel-*) 
2. Create repository
3. Register all repository to DI IEventFlowOptions
4. Maybe call repository in voyage readmodel method  public void Apply(IReadModelContext context, IDomainEvent<VoyageAggregate, VoyageId, VoyageCreatedEvent> e) to presist data.

I need some advise what currently what i did. I am confusing to how to presist data between readmodel using sql server.

Thank you :).

**Comment by rasmus** [comment]
@taufikfadjar Have you had a look at the documentation?

http://docs.geteventflow.net/ReadStores.html#microsoft-sql-server

**Comment by taufikfadjar** [comment]
Yes i had look the documentation, But I am getting confused. I already create new library contain readmodel using Mssql and register to UseMssqlReadModel.

**Comment by rasmus** [comment]
Have you had a look at the integration tests for the MSSQL read models. I know some nice documentation would be nice, but I haven't gotten to it yet.

https://github.com/eventflow/EventFlow/tree/develop/Source/EventFlow.MsSql/ReadStores

**Comment by rasmus** [comment]
I guess that a NuGet package that provides read model support for EF would be the best solution

**Comment by taufikfadjar** [comment]
Thank you sir @rasmus, I didn't notice. You had given an example :) . Sorry for bothering you.

I will try do it as your guideline 

https://github.com/eventflow/EventFlow/tree/develop/Source/EventFlow.MsSql.Tests/IntegrationTests/ReadStores

**Comment by rasmus** [comment]
@taufikfadjar No problem, glad you found a solution
