### ISSUE TITLE
EntityFramework support

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#260]
Provide NuGet package that enables MS Entity Framwork

Create another repo.

If anyone wants to be maintainer on such a package and get it hosted in the EventFlow org. Let me know.

**Comment by pichardoSoftware** [comment]
I could help you with this, but I need more information.

**Comment by rasmus** [comment]
@pichardoSoftware That would be great!

- The EF support is basically two parts, event persistance and read model support. I suggest you pick one and focus on that and get that PR finished first
- The project should be called EventFlow.EntityFramework and should contain both read model and event persistance support
- Have a look at the EventFlow.MsSql project source layout, it should be something like that
- Be sure to create integration tests. Its faily simple as there's a "suite" of tests that you can inherit from (https://github.com/eventflow/EventFlow/tree/develop/Source/EventFlow.TestHelpers/Suites). All the other projects use those for integration tests, so there should be some good examples
- Don't put any effort into updating build scrips and NuSpec files, as I hope to be able to close #257 soon and thereby making it much easier

If you have any questions, please ask. I preparing to move to a new house with the next three weeks, so I will not be able to provide that much in-depth support, but I'll try to answer any questions ASAP.

**Comment by rasmus** [comment]
Forgot some basic stuff

- Event persistence, create implementation of `IEventPersistence`
- Read model support, implement `ReadModelStore<>`

You can have a look at the in-memory or MSSQL implementations for some general idea on how to do it

**Comment by pichardoSoftware** [comment]
Ok, I'll check it out

**Comment by rasmus** [comment]
@pichardoSoftware PR #257 is closed now and will make it easier to get started on new projects

**Comment by rasmus** [comment]
@pichardoSoftware If you had problems working with EventFlow due to git lfs, give it another go as it has been removed

**Comment by frankebersoll** [comment]
I have a working implementation for Entity Framework 6 persistence and read models.

- Would people use this (our company does)?
- EF6 / EF Core / Why not both?

**Comment by wgtmpeters** [comment]
We are actually interested in this as well. Maybe you can get a branch up and running. If there is any help needed I might contribute as well.

**Comment by rasmus** [comment]
I have received a few requests on it by mail as well

**Comment by wgtmpeters** [comment]
@frankebersoll  Do you have any plans for setting up branch for this? We would really like to use this as well.

**Comment by frankebersoll** [comment]
@wgtmpeters Are you using EF Core or EF6? Could you briefly explain, how you would expect to use EventFlow together with Entity Framework? What DB do you use?

**Comment by wgtmpeters** [comment]
@frankebersoll we are using EF core in combination with Postgres.

**Comment by rasmus** [comment]
Released
