### ISSUE TITLE
SqlServer Cannot insert the value NULL into column 'AggregateId'

### ISSUE THREAD

**Issue by minhhungit** [eventflow/EventFlow#275]
I convert example demo to use sql server, because it does not auto create read-model table so I was try to create a read-model table like:

```
CREATE TABLE [dbo].[ReadModel-Example](
	[AggregateId] [nvarchar](255) NOT NULL,
	[MagicNumber] [int] NULL,
 CONSTRAINT [PK_ReadModel-Example] PRIMARY KEY CLUSTERED 
(
	[AggregateId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
```
Full code and exception are attached 
[full-code.txt](https://github.com/eventflow/EventFlow/files/591046/full-code.txt)
[full-exception.txt](https://github.com/eventflow/EventFlow/files/591047/full-exception.txt)

More question: any special requirements for ReadModel table, such as Id, AggregateId...

**Comment by minhhungit** [comment]
I can fix it by add a new property called **AggregateId** into ExampleReadModel, and update value for it like:

public class ExampleReadModel : IReadModel,
      IAmReadModelFor<ExampleAggrenate, ExampleId, ExampleEvent>
    {
        **public string AggregateId { get; private set; }**
        public int MagicNumber { get; private set; }

        public void Apply(
          IReadModelContext context,
          IDomainEvent<ExampleAggrenate, ExampleId, ExampleEvent> domainEvent)
        {
            **AggregateId = domainEvent.GetIdentity().Value;**
            MagicNumber = domainEvent.AggregateEvent.MagicNumber;
        }
    }

but any difference suggestion ?

**Comment by taufikfadjar** [comment]
Did you ever try this ? 
https://github.com/eventflow/EventFlow/tree/develop/Source/EventFlow.MsSql.Tests

may that link help your problem

**Comment by minhhungit** [comment]
I did, still don't understand why it required column **AggregateId**
I didn't see any difference between my code and sample Test code

**Comment by minhhungit** [comment]
The difference is read-model class:
my code is: public class ExampleReadModel : **IReadModel**
test code is public class MsSqlThingyReadModel : **MssqlReadModel**

**Comment by minhhungit** [comment]
if I change my code to use **MssqlReadModel** then it passed
but I also need add more column to read model table, such as:  AggregateId, CreateTime, UpdatedTime and LastAggregateSequenceNumber
And  I got a warrning: 
> EventFlow no longer dictates any properties for the MSSQL read models. Read the updated documentation

**Comment by taufikfadjar** [comment]
I'm just helping you get here. Maybe you can wait until mr @rasmus answer your question :)

**Comment by rasmus** [comment]
I'm relocating to a new house this week and have only limited internet and computer access. I'll try to get back to you later today when I had the time to look into the problem.

**Comment by rasmus** [comment]
Hi @minhhungit 

The MSSQL integration test verifies both the "old" (using `MsSqlThingyReadModel`) and the new (using `MsSqlThingyMessageReadModel`). I think your missing the`MsSqlReadModelIdentityColumn` attribute on the column that you would like to use as the identity. As EventFlow tries to limit its requirements to the read models, it still needs the attribute of the identity to allow it to set the value. So in short, have a look at `MsSqlThingyMessageReadModel`.

When I'm done updating the getting started guide I'll have a look at the MSSQL read model docs.

P.S.: @taufikfadjar thanks for helping out 😄

**Comment by minhhungit** [comment]
you mean like this: 

> public class ExampleReadModel : IReadModel,
>       IAmReadModelFor<ExampleAggrenate, ExampleId, ExampleEvent>
>     {
>         [MsSqlReadModelIdentityColumn]
>         public string AggregateId { get; private set; }
> 
>         [MsSqlReadModelVersionColumn]
>         public int Version { get; private set; }
> 
>         public int MagicNumber { get; private set; }
> 
>         public void Apply(
>           IReadModelContext context,
>           IDomainEvent<ExampleAggrenate, ExampleId, ExampleEvent> domainEvent)
>         {
>             MagicNumber = domainEvent.AggregateEvent.MagicNumber;
>         }
>     }

It does not work for me :(

**Comment by minhhungit** [comment]
okay, so: 
- how many require columns for read-model table and which are they? (id, aggregateId...)
- should we add code in read-model class to update aggregateId in read-model table, like:

```
public class ExampleReadModel : IReadModel,
      IAmReadModelFor<ExampleAggrenate, ExampleId, ExampleEvent>
    {
        public string AggregateId { get; private set; }
       .......

        public void Apply(
          IReadModelContext context,
          IDomainEvent<ExampleAggrenate, ExampleId, ExampleEvent> domainEvent)
        {
            AggregateId = domainEvent.AggregateIdentity.Value;  
        }
}
```
and if we should, is line **domainEvent.AggregateIdentity.Value** ok ?

**Comment by rasmus** [comment]
@minhhungit There's only one column required, which is the ID of the read model, which for MSSQL read model needs to be marked with a `MsSqlReadModelIdentityColumn` attribute, the name of that can be whatever you like. You should set the ID value yourself. It would be possible for EventFlow to set it, but then you would have to make the property `public`. The `MsSqlThingyMessageReadModel` has the `MessageId` as its ID.

https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.MsSql.Tests/IntegrationTests/ReadStores/ReadModels/MsSqlThingyMessageReadModel.cs

**Comment by minhhungit** [comment]
it worked  :)
so I will close this issue, thanks @taufikfadjar @rasmus
