### ISSUE TITLE
[Question] Ask about Emit Event & Handle when raise a domain error

### ISSUE THREAD

**Issue by taufikfadjar** [eventflow/EventFlow#276]
I have several question,

1. Can i create event without submit in eventstore ? . As example i just want notify user client.
2. I have collection data when emit event, can eventflow map multiple data to readmodel ?. As example we have collection thingymessage to iterate map in readmodel
3. How best practice to handle when raise domain in web app. Should we make new event or  we can get return data from await commandbus ?

Thanks :) , Hehe

**Comment by rasmus** [comment]
I'm relocating to a new house this week and have only limited internet and computer access. I'll try to get back to you later today.

**Comment by taufikfadjar** [comment]
Thank you, :)

**Comment by rasmus** [comment]
Hi @taufikfadjar 

1. You _could_ invoke the `IEventStore.StoreAsync` directly. However, it isn't a use case that EventFlow is designed for so it might be a bit cumbersome. You also have to decide if the committed events should be sent to read models, subscribers etc. you can have a look at the `AggregateStore` to see how it does it.
1. When you say _data_ if its related to your domain it should be within the event itself. If its merely "extra stuff" like request headers, current user ID, session state data, etc. then the easiest way is to implement `IMetadataProvider` which does the data gathering. The information is stored along each event and is present in the `IDomainEvent.Metadata` property that read models receive
1. If you need to return data, you can't. Its the CQRS part of EventFlow. You issue a command, wait for read models to be updated and then perform a query on your updated read models. EventFlow makes it a bit easy, as you _know_ that all read models have been updated after a `ICommandBus.PublishAsync` task completes. Best practice would be to embrace the concept of eventually consistent, but that might be too much work for smaller services.

Hope that helps.

**Comment by taufikfadjar** [comment]
Thank you. Maybe I will ask again.
