### ISSUE TITLE
Aggregate snapshot with Entities

### ISSUE THREAD

**Issue by minhhungit** [eventflow/EventFlow#279]
My **SupplierAggregate** have a **`List<SupplierContact>`** and a **Name**
I added **15** `supplierContact` to that supplier
I also create snapshot for that supplier with SnapshotEveryFewVersionsStrategy = 10
When I load aggregate, I just have **5** latest supplier contact, it counted from latest snapshot point
I think it should be **15**
I think this will make some mistakes when we need to compute List<SupplierContact>**
Is this a bug or my mistake ?

**Comment by minhhungit** [comment]
I think I found a problem
I must register event in aggregate constructor:
```
public SupplierRoot(SupplierId id) : base(id,  SnapshotEveryFewVersionsStrategy.With(SnapshotEveryVersion))
{
       Register<SupplierLocationWasAddedEvent>(e => _supplierLocations.Add(e.SupplierLocation));
}
```
and use readOnlyCollection

> public IReadOnlyCollection<SupplierLocation> SupplierLocations => _supplierLocations;

**Document site didn't include this info**

**Comment by rasmus** [comment]
@minhhungit The snapshotting aggregate is basically a aggregate with snapshotting capabilities, which means that the aggregate needs to have one of the methods to apply events. See http://docs.geteventflow.net/Aggregates.html#applying-events

**Comment by minhhungit** [comment]
@rasmus  thanks :) 👍
