### ISSUE TITLE
Re-populate read models from EventStore throws Only domain events from the same aggregate is allowed

### ISSUE THREAD

**Issue by warren-pieterse** [eventflow/EventFlow#280]
In the `SingleAggregateReadStoreManager` class, the `BuildReadModelUpdates` throws "Only domain events from the same aggregate is allowed" when populating from event store, or am I missing something?

Changing the implementation to the code below seems to fix it.

```
`        protected override IReadOnlyCollection<ReadModelUpdate> BuildReadModelUpdates(
            IReadOnlyCollection<IDomainEvent> domainEvents)
        {
            var readModelIds = domainEvents
                .Select(e => e.GetIdentity().Value)
                .Distinct()
                .ToList();

            List<ReadModelUpdate> list = new List<ReadModelUpdate>();
            readModelIds.ForEach(id =>
            list.Add(new ReadModelUpdate(id, domainEvents.Where(evnt => evnt.GetIdentity().Value == id).ToList())));

            return list;
        }`
```

**Comment by rasmus** [comment]
@warren-pieterse Darn. That is indeed a critical bug. I'll get a release ready ASAP

**Comment by rasmus** [comment]
The latest release should have the bug fix. Could you verify it and let me know

**Comment by warren-pieterse** [comment]
v0.38.2454 populates all my read models perfectly, thanks for fixing
