### ISSUE TITLE
[Question] Emit Event Contain List Entity Or  single ValueObject to ReadModel MsSql

### ISSUE THREAD

**Issue by taufikfadjar** [eventflow/EventFlow#282]
As example my **voyageaggregate** have a **schedule ( value object )** which contain **IReadOnlyCollection CarrierMovement (Entity)** and CarrierMovement ReadModel to store CarrierMovements data in MsSql (using locator)

If  i send command have a schedule which contain 10 CarrierMovements , so can we send event contain ValueObject Schedule or List of entity CarrierMovement to CarrierMovement ReadModel then add multiple data ?

if i want to delete 1 CarrierMovement from IReadOnlyCollection CarrierMovement  which contain 10 CarrierMovements. Should i create subscriber which contain delete query to delete data from MsSql ?

**Comment by rasmus** [comment]
@taufikfadjar as your `voyageaggregate` is mutable aggregate, it should have a `List<>` of `CarrierMovement`. Then to remove any or set a completly new set, you would mere call `.Clear()` or set a new list. In the example code I would create a method on the aggregate that would emit a `VoyageScheduleUpdatedEvent` event and a corresponding command, which will result in a new `Schedule` being set

**Comment by taufikfadjar** [comment]
- First
Yes voyageaggregate is mutable aggregate so list can be updated In eventstore .But how about remove data using mssqlreadmodel ? Should i set deleted flag (soft delete) ? or i can do without doing soft delete.

- Second
Based your example using in memory readmodel. I create  shipping using mssql readmodel version. 
In memory is so flexible, when emit VoyageScheduleUpdatedEvent i can update  schedule in readmodel without any problem.

But when convert example using MsSql. I must emit  CarrierMovementAddedEvent to insert CarrierMovement data one by one. How can i handle if using emit VoyageScheduleUpdatedEvent ?

...csharp
[Table("CarrierMovement")]
    public class CarrierMovementReadModel : IReadModel,
        IAmReadModelFor<VoyageAggregate, VoyageId, CarrierMovementAddedEvent>,
        IAmReadModelFor<VoyageAggregate, VoyageId, CarrierMovementUpdatedEvent>
    {

        public string VoyageId { get; set; }
        [MsSqlReadModelIdentityColumn]
        public string CarrierMovementId { get; set; }
        public string DepartureLocationId { get; set; }
        public string ArrivalLocationId { get; set; }
        public DateTimeOffset DepartureTime { get; set; }
        public DateTimeOffset ArrivalTime { get; set; }



        public void Apply(IReadModelContext context, EventFlow.Aggregates.IDomainEvent<VoyageAggregate, VoyageId, CarrierMovementAddedEvent> domainEvent)
        {
            VoyageId = domainEvent.AggregateIdentity.Value;
            var CarrierMovement = domainEvent.AggregateEvent.CarrierMovement;
            CarrierMovementId = CarrierMovement.Id.Value;
            DepartureLocationId = CarrierMovement.DepartureLocationId.Value;
            ArrivalLocationId = CarrierMovement.ArrivalLocationId.Value;
            DepartureTime = CarrierMovement.DepartureTime;
            ArrivalTime = CarrierMovement.ArrivalTime;
        }

        public void Apply(IReadModelContext context, IDomainEvent<VoyageAggregate, VoyageId, CarrierMovementUpdatedEvent> domainEvent)
        {
            var CarrierMovement = domainEvent.AggregateEvent.CarrierMovement;
            DepartureTime = CarrierMovement.DepartureTime;
            ArrivalTime = CarrierMovement.ArrivalTime;
        }

        public Domain.Model.VoyageModel.Entities.CarrierMovement ToCarrierMovement()
        {
            return new Domain.Model.VoyageModel.Entities.CarrierMovement(
                   new CarrierMovementId(CarrierMovementId),
                   new Domain.Model.LocationModel.LocationId(DepartureLocationId),
                   new Domain.Model.LocationModel.LocationId(ArrivalLocationId),
                   DepartureTime,
                   ArrivalTime
              );
        }
    }
...

**Comment by rasmus** [comment]
@taufikfadjar Oh, I didn't get your problem the first time, sorry about that.

If you want a one-to-many relation from aggregate to read model you should have a look at the `MsSqlThingyMessageReadModel` in the tests. It stores a message read model for each message which somewhat corresponds to the carrier movements.

As for read model deletion, here EventFlow doesn't have anything built-in at the moment. I haven't been able to figure out a solid solution yet 😢 (let me know if you have an idea), so some soft deletion will have to do. You might be better of managing your read models manually by implementing an `IReadStoreManager` that updates your MSSQL read models or implement a `ISubscribeSynchronousTo<>`. I try to provide several hook-ins in EventFlow so if the generic implementation it provides isn't adequate, you can provide a specialization that fits your needs.

Hope that helps, let me know if I'm still off.

**Comment by rasmus** [comment]
@taufikfadjar Let me know if I can close the issue

**Comment by taufikfadjar** [comment]
Thanks your explanation 👍 , It's my mistake because I did not explain well. 

So I have create many events which handle one-to-many relation from aggregate to read model. :smile:

I will consider use IReadStoreManager but i think more easy to use ISubscribeSynchronousTo<> :grimacing:

**Comment by PhatHoang21** [comment]
I was wondering if we can use Saga for these cases?
