### ISSUE TITLE
unable to add to an asp.net 4 application

### ISSUE THREAD

**Issue by lucamorelli** [eventflow/EventFlow#284]
Hi, I'm trying to add eventflow to an asp.net 4 application with autofac, but when I run the application I have this error message:

`Unable to load the type'EventFlow.EventFlowOptions'  from assembly 'EventFlow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
`

Am I missing something?

**Comment by rasmus** [comment]
@lucamorelli EventFlow is 4.5.1+ due to dependencies on API in the TPL

**Comment by lucamorelli** [comment]
Hmmm ... Never seen this... I called the test project EventFlow, with the same name of the dll, and looks like was overwriting the package dll without any warning.
Renamed the application assembly and now it's starting.
Thanks.
