### ISSUE TITLE
[Question] Replay events

### ISSUE THREAD

**Issue by minhhungit** [eventflow/EventFlow#285]
Hi team,
I have an event table with all events committed, I dropped all views table. How can I replay event for all views?
I used to work with [Cirqus ](https://github.com/d60/Cirqus)(is also a cqrs framework). It can auto replay all events immediately after we restart system, I don't sure if eventflow can do something like that

**Comment by rasmus** [comment]
Hi @minhhungit 

You can resolve the `IReadModelPopulator`, it is the methods you need and have a default implementation. If you need to do anything on bootdtrap, you can use implement the `IBootstrap` interface.

**Comment by minhhungit** [comment]
@rasmus Thank you and merry xmas. I'll research it.
Please add document for `<Replay>` feature & `<Bootstrap>` when you have time
