### ISSUE TITLE
What about storing the events on Cassandra?

### ISSUE THREAD

**Issue by MonDeveloper** [eventflow/EventFlow#287]
Since (imho) cassandra and its write-append mindset fits pretty well with the event storing approach I'm wondering if there is something similar in the roadmap

**Comment by rasmus** [comment]
@MonDeveloper I have read a bit about Cassandra, but I have no experience working with it, there's no plans for adding support for it. If you're up for it, I would recommend creating a package for it. I would prefer if it isn't stored in the main repo, that is getting a bit big and I'm considering splitting it up into smaller ones.

Creating your own event persistence in EventFlow is relatively simple though, you merely need to implement `IEventPersistence` and register it.

**Comment by johndab** [comment]
Check this out:
[EventFlow.Cassandra.EventStore](https://github.com/Pagaspot/EventFlow.Cassandra.EventStore)
