### ISSUE TITLE
"EventFlow.RabbitMQ" references "EventFlow.TestHelpers"

### ISSUE THREAD

**Issue by MonDeveloper** [eventflow/EventFlow#288]
Looking at the references I noticed that "EventFlow.RabbitMQ" has a reference to "EventFlow.TestHelpers" and it seems a bit wrong to me so I removed it and everything still compile succesfully.
Could you remove it?   ...or it has other meaning I missed?

**Comment by rasmus** [comment]
@MonDeveloper Doh, that's very wrong, will fix asap

**Comment by rasmus** [comment]
No types were used, so it shouldn't be a problem regarding the NuGet package. Fix is underway though.
