### ISSUE TITLE
DomainEvent event id metadata never changes

### ISSUE THREAD

**Issue by houseme-kyle** [eventflow/EventFlow#325]
Looking at AggregateRoot, is there a reason that the eventId never changes; this is ultimately used in the Metadata for domain events. 

`  var eventId = EventId.NewDeterministic(
                GuidFactories.Deterministic.Namespaces.Events,
                $"{Id.Value}-v{0}");`
_this will be identical for every event of an aggregate_

Thought the eventId was meant to be a unique identifier for each event generated.

**Comment by rasmus** [comment]
@houseme-kyle thanks for reporting that. It should have been `v{aggregateSequenceNumber}` instead of `v{0}`.

**Comment by houseme-kyle** [comment]
Thought that might be the case 👍
