### ISSUE TITLE
How to add TenantId in event

### ISSUE THREAD

**Issue by rvcssingh** [eventflow/EventFlow#337]
Hi,

I tried customizing the solution for creating multi tanent support but could not add tenantId as Aggregate Id.Please let me know how to do that.

**Comment by rasmus** [comment]
Not sure I follow, but you can create you own aggregate id's, simply create your own id class that implements IIdentity

**Comment by rvcssingh** [comment]
Yes,I created the same but when i passing the value through constructor it is asking to register service for that.

**Comment by rasmus** [comment]
@rvcssingh Have a look at #338

**Comment by rasmus** [comment]
@rvcssingh did the solution we discussed in #338 work for you?

**Comment by rvcssingh** [comment]
How to delete a aggregate. for eg. let say I have added one employee now I need to delete it by raising employeeDeleted event

**Comment by rasmus** [comment]
Invoke `IEventStore.DeleteAggregateAsync`, there's isn't a equivalent on `IAggregateStore` yet. I recommend doing it using e.g. the asynchronous-subscribers

http://eventflow.readthedocs.io/Subscribers.html?highlight=isubscribe#asynchronous-subscribers

**Comment by rvcssingh** [comment]
I am not able to find this
IsAsynchronousSubscribersEnabled.
I search it for but did not get anything in the code

**Comment by rasmus** [comment]
@rvcssingh Its right here https://github.com/eventflow/EventFlow/search?utf8=%E2%9C%93&q=IsAsynchronousSubscribersEnabled&type=

**Comment by rvcssingh** [comment]
I tried using ISubscribeAsynchronousTo and also register in application start using AddSubscribers.
Registered eventflow.hangfire and its working but handler method is not getting called.If i use ISubscribeSynchronousTo then only handler method get called.how to fix that

**Comment by rasmus** [comment]
@rvcssingh Have a look at the https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.Hangfire.Tests/Integration/HangfireJobSchedulerTests.cs test, it invokes subscriber in the `AsynchronousSubscribesGetInvoked` test

**Comment by rvcssingh** [comment]
Hi rasmus,
I am trying to understand Sagas from the document (http://docs.geteventflow.net/Sagas.html).
I have implemented the same but not sure it is correct or not as I did not find any example similar to what you provided in the doc.Thingy one is not fit the senario as it is very complex and not general.Can you please provide a sample code like stuff in more detail using the same example of sagas where you provide the logical flow of place order command.

**Comment by rasmus** [comment]
@rvcssingh I can, but it wont be any time soon. My recommendation is, if sagas seem too complex, then you properly don't need it.

Microsoft has a brief description of the concept here: https://msdn.microsoft.com/en-us/library/jj591569.aspx

**Comment by rasmus** [comment]
@rvcssingh closing as original question is answered
