### ISSUE TITLE
update docs to link to MongoDb and Firebase ReadStores

### ISSUE THREAD

**Issue by janfeyen** [eventflow/EventFlow#342]
Can you update your docs and add a link under the [ReadStores](http://docs.geteventflow.net/ReadStores.html) section to [EventFlow.Firebase](https://github.com/eventflow/EventFlow.Firebase) and [EventFlow.MongoDb](https://github.com/eventflow/EventFlow.MongoDB)?

**Comment by rasmus** [comment]
@janfeyen Could you provide a pull request? I haven't had much time for anything these last evenings. I would really like to support this, but I can't the next few days.

**Comment by janfeyen** [comment]
sure ... I'll do it tonight latest tomorrow. Firebase has 67 downloads so far, MongoDb 32. Hoping to get some more if they can find it via the official EventFlow docs.

Firebase works really nice with EventFlow clients as it solves the eventual consistency problem. ReadModel changes get pushed to all clients who subscribed to it. So no need to know when the ReadModel updated, Firebase just tells you by sending the new values.

**Comment by rasmus** [comment]
@janfeyen Very nice 😄

**Comment by rasmus** [comment]
Docs has been moved to its own repo
