### ISSUE TITLE
AddSubscriber/AddSubscribers does not support ISubscribeAsynchronousTo

### ISSUE THREAD

**Issue by Nysosis** [eventflow/EventFlow#343]
Documentation on http://docs.geteventflow.net/Subscribers.html states that for `ISubscribeSynchronousTo` and `ISubscribeAsynchronousTo` one should register via use of `AddSubscriber(...)`, `AddSubscribers(...)` or `AddDefaults(...)`. However neither `AddSubscriber(...)` or `AddSubscribers(...)` accept `ISubscribeAsynchronousTo` (AddSubscriber will not compile, and AddSubscribers throws a runtime error), and `AddDefaults` does not seem to pick up the subscription either.

EventFlow: 0.46.2886 from nuget

**Comment by rasmus** [comment]
@Nysosis verified, thanks for reporting. As a workaround you can register the subscribers as services for the interface `ISubscribeAsynchronousTo<,,,>`

**Comment by rasmus** [comment]
@Nysosis Fixed in v0.47.2894
