### ISSUE TITLE
Non-Generic Purge/Populate methods

### ISSUE THREAD

**Issue by houseme-kyle** [eventflow/EventFlow#345]
IReadModelPopulator to expose non-generic methods that take in the type. e.g.
public async Task PopulateAsync(Type readModelType, CancellationToken cancellationToken) or
public async Task PopulateAsync(IReadModel readModel, CancellationToken cancellationToken)

This allows the types to be determined during runtime then dynamically purged and populated. Use case as follows:
- Specify assembly of read stores to be purge/rebuilt
- Finds all IReadModel types within assembly
- Calls PurgeAsync then PopulateAsync

**Comment by rasmus** [comment]
Good idea, thanks for reporting.

**Comment by rasmus** [comment]
Will be in 0.48 release

**Comment by rasmus** [comment]
@houseme-kyle Released in [0.48.2937](https://www.nuget.org/packages/EventFlow/0.48.2937)

**Comment by houseme-kyle** [comment]
That was fast - thanks for adding it!

**Comment by rasmus** [comment]
no problem, it was a good idea
