### ISSUE TITLE
Doc: Add a readmodelrepository example

### ISSUE THREAD

**Issue by rlf** [eventflow/EventFlow#350]
In the documentation, you are missing the final link in the chain between readmodels and queries.
The example uses a `IUserReadModelRepository` but there is no example of how that would look.

Is it something that can be "autogenerated", or do I need to write a specific SQL-based repository (including interfaces) to access the ReadModel-store?

**Comment by rasmus** [comment]
@rlf good idea for the final link. EventFlow doesn't make any attempt at writing the SQL or ES queries and properly never will, its simply too complex and I personally wouldn't want them auto-generated as they often rely on e.g. indexes. In most cases I would guess that queries on read models would be based on a single property/column and then the SQL you be rather trivial

**Comment by k3daevin** [comment]
This should still be stated in the documentation. I was looking for these Repositories but yeah, it's to implementation specific.
