### ISSUE TITLE
UseEventStoreEventStore exception

### ISSUE THREAD

**Issue by ppXD** [eventflow/EventFlow#352]
MissingFieldException: EventStore.ClientAPI.StreamEventsSlice.NextEventNumber”。

code: 
```
var eventStoreIp = new Uri($"tcp://admin:changeit@localhost:2113");

var connectionSettings = ConnectionSettings.Create()
  .EnableVerboseLogging()
  .KeepReconnecting()
  .SetDefaultUserCredentials(new UserCredentials("admin", "changeit"))
  .Build();

IRootResolver rootResolver = EventFlowOptions.New
...
.UseEventStoreEventStore(eventStoreIp, connectionSettings)
.CreateResolver();
```

**Comment by rasmus** [comment]
@ppXD Please provide some details. You might be using a different configuration than the integration tests as those parsed green with the last release. Please verify your setup and check the differences between the integration tests,

https://ci.appveyor.com/project/rasmusnu/eventflow/build/0.48.2937/tests

**Comment by rasmus** [comment]
Almost a year old an no additional information or followup. Closing issue 😢
