### ISSUE TITLE
FilesEventPersistence.CommitEventsAsync causing IOException to occur

### ISSUE THREAD

**Issue by Nysosis** [eventflow/EventFlow#356]
I'm noticing this intermittently, getting a `IOException` thrown when trying to commit the events.

I think what's possibly happening is that the commit is being called from multiple threads (perhaps because of multiple requests firing events at the same time?), and end up in a race condition at [FilesEventPersistence.cs#L170](https://github.com/eventflow/EventFlow/blob/fa315bc60362df21d1f5f474c8234b268122d66b/Source/EventFlow/EventStores/Files/FilesEventPersistence.cs#L170), where one thread has claimed access to the file in it's call to `File.CreateText`, while a second thread hits the same bit of code at the same time.

I can't reliably replicate this, just seems to happen spuriously when I'm firing simultaneous requests to my API.

**Comment by rasmus** [comment]
@Nysosis You shouldn't use the file store for production environment as it isn't thread safe. I know it isn't stated very clear in http://docs.geteventflow.net/EventStore.html#files I'll update the documentation asap.

Please switch to a proper event store for production

**Comment by Nysosis** [comment]
I'm not using it production, wasn't planning on either :)

Just prototyping with it and occasionally happens from time to time

**Comment by rasmus** [comment]
@Nysosis great 😄 but yes, the file store isn't thread safe. If you have a single server setup and merely want to test EventFlow through a API, you could use the in-memory store.

I would be nice to have the file store thread safe, I'll create a issue for that
