### ISSUE TITLE
Alternative interface for configuration

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#36]
We need to rethink how the `EventFlowOptions` interface is and how users define configuration.

Proposals:

``` csharp
  // Option 1
  EventFlowOptions.New
    .As.EventSource().Use<MsSqlEventSource>()

  // Option 2
  EventFlowOptions.New
    .EventStore(r => r.Use<MsSqlEventStore())
```

@tabro Any other suggestions?

**Comment by rasmus** [comment]
The number of configuration options in EventFlow are increasing, making it hard to get an overview of the possibilities that the combined set of extension methods give. The problem could be addressed by doing the these changes.

- Grouping actions into relevant "sections" like the above example
- Provide guidelines on naming extension methods for `EventFlowOptions`

**Comment by JC008** [comment]
@rasmus Another concern to be aware of is the need for modularity, e.g. the need to register and configure a library that contains functionality at an application module level. Autofac modules provide a simple solution to the problem with it's [Module](http://autofac.readthedocs.org/en/latest/configuration/modules.html) approach and allows for a [hybrid of a builder and mapper](https://aphyr.com/posts/321-builders-vs-option-maps) to be used.

**Comment by JC008** [comment]
http://rogeralsing.com/2009/05/07/the-simplest-form-of-configurable-dependency-injection/

**Comment by rasmus** [comment]
Will open again when (and if) there's a suggestion for specific changes
