### ISSUE TITLE
Question about ReadModel and Aggreage consistency.

### ISSUE THREAD

**Issue by tatarincev** [eventflow/EventFlow#360]
`Command -> AggregateStore.UpdateAsync-> AggregateRoot.CommitAsync -> EventStore.StoreAsync -> DomainEventPublisher.PublishAsync -> DomainEventPublisher.PublishToReadStoresAsync` <- if the exception will be raised here what will be with consistency between read-models and aggregate?

**Comment by rasmus** [comment]
@tatarincev in-consistent 😢 currently EventFlow doesn't have any way of handling this. I have been working on #245 for some time, which will automatically apply missing events to read models on next event publish to the read model. This isn't the perfect solution I know, but I haven't found a good solution to do this.

I your case your left with a few choices, none of them very pretty.

- decorate the `IDomainEventPublisher` and detect the exception and do something
- decorate the `IReadStoreManager<TReadModel>` and handle it there
- handle the exception in the command handler
- come up with an alternative and create a PR

I have been thing about a very basic message (I would have used "event" here, but its rather overloaded here) system that allows you to hook into different parts of the EventFlow pipeline that would allow you to implement exception handling a bit easier.

Maybe something like this

```csharp
public class ReadModelExceptionHandler : IListenTo<ReadModelUpdateException>
{
   public Task HandleAsync(ReadModelUpdateException message)
   {
      // Do error handling here...
   }
}
```

Again, this is just an idea, but should allow you get some more control of whats happening inside EventFlow.

**Comment by tatarincev** [comment]
Many thanks for your detailed response. We will try to invent of something and definitely let you know if this is a good solution :)

**Comment by rasmus** [comment]
Closed as there hasn't been activity for more than a month on this question
