### ISSUE TITLE
support for reoccurring jobs

### ISSUE THREAD

**Issue by janfeyen** [eventflow/EventFlow#369]
I can't seem to find a way to schedule reoccurring jobs using hangfire?

**Comment by rasmus** [comment]
@janfeyen it isn't there, added as feature request

**Comment by rasmus** [comment]
Recurring jobs is part of the `IBackgroundJobClient` (see https://discuss.hangfire.io/t/enhance-interface-ibackgroundjobclient-for-unit-test/1450)
