### ISSUE TITLE
Is there any way of injhecting a dependency into an MSSQL read model?

### ISSUE THREAD

**Issue by roblevine** [eventflow/EventFlow#373]
I have an MSSQL readmodel, but need to inject some dependencies into it (e.g. a date time provider, a calculator class). 

I'd rather not go down a static service locator pattern, but the `UseMssqlReadModel `extension has a `new()` constraint on the read model.

Is there any way to access the container within the read model, or otherwise have dependencies injected in?

**Comment by rasmus** [comment]
Not through the constructor as the read models are created by Dapper. But the `IReadModelContext` passed in the `void Apply(IReadModelContext context, IDomainEvent<TAggregate, TIdentity, TEvent> domainEvent)` has an `IResolver` that you can use to resolve any needed services

**Comment by roblevine** [comment]
That'll teach me to try and solve these problems late on a Saturday night - totally missed the obvious.
Thank you.
