### ISSUE TITLE
Recover from "Commit transaction failed due to WrongExpectedVersion"

### ISSUE THREAD

**Issue by janfeyen** [eventflow/EventFlow#374]
Hi @rasmus 
I know this is more an EventStore question but I'm hoping you ran into this problem before.

We have rewritten an existing solution using EventFlow and are currently running the new system parallel with the old production system.
Everything running great and smoothly but now all of sudden, we are getting back "Commit transaction failed due to WrongExpectedVersion. TransactionID: 1886702422." on only 1 of the aggregates.
Most likely, we have a small bug lurking somewhere to get the aggregate in this state but we can't emit any events anymore on this aggregate. It always throws the WrongExpectedVersion error.

Is there any way to get this aggregate in a good state again? If this system is in production, what can we do?

Looking in EventStore, this aggregate is on event version 22, my readmodel used by the core api is also on version 22.

Any ideas/guidance welcome.

**Comment by rasmus** [comment]
I haven't any production experience with EventStore and my knowledge is very limited, but I'll try to help.

The `WrongExpectedVersionException` is caught in EventFlow and rethrown as an `OptimisticConcurrencyException` which basically means that two different threads/requests were editing the same aggregate at the same time. This is perfectly normal and something happens in our MSSQL event store several times a minute.

The exception is handled in EventFlow here https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.EventStores.EventStore/EventStoreEventPersistence.cs#L147

Under normal circumstances the aggregate stream is reloaded and the command handler is invoked again on the updated aggregate.

I would recommend you to have a look at the `EventStoreEventPersistence` to see if something looks odd.

**Comment by rasmus** [comment]
@janfeyen I wrote a test for EventFlow in #375

**Comment by rasmus** [comment]
@janfeyen I couldn't reproduce your problem via #375. Am I missing something?

**Comment by janfeyen** [comment]
closing it as it hasn't happened again
