### ISSUE TITLE
Split addins into their own repos

### ISSUE THREAD

**Issue by edwardwilson** [eventflow/EventFlow#378]
The main EventFlow repo has grown large and contains many addin projects. These should be moved to their own git repos where issues and work can be tracked better. Here are some I have identified as good moves to start.

- [ ] Move Elasticsearch to EventFlow.Elasticsearch  [#307](https://github.com/eventflow/EventFlow/issues/307)
- [ ] Move Documentation to EventFlow.Documentation [#306](https://github.com/eventflow/EventFlow/issues/306)
- [ ] Move Samples to EventFlow.Examples

**Comment by edwardwilson** [comment]
@rasmus I do not have permissions to create new repos in EventFlow, if you want to create the repos I can move the code, or add the permissions for me to do this? I don't mind either way.

**Comment by edwardwilson** [comment]
Consideration about build and deployment to nuget.org will need to be looked at too with these splits

**Comment by rasmus** [comment]
Before moving everything, I would like a solution for managing build files. So far the best I have come up with is a submodule and make the `build.cake` more convention based

**Comment by edwardwilson** [comment]
Yes it would be good to have a standard build, I am curious though why there is a need for a cake build. Can a simple MSBuild combined with the bespoke `appveyor.yml` per repo work? I feel a submodule would complicate the getting started for newcomers to contribute.

**Comment by rasmus** [comment]
I'm all for simplifying the build setup, but I prefer Cake to MSBuild configuration. If you have a good idea for simplification, create a pull request, I would love to see it.

I'm off this weekend so my support will be limited, but I hope to be to write to you soon.
