### ISSUE TITLE
CD pipeline help

### ISSUE THREAD

**Issue by Brandon2255p** [eventflow/EventFlow#381]
Hi, I have a question that kind of boils down to the framework (EventFlow in our case ). I have been looking at various patterns for deploying our microservices to production and it seems like we could benefit from a container based continuous delivery pattern. We have chosen RabbitMQ to talk to our different services. Each service has aggregates and read models. We use an EventStore for each microservice as the event database.

**Comment by Brandon2255p** [comment]
Sorry I clicked submit before I finished.

So I am having trouble understanding a couple key aspects of the pipeline. I know this is a lot to ask of an opensource project but is it possible to maybe Skype someone who can explain some things regarding setting up a staging environment and how to load balance between containers. I think we may have used our RabbitMQ wrong.

**Comment by rasmus** [comment]
@Brandon2255p I'm sorry, but I'm closing this issue as "out of scope". Its a very interesting discussion, but not something we merely could discuss on Skype.

I can recommend some if the articles listed here though

https://github.com/eventflow/EventFlow#useful-articles-related-to-eventflow-and-ddd

**Comment by Brandon2255p** [comment]
Thanks @rasmus
