### ISSUE TITLE
Finding my AggregateRoots to be fairly anaemic, is this expected?

### ISSUE THREAD

**Issue by Nysosis** [eventflow/EventFlow#382]
So, from using the framework for a bit, what I'm finding more and more, is that my AggregateRoot is nothing more than a dispatcher for the relevant events that build up the read models, and that storing any form of state on the roots is generally unnecessary (except for when needed for Specification logic).

Am I missing something, or is this sort of pattern the expected way?

**Comment by rasmus** [comment]
@Nysosis That is the case if you have a really simple domain. If your domain is complex and you managed to simplify that much, then you did a good job 😄

I would recommend reading a bit about DDD, specially around ubiquitous language. The aggregates and events should map directly to how you talk about your business, it makes it considerably easier anyway. Again, this might over-complicate a good setup.

**Comment by rasmus** [comment]
Closing issue after one month without feedback
