### ISSUE TITLE
Is need empty CTOR for IReadModel?

### ISSUE THREAD

**Issue by SergeyIlyin** [eventflow/EventFlow#390]
Do we need an empty designer of **IReadModel** in the next factory?
```
IReadModelFactory<TReadModel>
        where TReadModel : IReadModel,  new()
```
Can it be deleted?

I am start works for EF.Core ReadStore for exist DB where ReadModel inherits model  with not empty constructor.

**Comment by rasmus** [comment]
It isn't needed any more as any custom read model construction can be handled by `IReadModelFactory`

**Comment by rasmus** [comment]
@SergeyIlyin If you create a EventFlow.EntityFramework package, I can create a repo at the eventflow org if your interested.

**Comment by SergeyIlyin** [comment]
I removed empty constructor requirements in my own branch.
The EventFlow.EntityFramework package needn't at this time. I will create the pull request later.
