### ISSUE TITLE
Add support for unicode characters in type names

### ISSUE THREAD

**Issue by frankebersoll** [eventflow/EventFlow#397]
When you talk to non-english customers about their non-english domain, having a common [ubiquitous language](http://www.jamesshore.com/Agile-Book/ubiquitous_language.html) gets invaluable real quick. The need to translate back and forth between terms that are actually used in the business and far-fetched or even wrong translations will easily frustrate developers.

Furthermore, having a non-english ubiquitous language [comes with its own quirks](https://www.webfactory.de/blog/ubiquitous-language-in-a-non-english-domain): Developers have to agree upon where to use which language, and how they will be combined in identifiers: Is it `GetItem()` or `GetEintrag()` or even `EintragAbrufen()`? 

If your team decides on non-english identifiers, it will make a difference being able to use Umlauts, Accents, other diacritics or whatever your language has going for you - or having to fake it with `[A-Za-z0-9]`.

I propose to update any Regex that might benefit from it to use the corresponding unicode character classes:

- [X] `VersionedTypeDefinitionService.NameRegex` (for events, commands, jobs and snapshots)
- [X] `Identity.ValueValidation` (for identities)
- [X] `Label.NameValidator` (for naming things like tables and whatever)
- `MsSqlConnectionString.DatabaseReplace/Extract` (not touching this)
- [X] `CommandPublishMiddleware.CommandPath` (for ASP.NET routes)

**Comment by rasmus** [comment]
@frankebersoll Very good input

**Comment by rasmus** [comment]
Close by #396
