### ISSUE TITLE
RabbitMQ Username + Password support

### ISSUE THREAD

**Issue by marcopasveer** [eventflow/EventFlow#408]
Heya, Awesome project, one problem we are having though:

Currently your 'RabbitMqConnectionFactory' does not support a custom Username + Password. Logins are  done using the guest user.

Since our RabbitMQ cluster requires a username+password the following exception is being thrown:

BrokerUnreachableException: None of the specified endpoints were reachable ---> RabbitMQ.Client.Exceptions.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.

We fixed this by using a custom RabbitMqConnectionFactory, but it would be nice to support it out-of-the-box.

Thanks in advance for your reaction, 

Marco.

**Comment by rasmus** [comment]
@marcopasveer the RabbitMQ integration tests currently provides username and password via the URI, e.g. `ampq://username:password@example.org`.Do you have a link to the documentation for the format/method you use?

**Comment by marcopasveer** [comment]
My apologies, 

I was unaware that I could provide the username and password through the url.
The connection is succeeding now.

I implemented a custom IRabbitMqConnectionFactory where I was able to set the UserName and Password in the RabbitMQ.Client.ConnectionFactory.

Thanks.
