### ISSUE TITLE
EventStore's LoadAllCommittedEvents is too inefficient

### ISSUE THREAD

**Issue by mattgi** [eventflow/EventFlow#409]
`Population of read model 'User' took 86.158 seconds, in which 27 events was loaded and 27 was relevant`

Our current test EventStore instance has been sitting idle for weeks but has system generated $stats events, etc. being written to it constantly. As such, about 99.9% of its events are not related to app data. If I'm reading things correctly, I think it has 1145078675 events in it (and we care about 27).

Our issue then arises when we attempt to populate our read models. The current implementation within `LoadAllCommittedEvents` calls the EventStore client's `ReadAllEventsForwardAsync` method to read all aggregate events and is therefore quite inefficient.

By this, I mean that it pulls in every event and then [discards those that start with a `$`](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.EventStores.EventStore/EventStoreEventPersistence.cs#L72).

Am wondering if there is a way to only retrieve the events we need - perhaps via streams or some other EventStore construct (perhaps one stream per aggregate is created at time of publish or something). My initial thoughts are that IReadModelPopulator's PopulateAsync method goes on to only request the single read model that has been supplied. I believe in its current setup, if we wanted to populate several read models at once, we would be re-running that same LoadAllCommittedEvents method each time.. so 90 seconds per read model (when we only care about maybe 150 events in total across every read model at present).

I'm not sure about streams though. Really don't know which way to go. EventStore's doc on 
[reading-events](https://eventstore.org/docs/dotnet-api/4.0.2/reading-events/) also suggests that even streams would be inefficient and `"It is unlikely that client code would need to actually build a list in this manner. It is far more likely that events would be passed into a left fold in order to derive the state of some object as of a given event"`.

I do not have much/any experience with EventStore but believe it should be what we're using, given that Greg Young is behind it... just need to figure out how to best use it. Any ideas?

**Comment by rasmus** [comment]
@mattgi The current implementation _is_ inefficient as it needs to go through every single event to make sure it gets the correct event for the read models when you repopulate. The main reason is the `IReadModelLocator`, i.e., EventFlow has no clue to what the relation is between read models and events.

I have been working on something that would make it a bit better. The PR #245 which basically creates a one-to-one relationship between read models and aggregate roots, which then could be used for repopulating specific read models.

I have been able to think up a generic method that involves the `IReadModelLocator`s yet, ideas are welcome.

In your case, if you know which events you want to go through your read models again, then load the events using e.g. `IEventStore` and pass them to the `IReadStoreManager`. The interfaces are pretty clean and the implementation shouldn't be more than a few lines of code.

**Comment by janfeyen** [comment]
@mattgi Eventstore has the concept of [scaffolding](https://eventstore.org/docs/server/4.0.2/scavenging/) and settings for configuring how many stats to keep on a stream.
So set $maxAge, $maxCount or $tb metadata on your $ streams and run the scavenger.

**Comment by mattgi** [comment]
We were just about to switch to MS SQL - a more familiar terrain. Are either of you using EventStore with confidence?

**Comment by janfeyen** [comment]
We have been using it in production for about 3 months now.
We haven't had a single technical problem related to eventstore

**Comment by mattgi** [comment]
Okies.. will persist.. just trying the $maxAge stuff but will probably do as @rasmus suggests and roll my own multi read model solution so I can just do one pass. Thanks guys.
