### ISSUE TITLE
High volume of commands in a saga

### ISSUE THREAD

**Issue by sreagleeye** [eventflow/EventFlow#410]
I am using an AggregateSaga to process a large feed file. The saga is started by a FeedStarted event issued to the tenant which is running the feed. While the feed runs, it issues commands to different Aggregates to create/update those entities based off information provided in the feed. These feeds can contain over 100,000 records which could ultimately issue upwards of 1 million commands. 

Looking at the implementation of the Publish method on the AggregateSaga, the Commands are added to a Collection of unpublished events and only issued after the handler for the FeedStarted event exits. 

My concern is that when a large number of commands are created, this will put a heavy burden on the memory footprint of the application. Is there a way to publish these commands more incrementally? Or perhaps, do you recommend a different approach to this problem? 

```
public class FeedProcessManager :
  AggregateSaga<FeedProcessManager, FeedProcessManagerId, FeedProcessManagerLocator>,
  ISagaIsStartedBy<TenantAggregate, TenantId, FeedStarted>
{
  public FeedProcessManager(FeedProcessManagerId id) : base(id) { }

  public Task HandleAsync(IDomainEvent<TenantAggregate, TenantId, FeedStarted> domainEvent, ISagaContext sagaContext, CancellationToken cancellationToken)
  {
    Emit(new FeedProcessStarted(/*...*/));
    
    ProcessFileRecords(/*...*/);
    
    // Issue a command back to the TenantAggregate
    Publish(new CompleteFeed(/*...*/)); 
	
    Complete();
    
    return Task.CompletedTask;
  }

  public void Apply(FeedProcessStarted e) { /*...*/ }

  private void ProcessFileRecords(/*...*/)
  {
    //Create CSV File reader
    /*
    ...
    */
    
    while (csvReader.Read())
    {
      //Issue a command to each Aggregate within the feed file
      Publish(new CreateThingy1(/* Some row data */));
      Publish(new CreateThingy2(/* Some other row data */));
    }
  }
}
```

**Comment by rasmus** [comment]
I wouldn't use the sagas for CSV processing as it seems to be pretty low-level stuff to have in your domain (I might be wrong though). If it's just file processing, I would recommend moving it to a separate service, implement some batching (if possible) to better keep track of progress and then simply iterate through the CSV records there.

**Comment by rasmus** [comment]
As an example I have seen usage of RabbitMQ for records processing. One process iterates through the CSV file and published it to RabbitMQ, then multiple consumers take the records and process them in parallel. Keep in mind that you need to handle proper ordering and duplicate messages (if these are a concern).

**Comment by sreagleeye** [comment]
For my purpose, I think it makes sense to have a Feed as part of my domain. It can hold configuration information, validate if the feed is allowed to run, track runs, provide statistics, etc. That said, I like the idea of using another queue to hold the records to process.

To bring all the ideas together, the FeedProcessManager saga will still start from the Tenant's FeedStarted event. The handler for that event will kick off a process to load records from a file into a queue. Then, multiple queue readers will take those records and issue commands to the various aggregates. The FeedProcessManager saga will listen to events from those aggregates and issue followup commands.

Thanks for the help!

**Comment by rasmus** [comment]
@sreagleeye glad that you found a solution
