### ISSUE TITLE
Event Upgrade Manager Deferred Execution

### ISSUE THREAD

**Issue by houseme-brandon** [eventflow/EventFlow#413]
We have noticed an issue in the EventUpgradeManager since upgrading to dontnet core x64.

The following code segment results in null events being sent to the OrderBy()

```
return domainEventList
                .SelectMany(e =>
                    {
                        var a = eventUpgraders[e.AggregateType];
                        return a.EventUpgraders.Aggregate(
                            (IEnumerable<IDomainEvent>) new[] {e},
                            (de, up) => de.SelectMany(ee => a.Upgrade(up, ee)));
                    })
                .OrderBy(d => d.AggregateSequenceNumber);
```

I am not sure why this has only surfaced when we use dotnet core x64 but both SelectMany and OrderBy are implemented using delayed execution. The `a.Upgrade(up, ee)` was never being called which I suspect causes the values to be null. We fixed this by adding a `.ToList()` before `OrderBy()` to execute the upgrades.

**Comment by houseme-brandon** [comment]
@rasmus Not yet, currently using Azure App Services. Will be moving to linux dockers in the future. Is there a known issue related to that?

**Comment by rasmus** [comment]
@houseme-brandon No, I was merely trying to reproduce it without any success and was thus trying to recreate the same setup

**Comment by rasmus** [comment]
😢

**Comment by Brandon2255p** [comment]
Sorry!
I have tested it again and it seems fine.. I am really confused as to what happened previously.
Will re-open if I see it again

**Comment by rasmus** [comment]
@Brandon2255p perfect, thanks.
