### ISSUE TITLE
PostgreSQL or MySQL Support

### ISSUE THREAD

**Issue by ptwenke** [eventflow/EventFlow#414]
Is either PostgreSQL or MySQL supported?  If so, how do I configure the framework to do so?

**Comment by edwardwilson** [comment]
There is no direct support for either of these databases. However you could take a look at the MSSQL or the SQLite projects to see how they are implemented. 

EventFlow is very customisable and can be extended by the configuration to use and custom data store. A pull request for either of these two are welcomed

**Comment by ptwenke** [comment]
I'll get started on the PostgreSQL support.

**Comment by rasmus** [comment]
@ptwenke I think that AppVeyor supports Docker in their build, might be a good idea for integration testing

**Comment by ptwenke** [comment]
@edwardwilson @rasmus , do the examples in the README show the APIs from the `develop` or `master` branch?  Which branch should I branch from?

**Comment by rasmus** [comment]
@ptwenke As soon as I get some time I'll try to split most of the packages to individual repos. Thus a new repo for PostgresSQL would be best

**Comment by ptwenke** [comment]
@rasmus , would you prefer I wait for the new repo before creating a PR?

**Comment by rasmus** [comment]
@ptwenke it would seem that I'm a bit slow in doing the repo cleanup. Lets start with a PR on this repo and  it can be moved later at some point.

**Comment by rmess** [comment]
@rasmus Did you complete the PostgresSQL Support ?

**Comment by wenkepaul** [comment]
@rmess , yes, but I didn't write the unit tests yet.
https://github.com/ptwenke/EventFlow

**Comment by rmess** [comment]
Thank you,
I'm currently working on my own version too and I have some issues with the unit tests on the snapshots coverage part.

`System.IO.FileLoadException : Could not load file or assembly 'Npgsql, Version=3.2.6.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

I don't know how to fix this and it's make my fails a lot of tests.

**Comment by wenkepaul** [comment]
@rmess , I'll take a look at your tests tonight.

**Comment by rasmus** [comment]
Let me know if you need anything

**Comment by wenkepaul** [comment]
@rmess what branch are your working on?

**Comment by rmess** [comment]
implement-postgre-backend

**Comment by rmess** [comment]
@wenkepaul  @rasmus my version is pushed. Did you saw it ?

**Comment by wenkepaul** [comment]
@rmess , I'll be able to take a look tomorrow night.

**Comment by anthonyhuebers** [comment]
We are waiting for this functionality. Is there any prospect when this is going to be released?

**Comment by rasmus** [comment]
Hi @anthonyhuebers there is. If you have experience in working with PostgreSQL you can help out with the final tests in PR #479

**Comment by rasmus** [comment]
PostgreSQL support is done
