### ISSUE TITLE
best practices for Event payloads and optional fields

### ISSUE THREAD

**Issue by mattgi** [eventflow/EventFlow#415]
If I have an Event that includes optional fields, what should be stored in the Event Store?

For example, 

```
  [EventVersion("UserDetailsUpdated", 1)]
  public class UserDetailsUpdated : AggregateEvent<UserAggregate, UserId>
  {
    public string FirstName { get; set; }

    public string LastName { get; set; }

    public UserDetailsUpdated(string firstName, string lastName)
    {
      FirstName = firstName;
      LastName = lastName;
    }
  }
```

If the user only updates `FirstName`, what pattern should be used to ensure only the _set_ / _patched_ data is written to the event store? Or should `LastName` be included, but with a null value. If the latter, what then happens when the user explicitly wants to remove their `LastName`?

My code is presently turning in to a whole bunch of `string.IsNullOrEmpty` checks before I set fields and I'm sure there must be a better approach.

**Comment by rasmus** [comment]
@mattgi It only matters if it has some significant meaning in your domain. If you later want to create events that explicitly state that only the first name was changed, you can do so using event upgraders (http://docs.geteventflow.net/EventUpgrade.html). Personally I would set the first and last name, as only having one could be misunderstood as removing e.g. the last name and not only updating the first.

**Comment by mattgi** [comment]
> set the first and last name

Just to confirm in my own head based on a working example... (i.e. that the absence of a field in the request results in the field's removal). Would you agree that the flow would be as follows:

Data
```
FirstName : "Prince Roger",
LastName : "Nelson"
```

1. A request comes through to the UpdateUserDetails command (to update first name):
```
{ firstName : "Prince", lastName: "Nelson" }
```

Results in the Event:

```
{ firstName : "Prince", lastName: "Nelson" }
```

---

2. A 2nd request comes through to the UpdateUserDetails command (to remove Last Name):
```
{ firstName : "Prince" }
```

Results in the Event:
```
{ firstName : "Prince", lastName: "" }
```

_(a fairly contrived example (perhaps an Address update would have been better) but I think this will firm up my thinking)_

**Comment by rasmus** [comment]
@mattgi That would make sense to me, but again, its really up to how you as a group talk about the domain.

some examples

remove last name
```json
{ "firstName" : "Prince", "lastName": "" }
```

only update first name
```json
{ "firstName" : "Prince" }
```

if there's uncertainty regarding what the different values mean, you could wrap the value in value object

```c#
[JsonConverter(typeof(SingleValueObjectConverter))]
public class NamePartUpdate : SingleValueObject<string>
{
  public NamePart(string value) : base(value) {}
  public bool IsUpdated => Value != null;
  public bool IsUnknown => Value == null;
}
``` 

or if you like enums better

```c#
public enum NamePartUpdateAction
{
  Skipped,
  Updated,
  Removed
} 

[JsonConverter(typeof(SingleValueObjectConverter))]
public class NamePartUpdate : SingleValueObject<string>
{
  public NamePart(string value) : base(value) {}
  public NamePartUpdateAction UpdateState
  {
    get {
       switch (Value) {
          case null: return NamePartUpdateAction.Skipped;
          case "": return NamePartUpdateAction.Removed;
          default: return NamePartUpdateAction.Updated;
       }
    }
  }
}
``` 

(haven't checked if it actually compiles)

I recommend creating value object to represent values that might be misunderstood, but it really depends on how complex you want your code base and if value objects is something you like. I usually go overboard regarding value objects and almost wrap every single primitive in the domain in one... but as I said, that might be a bit too much.

check http://docs.geteventflow.net/ValueObjects.html#making-pretty-and-clean-json to make sure any value objects serialize to some nice JSON.

**Comment by mattgi** [comment]
Ah true.. had not considered ValueObjects for simple types; makes sense.. thanks!
