### ISSUE TITLE
 Saga: Where should business logic go?

### ISSUE THREAD

**Issue by wgtmpeters** [eventflow/EventFlow#418]
After reading all examples and test code of EventFlow is am still confused about where business logic should go.

For example the following workflow:
1 Some DomainService sends the CreateOrderCommand
2 CommandHandler handles the Command and calls updateAsync on the OrderAggregateRoot
3 The OrderAggregateRoot Emits the OrderCreatedEvent
4 Saga is created for the OrderCreatedEvent
5 From this Saga a process should be started that takes the information from the OrderCreatedEvent
In order to process this information the Saga needs more then the information that is has right now. For example by calling some injected services for processing/data.
6 Sage Sends the next command that the OrderAggregate processes with the calulated information

**How to handle step 5?**
It seems like there is no way to do this from within the saga, as no injection is done at this point.
As I understand that the Saga should be seen as a Process Manager I can understand this limitation.

I also understand that a Command should contain all information that is needed to process that command in CommandHandler for the aggregateRoot. Which means that the CommandHandler can not do anything with that data except validate it and send it to the AggregateRoot.

So what option's do i have to implement step 5?
I can use normal Subscribers for the DomainEvents to handle step 5, but then I see no use for the Saga.
Or should the Saga emit an Event that lets a Subscriber handle step 5?

**Comment by rasmus** [comment]
@wgtmpeters Microsoft has written a free book about CQRS and ES that's very easy to read. There's a article about sagas that might clarify how you might do it.

![image](https://user-images.githubusercontent.com/18956/35137721-241feadc-fceb-11e7-8e3e-0fe81ae05c2e.png)

From https://msdn.microsoft.com/en-us/library/jj591569.aspx

**Comment by wgtmpeters** [comment]
@rasmus I came across that article before. 
In this example when using Saga's it would mean that between order created and sending the MakeReserveration command the Saga would not be able to get any more information than it already has correct?

So how would a Saga handle your example with VoyageScheduleUpdatedEvent that starts th e VerifyCargosForVoyageJob (the Job part is not important, it just processes some data which results in commands to AggregateRoots.)

Would you mix Saga's with normal subsribers that trigger Domain like services like in the example of VerifyCargosForVoyageJob?

**Comment by rasmus** [comment]
@wgtmpeters If you need any additional information from within a saga, you could simply take in the any required services in the constructor along with the saga ID and use these in the saga handlers.

We could also expand the `ISagaContext` to container a `IResolver`, it would make it possible for each developer to chose their style (some like services via the constructor and others prefer requesting them when needed).

I would mix sagas with subscribers as the chain of events then become rather complex.

Please note that my personal experience in working with sagas is rather limited. I implemented the feature as I though that I needed it, but ended up not doing so.

**Comment by wgtmpeters** [comment]
@rasmus  thank you for your help. Right now we have solved this by injecting domain Services into the Saga.
