### ISSUE TITLE
ReflectionHelper.CompileMethodInvocation

### ISSUE THREAD

**Issue by domenkogler** [eventflow/EventFlow#422]
Bug report

http://docs.geteventflow.net/Aggregates.html#events states that Appy method _can_ be `private`, but `private` **Apply** methods throws `ArgumentException` in AggregateRoot static constructor.

Pull request solves this issue https://github.com/eventflow/EventFlow/pull/421

**Comment by rasmus** [comment]
Released in 0.53.3204
