### ISSUE TITLE
Some questions about the implementation of the DDD

### ISSUE THREAD

**Issue by xiedeyou** [eventflow/EventFlow#423]
1、is the entity a value object?Must the entity need Identity?
eg:  order is a aggregate ,orderline is a entity. i think orderline Identity is not required.

2、ISqlReadModelStore how to find multiple readmodel?

**Comment by rasmus** [comment]
1) If you follow DDD then you distinguish to different entities from each other by their IDs. If the ID is the same, then its the same object. In your example an order line may simply be a value object, i.e., inherit from `ValueObject`. EventFlow `Entity` is also a value object and one could argue that the equality comparison should only be on the ID and not all of its attributes.

2) The actual queries to your MSSQL read models should be made by you, e.g. if you want to find all blog posts from a user, then you should have an index column with the user ID. EventFlow only helps in keeping the read models up to date.

Hope that answers your questions

**Comment by xiedeyou** [comment]
if order line is a ValueObject,So it doesn't need ID。
I think the entity is ValueObject and Contain ID  is contradictory.

Thank you for your answer to the second questions.

**Comment by rasmus** [comment]
Hi @xiedeyou although Entity inherits from `ValueObject`, its equality is calculated based on only the ID.

See here
https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/Entities/Entity.cs#L48
