### ISSUE TITLE
Sagas trigger without domainEvent

### ISSUE THREAD

**Issue by wgtmpeters** [eventflow/EventFlow#424]
I have a question about how to Trigger some Process in a Saga depending on some Timed Event.
In our case Some time in the future some Command should be send, ideally we want this to also be triggered from the Saga.
Is there a way to awaken the Saga somehow at the moment by a Cron job / timer?

Otherwise the only clean solution I think would be a domainService that handles this part Without being called by the saga but simple whenever the Timer is triggered.
Another way but not clean by my oppinion would be to somehow Create the DomainEvent that the Saga needs to trigger after the Timer has gone off. But that would not be correct usage of DomainEvents correct?

**Comment by rasmus** [comment]
@wgtmpeters EventFlow doesn't currently support invoking sagas without a domain event.

At work we have discussed how to handle "something needs to happen at this time" in our domain and typically they have fallen into two different categories.

- Part of the domain, e.g. listing is about to expire. In these cases it has made sense to trigger the event via a command from some domain services that is triggered by a job or timer. The domain would then have a name like `ExpirationRequested` which would then kick start the saga.
- The event wasn't part of the domain (but a side effect might be) and in these cases we simply model it without the domain.

I do however think it would be a good idea to add the functionality to EventFlow and allow developers to invoke sagas without the need of events.

Remember that EventFlow can fire commands at a specific time if using the `PublishCommandJob`. Simply install e.g. Hangfire and `EventFlow.Hangfire` and use the built-in scheduling.

**Comment by rasmus** [comment]
Also, as sagas by default are aggregates, you could update a saga simply use `IAggregateStore.UpdateAsync` to update it. You would need to invoke `PublishAsync` on the saga yourself to get any commands published.

**Comment by wgtmpeters** [comment]
@rasmus do you mean sending a Command to a AggregateRoot which would result in the ExpirationRequest Event for that the saga handles?

Or manually creating a DomainEvent without sending a Command first?

**Comment by wgtmpeters** [comment]
@rasmus if you have any ideas what you would expect the direct awakening of saga should look like maybe I will do a implementation of it.

**Comment by rasmus** [comment]
@wgtmpeters I doesn't sound too complicated and may help cleanup some of the saga code base. I'll give it a give it a go tomorrow.

**Comment by rasmus** [comment]
@wgtmpeters Have a look at PR #435. You would be able to use the simplified `ISagaStore.UpdateAsync` to update sagas without any domain events, e.g. via a trigger

**Comment by wgtmpeters** [comment]
@rasmus  look good to me.
Why are you not using the SagaStore as BaseClass for SagaAggregateStore ? You are only using it for the Test Alternative Saga Store.

**Comment by rasmus** [comment]
@wgtmpeters You are absolutely correct, just a slip of my mind. Thanks for going though the PR. I have created #440 to fix it

**Comment by rasmus** [comment]
Fixed in release 0.55.3323
