### ISSUE TITLE
[Question] Not found the GettingStartedExample test method in GettingStarted document.

### ISSUE THREAD

**Issue by idubnori** [eventflow/EventFlow#426]
I cound not find out `GettingStartedExample` test method on `master` / `develop` branches.
Anybody could let me know? Thank you in advance.

> The example code provided here is located within the EventFlow code base exactly as shown, so if you would like to debug and step through the entire flow, checkout the code and execute the GettingStartedExample test.
[Getting Started](http://docs.geteventflow.net/GettingStarted.html#getting-started)

**Comment by rasmus** [comment]
The example was moved to the documentation repo, I'll get the docs updated https://github.com/eventflow/Documentation/blob/master/Source/EventFlow.Documentation/GettingStarted/ExampleTests.cs

**Comment by rasmus** [comment]
put in a crude link for now

**Comment by idubnori** [comment]
Thank you! I could Get Started in a real sense.
