### ISSUE TITLE
Questions about readmodel update

### ISSUE THREAD

**Issue by cykelbud** [eventflow/EventFlow#427]
I've been looking at your lib and it looks very nice :)

But I have some difficulties trying to create a readmodel for an aggregate containing a list of entities, using the extension lib EventFlow.MsSql.

My aggregate contains a property that is a list of an entity (lets say 3 items).

I'm trying to create a readmodel that uses the entity-Id as identityColumn, so that I can easily get entities for later queries.

I use the ReadModelLocator to get all entity-Ids (which works fine), and then the entityReadmodel.Apply method is called 3 times. But It doesn't give any information for what entity-Id the Apply-method is invoked for. So I dont know what item in the aggregates entitylist to set as Id for the readmodel.

Can you give me some suggestions on how to implement this in the readmodel?

**Comment by rasmus** [comment]
@cykelbud EventFlow uses [Dapper](https://github.com/StackExchange/Dapper) behind the scenes to write MSSQL read models to the database and AFIK having properties that are lists isn't possible.

I sounds link you might want to have a look at how the [`MsSqlThingyMessageReadModel`](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.MsSql.Tests/IntegrationTests/ReadStores/ReadModels/MsSqlThingyMessageReadModel.cs) is implemented in the MSSQL read model integration tests.

**Comment by rasmus** [comment]
Closed due to lack of activity
