### ISSUE TITLE
Atomic event persistance and publishing

### ISSUE THREAD

**Issue by domenkogler** [eventflow/EventFlow#433]
Persisting events and publishing shoud be an atomic operation. This is hard to acieve; it needs two phase commit, distibuted transactions or some other techniques like MassTransit Courier with RoutingSlips - for my project i will use last option since I will use MassTransit anyway.

For now this two operations should be as close as possible, therefore i propose moving domain events publishing from AggregateStore to EventStoreBase @ Pull request #432.

AggregateStoreTests are failing and needs review.
Publisher should not throw OptimisticConcurrencyException, event persistence should instead.

Also EventStore needs Tests.

**Comment by rasmus** [comment]
@domenkogler You can't move it as the event store doesn't have any concepts of command results, You removed the [aggregateUpdateResult.Result.IsSuccess](https://github.com/eventflow/EventFlow/pull/432/files#diff-71df9f46b0ac19de16880fd1b52b7a42L146) check. If a developer returns a failed command results, no events be committed or publish

**Comment by domenkogler** [comment]
Publish is now triggered inside [aggregate.CommitAsync](https://github.com/eventflow/EventFlow/pull/432/files#diff-71df9f46b0ac19de16880fd1b52b7a42R125) that is heuristically impossible to reach if developer returns failed command, because of [this return statement](https://github.com/eventflow/EventFlow/pull/432/files#diff-71df9f46b0ac19de16880fd1b52b7a42R120).

I followed simple principle: if event is stored it must be also published. All checks should be made before  persistance is made therefore is it save to publish it there.

**Comment by rasmus** [comment]
But the events aren't committed at that point, yes, the in-memory aggregate is updated but the events aren't committed to the event store until line [125 in that file](https://github.com/eventflow/EventFlow/pull/432/files#diff-71df9f46b0ac19de16880fd1b52b7a42R125). Events aren't committed if the command result is unsuccessful and they aren't published either with the current implementation, which is also covered by the test [here](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.Tests/UnitTests/Aggregates/AggregateStoreTests.cs#L182).

**Comment by domenkogler** [comment]
Yes exactly, we are talking the same thing. And this is exactly the same also with my implementation. Events are published [here](https://github.com/eventflow/EventFlow/pull/432/commits/170ecb894b62271d94fe74f8b9ee57636c722ea2#diff-74b115a777344065c5c095b1b9273680R119), **after** persisting them.

**Comment by rasmus** [comment]
@domenkogler Ah, sorry. You are right and it makes sense. It still changes behavior as any sub-subsequent commits to the event store or any other places that could throw `OptimisticConcurrencyException` would trigger another update of this original aggregate.

**Comment by domenkogler** [comment]
I am not sure I understand what is the problem with `OptimisticConcurrencyException`. In case of that exception events are not commited or published, so eventual consistency is still there.

**Comment by rasmus** [comment]
@domenkogler A bit more detailed

1. Command A is published which triggers that event A1 is emitted from aggregate A
1. Event A1 is committed to the event store
1. Subscriber B subscribes to event A1 and publishes command C
1. Command C triggers event C is emitted from aggregate C
1. A optimistic concurrency exception happens five times as aggregate C is under heavy update
1. Event C is *not* committed as the number of `OptimisticConcurrencyException` exceeds the [configured limit](https://github.com/eventflow/EventFlow/blob/e0f60416d3598117aa8c2c2dc706d42604eedbd1/Source/EventFlow/Configuration/EventFlowConfiguration.cs#L39) and the `OptimisticConcurrencyException` is thrown by the aggregate store
1. The `OptimisticConcurrencyException` is caught in the retry loop of the commit path of event A1 as the event dispatching is moved within the transient fault handler
1. Command A is retried by reloading aggregate A (now with event A1 in its history) and event A2 is emitted (give this is legal within the domain)
1. Event A2 is committed to the event store
1. Subscriber B subscribes to event A2 and publishes command C (again)
1. _continues_ ...

The above is the same for any exception thrown by any of the other dispatchers that are invoked from within the [DomainEventPublisher](https://github.com/eventflow/EventFlow/blob/e0f60416d3598117aa8c2c2dc706d42604eedbd1/Source/EventFlow/Subscribers/DomainEventPublisher.cs#L82)

Hope that clarifies it, it not, then let me know.

In addition, the reason for separating the event store into the event store and aggregate store, is to allow developers to access events without having them published, e.g. if you wan't to import large amounts of events (no efficient API is there yet, but it has been requested).

I understand your concern, but the events are published right after events are committed, the code paths aren't that different between the current code and the code in the PR.

**Comment by domenkogler** [comment]
First of all, thank you for really detailed explanation. I understand exactly what you are trying to explain to me.
I now see that the way this framework is implemented it is not ment to be for microservices.
But keep up the excellent work!

**Comment by rasmus** [comment]
@domenkogler EventFlow is indeed intended for micro services, especially web based APIs (e.g. no background worker threads, everything is done within the same async context) and we use EventFlow at eBay in our micro services

**Comment by domenkogler** [comment]
But is has major flaw! It assumes that service is never put down unexpectedly and has no recovery mechanism for this scenario. For me that is the critical part of microservice.

During `IDomainEventPublisher.PublishAsync` method is just too much exposure for losing consistency.

**Comment by rasmus** [comment]
@domenkogler Good input. Sorry for the late reply. I have opened issue #439, if you have any input and/or ideas, please post them there. I'll close this issue as moving the invocation of the publisher won't do any difference as the code path stays virtually the same.

**Comment by domenkogler** [comment]
In my project i will ensure eventual consistency using MassTransit (RabbitMQ) [Courier](http://masstransit-project.com/MassTransit/advanced/courier/) with RoutingSlips and "At least once delivery" with handling more than once delivery. If you are interested in accepting this external dependency i can prepare PR. PR #432 was just step one for this solution.
