### ISSUE TITLE
Dependency Injection for Command Handlers

### ISSUE THREAD

**Issue by identify1980** [eventflow/EventFlow#441]
Given scenario: in my web application the current user is resolved by my (AutoFac) IoC-Container, so that I can simply put the type "CurrentUser" as a dependency, wherever I need it. Aggregates may only be modified by the user, who owns the aggregate. The owner is stored, when the aggregate is created first. Every later modification may only happen, if the current user equals to the aggregate owner. I created a specification for this and call this specification in my corresponding method at the aggregate.

However - I need to pass the current user to the spec. As far as I can see, there is no dependency injection on specifications. This causes me to pass the current user from the aggregate. As there is no dependency injection as well, I need to pass the current user to the aggregate method which triggers the specification. I call this method from my command handler. Is there a way to have dependency injection on command handlers? Currently I am passing the current user by the command - which is not exactly what I want.

**Comment by rasmus** [comment]
@identify1980 command handlers and aggregates are resolved via the IoC container, Autofac in your case. You should be able to merely put the required services into the command handler/aggregate constructor and get the instances.

Tests that verify IoC on aggregates are in the [`AggregateFactoryTests`](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.Tests/IntegrationTests/Aggregates/AggregateFactoryTests.cs) and command handlers are resolved via the IoC container [here](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/CommandBus.cs#L117)
