### ISSUE TITLE
Use Microsoft.Extensions.DependencyInjection inplace of inbuilt Container

### ISSUE THREAD

**Issue by edwardwilson** [eventflow/EventFlow#449]
I believe it would be good to use the standard IoC developed for the .netcore eco system (but is supported in existing systems). This will allow uses to change their choice of IoC easier in the future as most major offerings support the Extensions.dependencyInjection library.

**Comment by rasmus** [comment]
There's a PR for that #445

**Comment by RTodorov** [comment]
@rasmus since #445 has been merged already, should we close this issue?

**Comment by rasmus** [comment]
Part of the 1.0 release
