### ISSUE TITLE
Recommendations for creating readmodels for multiple aggregates

### ISSUE THREAD

**Issue by ludydoo** [eventflow/EventFlow#451]
What is the recommended way of defining readModels that are a projection of multiple aggregate types?

E.g. ReadModels that are populated by events coming from two different aggregate types.

**Comment by rasmus** [comment]
Have a look at the [`MultipleAggregateReadStoreManagerTests`](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.Tests/IntegrationTests/ReadStores/MultipleAggregateReadStoreManagerTests.cs), they should show how to setup read models for multiple aggregates.

**Comment by rasmus** [comment]
The [documentation](http://docs.geteventflow.net/ReadStores.html) seems to be missing the information.

**Comment by rasmus** [comment]
Created issue in the documentation repo
