### ISSUE TITLE
Add SourceLink

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#459]
Use SourceLink to improve debugging experience with EventFlow.

https://github.com/dotnet/sourcelink

**Comment by rasmus** [comment]
No support for .NET standard 😢

**Comment by ArieJones** [comment]
You may want to relook at this... as from this item it appears that they do support .net standard [https://github.com/dotnet/sourcelink/issues/95](url)
and I believe that standard and core are aligned now.. per http://immo.landwerth.net/netstandard-versions/#

**Comment by rasmus** [comment]
Thanks! I'll have a look

**Comment by leotsarev** [comment]
@rasmus that is probably already have been fixed in #626 ?

**Comment by rasmus** [comment]
Doh, yes
