### ISSUE TITLE
Aggregate independent commands

### ISSUE THREAD

**Issue by ghost** [eventflow/EventFlow#460]
Hi there,

is it possible to send and handle commands that are not related to a aggregate?

As ICommand<Aggregate, …> and ICommandHandler<Aggregate, …> both require aggregate types, it seems impossible.

Sincerely,

Nolde

**Comment by rasmus** [comment]
Commands are currently only for aggregates in EventFlow. If you want to use commands for something else you could take a look at [https://github.com/BrighterCommand/Brighter](Brighter)

**Comment by crazynolde** [comment]
Thanks a lot for your quick reply.

In general i'm happy with aggregate bound commands.

But aside of those, i have to deal with some work that does not refer to aggregates. So I am looking for a solution based on event flow, as this is the framework of my choice and i do not want to have a second command execution framework in my application.

Maybe there's an implementation scenario for such a requirement that brings additional value for your framework.

Sincerely,

Nolde

**Comment by crazynolde** [comment]
That's maybe related to issue 181
https://github.com/eventflow/EventFlow/issues/181

**Comment by rasmus** [comment]
I would make sense to loosen up the restrictions a bit. I do try make sure that EventFlow doesn't impose too many limits on how you would like to implement your domain.

**Comment by wgtmpeters** [comment]
We have a maybe a another use case in combination with sagas.

Right now we sometimes use direct updates on the sagas using the new method you expose on the sagastore. However these are all use cases in which we would rather send a command to the Saga in the same way as we send them to Aggregates.

**Comment by rasmus** [comment]
So basically there would be three different cases the command bus would handle

1. Commands for aggregates (find handler, pass aggregate via the update on aggregate store)
1. Commands for sagas (find handler, pass saga via the update on saga store)
1. Commands for everything else (find handler, execute)

**Comment by rasmus** [comment]
For the important part is that a clear implementation can be found, one that doesn't have to "forced" into the code base.
