### ISSUE TITLE
AggregateSaga.Publish(new MyCommand()) does not actually publish the command.

### ISSUE THREAD

**Issue by HistoricallyCorrect** [eventflow/EventFlow#462]
I've been using AggregateSaga to implement an orchestration between aggregates. The code is as below. I found an issue where using `AggregateSaga.Publish(new MyCommand())`, the command never gets published. [Here's the method](https://github.com/eventflow/EventFlow/blob/e0f60416d3598117aa8c2c2dc706d42604eedbd1/Source/EventFlow/Sagas/AggregateSagas/AggregateSaga.cs#L60). So currently I have to inject ICommandBus to publish command within AggregateSaga. But I wonder if this would cause any issues such as the command can only be published before something is committed. Would be good if a fix could be in place soon. Thanks very much.

```
    public class MySaga
        : AggregateSaga<MySaga, MySagaId, MySagaLocator>,
            ISagaIsStartedBy<MyAggregate, MyId, MyEvent>,
            ISagaHandles<MyOtherAggregate, MyOtherId, MyOtherEvent>
    {
        readonly ICommandBus _commandBus;

        public EnrolmentSaga(MyId id, ICommandBus commandBus) : base(id)
        {
            _commandBus = commandBus;
        }

        public Task HandleAsync(IDomainEvent<MyAggregate, MyId, MyEvent> domainEvent,
            ISagaContext sagaContext, CancellationToken cancellationToken)
        {
            //Publish(new MyCommandOfOtherAggregate()); //does not actually work, only puts the command into AggregateSaga.cs _unpublishedCommands but never actually publishes.
            _commandBus.Publish(new MyCommandOfOtherAggregate()); //currently I'm doing this to make it work.

            return Task.FromResult(0);
        }

        public Task HandleAsync(IDomainEvent<MyAggregate, MyId, MyOtherEvent> domainEvent,
            ISagaContext sagaContext, CancellationToken cancellationToken)
        {
            return Task.FromResult(0);
        }
```

**Comment by HistoricallyCorrect** [comment]
Found another issue related to saga (maybe it's my understanding and or usage), that

1. Saga -(publishes)-> MyCommandOfOtherAggregate to MyOtherAggregate
2. MyOtherAggregate -(emits)-> MyOtherEvent
3. Saga -(handles)-> MyOtherEvent

3 doesn't actually happen at the moment, HandleAsync of MyOtherEvent in Saga never gets invoked.

**Comment by rasmus** [comment]
The problem is in the [`SagaAggregateStore`](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/Sagas/AggregateSagas/SagaAggregateStore.cs#L80). It's a scenario I didn't think of when implementing the saga aggregate store. However, it does seem like a bug as it doesn't do what you expect (or I expected without reading the code).

If you are in the context of a saga, you should be able to handle events without the need to emit an event for every single event that you are handling.

If no one objects, then I'll mark it as a bug and create a fix with the breaking change.

**Comment by HistoricallyCorrect** [comment]
Thanks to both @wgtmpeters and @rasmus.

My understanding of the term Saga in the context of EventFlow (or Domain Driven Design) carries a different meaning than in the context of Message Driven Architecture.

Saga as I understand it is an orchestrator between different messages, so there is a single place to reason about the workflow between messages as well as providing a management of states of long running process and can cater for Eventual Consistency.

Where EventFlow, Aggregate already provides what Saga provides in the context of MDA (orchestration of Domain Events, DE are like messages in MDA). And Saga in DDD is just yet another higher level of MDA Saga, which manages / orchestrates across different Bounded Context (which are Aggregates). I see a lot of cases where EventFlow Saga may not need to emit Domain Event and facilitate communication between Bounded Context by sending command to Aggregate. The events that are emitted from Saga are more useful when Saga itself has events for state tracking purposes.

It is a bit hard to explain but please let me know if my above understandings are correct.

So yes I agree that without emitting events within saga, commands should be published to the aggregates regardless.

**Comment by wgtmpeters** [comment]
I agree that Saga's should only emit Events for saving state.
The default implementation of Saga's in EventFlow is also done by making them EventSources and use the already existing AggregateRoot implementation.
This however does make it a bit easy sometimes do to things that might not be really good Eventsourcing design.
Like using Saga events as domainEvents in your system, while in fact these should be coming from AggregateRoots.

**Comment by rasmus** [comment]
@HistoricallyCorrect As you pointed out, the fact that the current saga store implementation in EventFlow uses event sourcing shouldn't have any effect on the saga design pattern, i.e., if a saga emits no events any commands should still be published.

As @wgtmpeters pointed out, there are some pitfalls making sagas aggregate roots. While it does provide a nice clean and familiar event source functionality and you reap the benefits of event sourcing, events from sagas aren't really domain events (maybe I'll put that in the docs somewhere).

I made sure to make it possible to change the storage system for sagas at a later point as I wasn't sure it really was a good idea. There's even a [test that verifies](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.Tests/IntegrationTests/Sagas/AlternativeSagaStoreTestClasses.cs) an alternative storage mechanism is possible.

I'll mark this as a bug an create a patch.
