### ISSUE TITLE
Support Kafka

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#465]
Until Docker integration testing is ready (#425), maybe setup a free plan using https://www.cloudkarafka.com/plans.html

Use https://github.com/confluentinc/confluent-kafka-dotnet as its the recommended client from Microsoft.

**Comment by RTodorov** [comment]
Hi @rasmus,

Looks like EventFlow is the most mature DDD/CQRS/ES library for C# out there, kudos for that!

I'm looking into adopting it on different projects but I'm gonna be using Kafka as the main event store / service bus. Any idea how hard would be to implement Kafka support on my own? Or is there any active workstream for adding kafka support other than this issue?

Thank you

**Comment by rasmus** [comment]
@RTodorov the persistence layer in EventFlow is defined by the [`IEventPersistence`](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/EventStores/IEventPersistence.cs) which isn't that complex.

You could get some inspiration for how to implement it by looking at some of the existing implementations, e.g. the [`InMemoryEventPersistence`](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/EventStores/InMemory/InMemoryEventPersistence.cs)

If you do select to do the implementation, then the event persistence test suite that EventFlow uses to tests its implementations are shipped in the [`EventFlow.TestHelpers`](https://www.nuget.org/packages/EventFlow.TestHelpers/) NuGet package, specifically the class `TestSuiteForEventStore`. Setting it up is rather simple, have a look at the [`MsSqlEventStoreTests`](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.MsSql.Tests/IntegrationTests/EventStores/MsSqlEventStoreTests.cs) to get an idea on how to get started.

If you get a working implementation along with a suite of integration tests, then we could add it to the repo.

Hope that helps.

**Comment by ahernandez-allegion** [comment]
@rasmus I'm curious, would supporting a basic Kafka extension really be that different than the existing RabbitMQ extension?
