### ISSUE TITLE
How to globally register event store and set use this event store ?

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [eventflow/EventFlow#474]
I want to register global configurations like the Startup.cs file. How can I do it?
Or is it unnecessary and I can just push connection string directly into class ?

**Comment by rasmus** [comment]
Have a look at the [getting started guide](http://docs.geteventflow.net/GettingStarted.html#getting-started).

**Comment by Ilchuk-Mihail** [comment]
I can't find the answer here. 
Should I be looking at configuration with Ioc container? 

Can I do it in a standart .net core Ioc ?

**Comment by rasmus** [comment]
Then I'm not sure what king to global configuration you are talking about.

If its for MSSQL, then its in the MSSQL documentation here http://docs.geteventflow.net/MSSQL.html

If its for general EventFlow settings, its documented here http://docs.geteventflow.net/Configuration.html

**Comment by Ilchuk-Mihail** [comment]
I mean so that not to write this every time:
```
ConfigureMsSql(MsSqlConfiguration.New
    .SetConnectionString(@"Server=.\SQLEXPRESS;Database=MyApp;User Id=sa;Password=???"))
    .UseMssqlEventStore()
```

But to set it once for entire aplication.

**Comment by rasmus** [comment]
No, you'll have to either use the resolver from `CreateResolver()` or use e.g. the Autofac EventFlow binding

**Comment by rasmus** [comment]
Closing, old question
