### ISSUE TITLE
Azure Cosmos DB support

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [eventflow/EventFlow#478]

**Comment by rasmus** [comment]
@Ilchuk-Mihail Nothing yet

**Comment by Ilchuk-Mihail** [comment]
@rasmus I found. 
We can start with using this https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-introduction
Azure Cosmos DB has support of Mongo DB API  :)

**Comment by jasonchester** [comment]
One downside to using CosmosDB via the Mongo API vs. the DocumentDB api is that you lose support for reading from the Cosmos Change Feed.

Perhaps https://github.com/ASOS/SimpleEventStore would be a good starting place for adding cosmosdb support?

**Comment by rasmus** [comment]
Maybe use the [Docker version](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#running-on-docker) for integration testing

**Comment by ahocquet** [comment]
Is there any plan in the near futur to support Cosmos DB ? I'm about to start a new project in the company I work for, so I'm wondering if I should setup an Azure SQL Server or wait a little bit and stick with Cosmos DB. 

Thank you :)

**Comment by rasmus** [comment]
There currently no plans for adding Azure Cosmos DB

/rasmus

**Comment by bartelink** [comment]
As someone who as spent significant time implementing and tuning CosmosDb support for another system with CosmosDb Event Storage ([Equinox](https://github.com/jet/equinox)), I'd strongly advise against considering a 'trivial' event-as-a-document implementation - while it will work, and the change feed is nice, ultimately you won't get a viable mix of semantics, perf and cost effectiveness without a heck of a lot of engineering effort, necessitating surfacing some necessary implications of applying Cost Model Sympathy (and doing so would duplicate the purpose of [CosmoStore](https://github.com/Dzoukr/CosmoStore), [SimpleEventStore](https://github.com/ASOS/SimpleEventStore), [Eveneum](https://github.com/Eveneum/Eveneum), which are already non-trivial efforts)

**Comment by jessemillerrev** [comment]
I was able to implement Eveneum as the interface to CosmosDB pretty easily actually. I am not sure if that is the direction you want to go here in EventFlow but it is definitely an option. The only real issue with using Eveneum is there is a name clash as both use EventStore as a concept.
