### ISSUE TITLE
Specific column "EventName"

### ISSUE THREAD

**Issue by frankebersoll** [eventflow/EventFlow#485]
All SQL implementations use serialized metadata to store the event name. While this is certainly enough to replay events, during development, I often need to look into the database to figure out what happened and it would be so much nicer if I was able to distinguish events by name. 

- Benefits / performance impact / additional size?
- Could we add this "on demand", so people don't have to migrate existing data?

**Comment by rasmus** [comment]
We have the same in the event source system that doesn't use EventFlow (created before EventFlow) and is indeed convenient.

As its merely a "display" field for when viewing, we could just add a default null column.

**Comment by frankebersoll** [comment]
For MSSQL, I have a workaround where I use [JSON_VALUE](https://docs.microsoft.com/de-de/sql/t-sql/functions/json-value-transact-sql?view=sql-server-2017) in a View - no need for duplicated data.

**Comment by ArieJones** [comment]
@frankebersoll this would be the most efficient way and would actually be a handy implementation to have on the existing schema structure with alternate database tech supplying their own view logic...eg MySQL would use JSON_EXTRACT.

**Comment by frankebersoll** [comment]
The script for MSSQL could look like this:

``` SQL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE table_schema = N'dbo' AND table_name = N'EventFlowView')
BEGIN
	EXECUTE('CREATE VIEW [dbo].[EventFlowView]
		AS SELECT
			GlobalSequenceNumber,
			AggregateName,
			AggregateId,
			AggregateSequenceNumber,
			JSON_VALUE(Metadata, ''$.event_name'') as EventName,
			JSON_VALUE(Metadata, ''$.timestamp'') as Timestamp,
			Data
		FROM EventFlow')
END
```

@rasmus Could we make this optional in `EventFlowEventStoresMsSql.MigrateDatabase`?
