### ISSUE TITLE
Question: Read Model Removed

### ISSUE THREAD

**Issue by robbihun** [eventflow/EventFlow#487]
Given a type of event, "MyThingRemovedFromSchedule" and a read model that lists all of the "MyThings" for a Schedule how would one remove a "MyThing" from the read model?

**Comment by rasmus** [comment]
Currently there isn't a built-in way of deleting read models in EventFlow. It doesn't have much though, simply create a [subscriber](http://docs.geteventflow.net/Subscribers.html) that listens on `MyThingRemovedFromSchedule` and then call [`IReadModelPopulator.DeleteAsync(...)`](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/ReadStores/IReadModelPopulator.cs#L46).

**Comment by robbihun** [comment]
Thanks! would you recommend this approach for not using the built-in read model mechanism? Say the project already has an EF model they're using as a read model - would you use basic subscribers with EF injected in to create/update the data?

**Comment by robbihun** [comment]
Yeah, I see how the is deleted would work fine. I think my main hang up is when I think of ES read models, I shouldn't have to do a lot of joining or filtering, the data should be optimized for display. 

We typically have a lot of EF6 with plans to move to core at some point. I'm really just playing with the EventFlow framework to get my head around how it works and looking at how it might fit some needs. The read model seems to break down for me in complex domains with a lot of entities. And breaking out to event subscribers to manage my own read model seems to be missing something (error handling, retried, etc).

Also, not related to this issue, but for discussion on the framework. What about other queuing technologies, right now it seems everything is in memory. What about moving to distributed queues (msmq, sqs, rabbitmq, etc) to communicate commands to the domain and receive events. We typically have our domains run as windows services then have one or more related systems that subscribe to events to display data and send commands to the domain, using queues allows us to scale easily. Just thinking "out loud" here...

**Comment by rasmus** [comment]
Instead of executing subscribers you could use [asynchronous subscribers](http://docs.geteventflow.net/Subscribers.html#asynchronous-subscribers) and have then executed using e.g. Hangfire

**Comment by frankebersoll** [comment]
Please try what I built in #489, it should remove exactly one read model instance (the one that is handling the current event).

**Comment by rasmus** [comment]
Released in 0.60.3490

**Comment by rasmus** [comment]
Closing, old question
