### ISSUE TITLE
Read model locator question

### ISSUE THREAD

**Issue by coding4food** [eventflow/EventFlow#499]
Constructor of `MultipleAggregateReadStoreManager` requires instance of type implementing `IReadModelLocator`. When I register my read model with `EventFlowOptionsReadStoresExtensions.UseReadStoreFor<TReadStore, TReadModel, TReadModelLocator>`/` EventFlowOptionsReadStoresExtensions.UseInMemoryReadStoreFor<TReadModel, TReadModelLocator>` it does not register `TReadModelLocator` type in container. This leads to exception during resolver validation. Is this desired or buggy behaviour?

**Comment by rasmus** [comment]
Hi @coding4food its by design. EventFlow doesn't know how to construct your type or even their lifetime. While both might be trivial is most cases there are sometimes they are not, e.g. a locator could be singleton or transient or created using some lambda method.

**Comment by coding4food** [comment]
I see, that's a valid point. Probably EventFlow could provide some default registrations for missing types or we could later override them with specific lifetimes of factories.

**Comment by rasmus** [comment]
I don't think EventFlow ever will try to register any types not directly part of the framework and personally I wouldn't expect any framework to do it for me either. The IoC in EventFlow is merely a bridge to the IoC in your application for the interface EventFlow types, while its possible to use the service registration provided by EventFlow, I would suggest using the more powerful functionality of e.g. Autofac.

If you have a simple application it can be done as simple as this in Autofac

```csharp
containerBuilder.RegisterAssemblyTypes(assembly).AsImplementedInterfaces();
```

**Comment by coding4food** [comment]
OK, thank you for clarification.

**Comment by rasmus** [comment]
Please, if you have any other questions or have any references to your use case, let me know.
