### ISSUE TITLE
Consider change to LibLog

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#51]
Instead of creating yet another log framework within EventFlow, consider changing to LibLog and then embed the DLL with ILMerge.

https://github.com/damianh/LibLog

**Comment by rasmus** [comment]
Maybe just add a extra logger called `LibLog` that developers can register

**Comment by JC008** [comment]
A good write up on the subject - [Which logging abstraction should I use?](https://nblumhardt.com/2016/04/which-logging-abstraction-should-i-use/)

**Comment by rasmus** [comment]
@JC008 Thanks
