### ISSUE TITLE
Why does Aggregate Id have to be a Guid?

### ISSUE THREAD

**Issue by JackHerring** [eventflow/EventFlow#518]
See line `111` here https://github.com/eventflow/EventFlow/blob/92e05a7e1bace5283fe219bd21a7bfef3805d8e1/Source/EventFlow/Core/Identity.cs

Is there a good reason for this? I have a use case where my `Id`s are coming from an external system and are not `Guid`s. I can have an arbitrary `Id` alongside the external `Id` (as a 'reference' I guess) but it seems like an unnecessary restriction.

**Comment by rasmus** [comment]
@JackHerring There's absolutely no need, its merely the default implementation that fits most. If you need something else, just disregard the `Identity<>` implementation and create your own, it merely needs to implement the `IIdentity` interface.

There's even a test that verifies a custom implementation is possible.

https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.Tests/Exploration/CustomAggregateIdExplorationTest.cs

**Comment by JackHerring** [comment]
@rasmus got it, thank you
