### ISSUE TITLE
Could you please assist how can I implement uniqueness check on an aggregate

### ISSUE THREAD

**Issue by Nitinbabariya** [eventflow/EventFlow#522]
Hi,
I am developing a prototype using Eventflow.
I want to implemented an uniquess check on an aggregate for example a name of person has to be unique.
In my opinion there are many ways to achieve this i,.e domainservice, firing a query to check if there are any person exists with same name  or maintaining a list of person names in a list in a seperate aggregate.

Coud you please suggest how can I implement it in the best possible way using EventFlow.
Is there any chat group to raise any questions I have regarding EventFlow?

Best regards,
Nitin

**Comment by rasmus** [comment]
There's a few methods you could do this, which one depends on your domain, here's a few off the top of my head

- Detect any violation of the uniqueness and then issue a new event that requests a new name. Example would be amazon that allows two persons to buy the last item. Which could result in an e-mail to one saying "sorry, the item is already bought". This is eventually consistent but might be hard in some applications
- Implement a name reservation. Check if the name is taken, if not, then reserve it for a time and then create the user
- Implement a unit of work that encapsulates the event store and the DB name reservation table. This is rather bad for performance and could lead to all sorts of other problems, but might be the only options in some cases

**Comment by a-t-k** [comment]
// Create a namespace, put this in a constant somewhere
var emailNamespace = Guid.Parse("769077C6-F84D-46E3-AD2E-828A576AAAF3");

// Creates an identity with the value "test-9181a444-af25-567e-a866-c263b6f6119a"
var testId = TestId.NewDeterministic(emailNamespace, "test@example.com");

So, you can use unique field as ID. When you create entity with the same "Unique-Field" an exception will be thrown. 

I hope its not wrong aproatch.

**Comment by rasmus** [comment]
@a-t-k your approach is sound as long as you don't wan't to support changing the user email. In that case you would have to map the existing user to a new aggregate as its ID would change.

**Comment by rasmus** [comment]
Closing, old question
