### ISSUE TITLE
ResolverExtensions.ValidateRegistrations throws StackOverflowException

### ISSUE THREAD

**Issue by coding4food** [eventflow/EventFlow#523]
Let's say we have a command handler decorator like this:
```
public class SomeCommandHandlerDecorator<TAggregate, TIdentity, TResult, TCommand> :
        CommandHandler<TAggregate, TIdentity, TResult, TCommand>
        where TAggregate : IAggregateRoot<TIdentity>
        where TIdentity : IIdentity
        where TResult: IExecutionResult
        where TCommand : ICommand<TAggregate, TIdentity, TResult>
    {
        public SomeCommandHandlerDecorator(ICommandHandler<TAggregate, TIdentity, TResult, TCommand> inner)
        {
            ...
        }

        ...
    }
```
in the same assembly as other command handlers.

When we register EventFlow types with `EventFlowOptionsDefaultExtensions.AddDefaults` (which calls `EventFlowOptionsCommandHandlerExtensions.AddCommandHandlers`) this open generic type gets registered as command handler. Any attempts to resolve it cause `StackOverflowException` (registration validation does that). Probably, some additional checks are needed to register only bound generic types as service implementations in built-in container.

**Comment by rasmus** [comment]
Thanks for reporting

**Comment by frankebersoll** [comment]
I'm working on this
