### ISSUE TITLE
Versioned types not loaded when using DependencyInjection package

### ISSUE THREAD

**Issue by wernert72** [eventflow/EventFlow#526]
Maybe i did not understand how to use the DependencyInjection package.
But when i use it like:
var provider = services.AddEventFlow((o) => ....).BuildServiceProvider(); 
And then when publishing a Command using the commandbus i get a exception in the versionedtypes service telling me : No definition for type type (EventType) have you remembered to load it during EventFlow initialization".

I did not went through the source yet to see if it was a flaw in the DependencyInjection package ( when using the simple build in IoC container it works just fine).

So if anyone can enlighten me on this?  ~

**Comment by idubnori** [comment]
I had the same. This might work well.
1. Add [this](https://github.com/eventflow/EventFlow/blob/5d42a8eb8f6ded915dca8a6c6120ee4c8a651acd/Source/EventFlow.AspNetCore/Extensions/EventFlowOptionsExtensions.cs#L42) within `.AddEventFlow((o) => ....)`
2. Copy [`HostedBootstrapper`](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.AspNetCore/ServiceProvider/HostedBootstrapper.cs) into your code-base

**Comment by wernert72** [comment]
In other words i add AddAspNetCoreMetadataProviders().
In anyway, tnx.

**Comment by wernert72** [comment]
@idubnori  agree
