### ISSUE TITLE
Report unstable builds

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#531]
Build seem to fail randomly and while there are some know culprits its hard to get an overview. If you experience unstable builds, i.e., builds that fail randomly and unrelated to your change, then please post a link to the build here.

Reported unstable tests
- `EventFlow.RabbitMQ.Tests.Integration.RabbitMqTests.PublisherPerformance`
  - timeouts after 60 seconds
- `EventFlow.Tests.UnitTests.EventStores.ConcurrentFilesEventPersistanceTests.MultipleInstancesW`
  - Assertion failure "Expected a <System.IO.IOException> to be thrown because of concurrent access to the same files., but no exception was thrown"

**Comment by idubnori** [comment]
https://ci.appveyor.com/project/eventflow/eventflow/build/0.65.3643/tests in #537

**Comment by idubnori** [comment]
https://ci.appveyor.com/project/eventflow/eventflow/build/0.65.3653/tests in #514

**Comment by rasmus** [comment]
Removed old build system
