### ISSUE TITLE
Question: Exception in subscriber

### ISSUE THREAD

**Issue by ArnoHorl** [eventflow/EventFlow#536]
Hi,

I'm trying to understand what to do with an exception in one of the subscribers. Can you shed some light on this?

I have two subscribers for one event and both are inserting/updating different tables in two sql databases through EF. 

What to do if one subscriber throws an exception (for some reason)? So the read and writemodel are out of sync. At least for one table, because the other subscriber executed without exception.

What is the best practices for this?
Register the event on a bus and retry / replay on a later moment for just this subscriber? Or are there other options?

Thanks in advance!

**Comment by rasmus** [comment]
Hi @ArnoHorl. As you have noticed, subscribers are swallowed by default (read [here](http://docs.geteventflow.net/Subscribers.html#exceptions-swallowed-by-default) how to disable it required).

As for how to handle exceptions in read model stores and subscribers, you might find some information in the issue #439. The short version is, it depends on your application and how good it is at handling eventually consistency, Of course the first problem is detecting the read models/subscribers are out of sync.

Some mirror events committed to a separate log and do a catch up, either regularly or on next application start. Others don't use the build in mechanism in EventFlow for read models and subscribers, but have built their own more resilient solution based on some 3rd party framework. All of these are custom solutions and none have yet made it back to the main EventFlow code base.

Sorry, I didn't really answer your question, but let me know if you have a follow up.

**Comment by rasmus** [comment]
Closing, old question
