### ISSUE TITLE
Saga Received event more than once

### ISSUE THREAD

**Issue by MongkonEiadon** [eventflow/EventFlow#539]
I tried to use Saga to process like a customer register, then I've implemnted  "ISagaIsStarted<>" then I've found out that event become 2 times like this

![image](https://user-images.githubusercontent.com/3174809/45913001-075f8c00-be55-11e8-9ba6-8c82e3bf0ddf.png)

**Comment by rasmus** [comment]
@MongkonEiadon sorry for the late reply, but it seems like you have registered the saga twice

![image](https://user-images.githubusercontent.com/18956/47012869-a79f8c80-d145-11e8-8147-f6d0945f6254.png)

**Comment by rasmus** [comment]
Will add a check that ignores a saga if its added twice

**Comment by MongkonEiadon** [comment]
For sure I've reimplemented all saga again an again, now it's work fine but once when I've tried to ```Complete()``` after one final complete event (this event will finish the saga) become by ```ISagaHandler<Agg, AggId, FinalEvent>``` then I've Emit<SagaCompletedEvent> and then I put Complete() after that

Saga was threw the exception about multiple event already had operation,

If this kind of multiple registration the saga, how it's happened because I've just use AddDefault(Assembly)

![image](https://user-images.githubusercontent.com/3174809/47013746-6d001900-d172-11e8-8a5c-753af0284e6b.png)

**Comment by rasmus** [comment]
`AddDefault(Assembly)` add everything from an assembly, if you do service registration as well you'll have registered it double. The error you are getting now, is due to the same operation being applied to the saga (its an aggregate) more than once. It happens here https://github.com/eventflow/EventFlow/blob/92e05a7e1bace5283fe219bd21a7bfef3805d8e1/Source/EventFlow/Aggregates/AggregateStore.cs#L114

**Comment by MongkonEiadon** [comment]
Now I've knew the root causes: that the SagaDifinitionService have more than one like this
![image](https://user-images.githubusercontent.com/3174809/47220194-4a246d80-d3db-11e8-9d58-328ffcfbde61.png)


Because I've use autofac and also use ServiceCollection After I done this, it was fix now
![image](https://user-images.githubusercontent.com/3174809/47220305-9c658e80-d3db-11e8-8294-2aa97ae7f4bf.png)

: )

**Comment by rasmus** [comment]
Perfect, I'll release the check tomorrow, making it a bit easier

**Comment by rasmus** [comment]
Fixed in v0.68
