### ISSUE TITLE
Deleting rows from a read model that uses a read model locator

### ISSUE THREAD

**Issue by ghost** [eventflow/EventFlow#540]
How do you delete rows from a read model that uses read model locator?

**Comment by rasmus** [comment]
There's no built in functionality. As the IDs of the read models are created by your application based on data from event, EventFlow has no knowledge of how to do this mapping "in reverse". You'll have manage deletion of these read models manually.

If you have an alternative solution, then please open a feature request with a implementation suggestion.

**Comment by madmax19** [comment]
For manual deletion, should I write queries inside the apply function of the read model and then delete or is there another solution?

**Comment by dennisfabri** [comment]
I am quite new to eventflow, but therefore I started implementing an example with Entities below an AggegateRoot. Deleting the ReadModel for the entities (which uses an ReadModelLocator) seems to work quite well. The code can be found here:
https://github.com/dennisfabri/Eventflow.Example.Racetimes
Maybe this helps. Otherwise I would be glad to know where I have made mistakes.

**Comment by rasmus** [comment]
Hi @dennisfabri 

I had a very quick look at your example and have a few comments that might be useful if using EventFlow for something else. Besides that, it look OK 👍 

- Remember that execution results merely need to implement `IExecutionResult`, you don't need to use the built-in, you can implement your own and add additional properties (this is a general theme in EventFlow, there's default implementations for everything, but you don't have to use it if it doesn't fit your domain or CQRS+ES+DDD "flavor").
- You could have a look at specifications to simplify and/or give better names for the checks in the aggregate. EventFlow has an implementation that you could use
- There's three different flavors to choose from when deciding how event are to be applied to your aggregate: public methods, lamdas and state objects. Again, which you choose is up to you. Have a look at the test aggregate use in EventFlow tests here https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.TestHelpers/Aggregates/ThingyAggregate.cs#L57
- Personally I sometimes brake the normal "one class per file" and bundle commands and command handlers together in the same file. It makes navigating the code a bit easier and a bit more readable. This is a personal preference, and only done for some projects
- Small note, the built-in `Identity<>` fits most cases, but is rather verbose, you can implement your own
- You should be able to use the `MsSqlReadModelVersionColumn` attribute for the version column on your read model and have EventFlow maintain it

The example looks nice and clean and is something that developers have been asking about. If you are up for it, then create a PR on EventFlow that updates the read-me examples section with a "external examples" and put your repo there

**Comment by dennisfabri** [comment]
Thanks for the feedback. I was already going to add some things and specifications were already on my list. Some other points really helped me. When I have finished some polishing on the project I would be really glad to add my repo to the examples.

**Comment by MongkonEiadon** [comment]
this is my deletion snippet:

```javascript    
public class DeleteCustomerCommand : Command<CustomerAggregate, CustomerId>
    {
        public DeleteCustomerCommand(CustomerId customerId) : base(customerId) { }
    }

class DeleteCustomerCommandHandler : CommandHandler<CustomerAggregate, CustomerId, DeleteCustomerCommand>
    {
        private readonly IReadModelPopulator _readModelPopulator;

        public DeleteCustomerCommandHandler(IReadModelPopulator readModelPopulator)
        {
            _readModelPopulator = readModelPopulator;
        }

        public override Task ExecuteAsync(CustomerAggregate aggregate, DeleteCustomerCommand command, CancellationToken cancellationToken)
        {
            _readModelPopulator.DeleteAsync(command.AggregateId.Value, typeof(CustomerReadModel), cancellationToken);

            aggregate.DeleteCustomer();

            return Task.CompletedTask;
        }
    }
```

: )

**Comment by rasmus** [comment]
Closing, old question
