### ISSUE TITLE
GetAll query

### ISSUE THREAD

**Issue by hmintern** [eventflow/EventFlow#550]
Hello there,

I am just getting started on going through implementing EventFlow and it is working like a charm. But I wondered how do I get all ReadModels via a `GetAll` query? I saw that there are some InMemory implementations of it. But none for entity framework for example. Is that a design decision? If so, how do I show a list of all created entries I got so far?

Thank you very much

**Comment by marcelpiva** [comment]
were you able to save data in read store?

**Comment by hmintern** [comment]
Yes, I did?

**Comment by marcelpiva** [comment]
> Yes, I did?

which database?

**Comment by hmintern** [comment]
Microsoft Sql Database

**Comment by marcelpiva** [comment]
Here, the GetCustomerQueryHandler looks is working.
But when i dispatch CreateCustomer service, PublishAsync (command), then my command request Create method in CustomerCreateCommand, and in CustomerAggregate i call Emit(new CustomerCreatedEvent), so... the Apply method in the CustomerReadModel is think that will fire, but it's not working.

**Comment by hmintern** [comment]
How does that help with my GetAll query?

**Comment by marcelpiva** [comment]
> How does that help with my GetAll query?

so, i created a CustomerReadModel, and, i created GetCustomerQueryHandler injecting readstore.
In my case, inmemory, `IInMemoryReadStore<CustomerReadModel>`

And in my implementation.

`            var customerReadModels = await _readStore.FindAsync(
                rm => true,
                cancellationToken)
                .ConfigureAwait(false);
            return customerReadModels.Select(rm => rm.ToCustomer()).ToList();`

**Comment by hmintern** [comment]
Yes, but as I already said, I don't use `IInMemoryReadStore<T>`. I use entity framework readstore, which is a `IReadModelStore<T>` and does not have a `FindAsync` method.

**Comment by rasmus** [comment]
EventFlow doesn't (yet) provide a GetAll query by default as it would take up a lot of memory in larger systems. I can recommend looking into the event streaming PR, specifically around here https://github.com/eventflow/EventFlow/pull/464/files#diff-38b71528d0aba96cdbf74b70609dab1dR301 for inspiration on how to iterate through large sets of data. When C# 8 is released, and thereby the `IAsyncEnumerable` I'll add additional support for working with large sets of data, of which PR #464 is one addition.

**Comment by MongkonEiadon** [comment]
FindAsync Not Provide for QueryReadModel by another condition without Id; This kind I've extended

1. Extend interface from IReadModelStore<TReadModel> this provide a FindAsync With you can put condition here
```javascript
public interface ISearchableReadModelStore<TReadModel> : IReadModelStore<TReadModel>
        where TReadModel : class, IReadModel, new()
    {
        Task<IReadOnlyCollection<TReadModel>> FindAsync(
            Predicate<TReadModel> predicate,
            CancellationToken cancellationToken);
    }
```

2. I've implemented it on Infrastructure.EntityFramework environment here:
```javascript
public class EfSearchableReadStore<TReadModel, TDbContext> :
        ISearchableReadModelStore<TReadModel>
        where TReadModel : class, IReadModel, new() where TDbContext : DbContext
    {
        private readonly IDbContextProvider<TDbContext> _dbContextProvider;
        private readonly IEntityFrameworkReadModelStore<TReadModel> _readStore;


        public EfSearchableReadStore(
            IEntityFrameworkReadModelStore<TReadModel> readStore,
            IDbContextProvider<TDbContext> dbContextProvider)
        {
            _readStore = readStore;
            _dbContextProvider = dbContextProvider;
        }

        public async Task<IReadOnlyCollection<TReadModel>> FindAsync(Predicate<TReadModel> predicate,
            CancellationToken cancellationToken)
        {
            using (var dbContext = _dbContextProvider.CreateContext())
            {
                var readModelType = typeof(TReadModel);

                var entity = await dbContext.Set<TReadModel>()
                    .Where(x => predicate(x))
                    .ToListAsync(cancellationToken);

                if (!entity.Any()) return Enumerable.Empty<TReadModel>().ToList();

                return entity;
            }
        }

     ... something else
}
```

3. I've register services
```javascript
public static IEventFlowOptions ConfigureSearchableReadModelStore<TReadModel, TDbContext>(
            this IEventFlowOptions options)
            where TReadModel : class, IReadModel, new()
            where TDbContext : DbContext
        {
            return options
                .UseEntityFrameworkReadModel<TReadModel, TDbContext>()
                .RegisterServices(r =>
                {
                    r.RegisterGeneric(typeof(ISearchableReadModelStore<>), typeof(EfSearchableReadStore<,>));
                    r.Register<ISearchableReadModelStore<TReadModel>, EfSearchableReadStore<TReadModel, TDbContext>>();
                });
        }
```

4. When you want to query by QueryHandler, that didn't query by <<Id>> goes here:
```javascript
 public class QueryIqAccountByEmailAddress : IQuery<IqAccount>
    {
        public QueryIqAccountByEmailAddress(string emailAddress)
        {
            EmailAddress = emailAddress;
        }

        public string EmailAddress { get; }
    }

    internal class QueryIqAccountByEmailAddressQueryHandler :
        IQueryHandler<QueryIqAccountByEmailAddress, Account>
    {
        private readonly ISearchableReadModelStore<AccountReadModel> _readStore;

        public QueryIqAccountByEmailAddressQueryHandler(
            ISearchableReadModelStore<AccountReadModel> readStore)
        {
            _readStore = readStore;
        }


        public async Task<Account> ExecuteQueryAsync(QueryIqAccountByEmailAddress query,
            CancellationToken cancellationToken)
        {
            var result = await _readStore.FindAsync(x => x.UserName == new User(query.EmailAddress), cancellationToken);

            return result?.FirstOrDefault()?.ToAccount();
        }
    }
```

may be this could help you : )

**Comment by hmintern** [comment]
> The Question is "How to get all ReadModels" for UI? or data analysis?.
> You mean Read-Stack of CQRS?

Yes for UI..

> FindAsync Not Provide for QueryReadModel by another condition without Id; This kind I've extended
> may be this could help you : )

This is how I did it aswell now.. but I am not sure if that is the good way? Is there a good way?

**Comment by rasmus** [comment]
Closing, old question
