### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by ShanePadellaro** [eventflow/EventFlow#555]
This is our scenario: 

We have a system that needs to keep track of transaction on Accounts. Calculate the Balance of it and also sum up taxes for different regions and months.

At the moment we have a AccountAggregate that calculates the Balance of the account whenever a Credit Or Debit is made. There is also a TaxLedger that keeps track of all of the Taxes in the system. For taxes we are using the same aggregate Id every time so that we can sum up all the taxes in the system.

When we do billing of our customers we need to be able to create thousands of transactions per account in a very short time. At the moment every transaction corresponds to a AccountCredited or AccountDebited event that gets Emited by the AccountAggregate. The Event contains the new balance and get's applied to the Balance property.

In our Benchmark we are trying to Credit one account a thousand times in a for loop. But we keep running in to OptimisticConcurrency exceptions if we do this async. 

Is there a solution to this problem? Is there another way to better model our domain? At the moment it seems very difficult to get high throughput if the same Aggregate is being updated all the time.

**Comment by wgtmpeters** [comment]
The exception you see is as expected. You will see it when a change on the aggregate is performed on the wrong, cq., old version. And is thus reapplied to the current version of the aggregate. The more changes you do in paralel the more you will see the error and that can eventually even fail the apply of the event.

The main point here is to test with real scenario. Will 1 account actually get 1000 modifications in a couple of seconds?if not then change your test to use a realistic amount

**Comment by rasmus** [comment]
Just an elaboration upon the above:

When a aggregate is edited its loaded into memory, events are fired and then the new events are committed to the event store. If any other threads have made changes the exception is thrown as described by @wgtmpeters. Normally this will trigger a reload of the aggregate and the command is retried until the [retry limit](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/Configuration/IEventFlowConfiguration.cs#L46) has been reached. When this happens, the exception is thrown. Event sourcing isn't known for its performance, but combined with CQRS it makes modelling with DDD easier. If you have such a high performance requirement, there a few things you could try.

1) Move the high performance demanding parts to something else
1) Make sure a single thread only executes on each aggregate
1) Queue operations and then do 2)

Remember, that beside any storing of events, EventFlow still needs to [update read models, trigger any subscribers and sagas](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/Subscribers/DomainEventPublisher.cs#L78) which is still a lot of stuff to do.

**Comment by rasmus** [comment]
Closing, old question
