### ISSUE TITLE
MSSQL Snapshot dont serialize array of entities inside of an agreggateState

### ISSUE THREAD

**Issue by a-t-k** [eventflow/EventFlow#557]
Hi, sorry for my english

I have agtegateState and inside of it an array of entitites. 
After creation of agreggate and add some entities to it (Events are stored, readModels created).
All works fine.

But, when snapshot creation is triggered and serialisation persist data:

In the database in table "EventFlowSnapshots" field "Data" i se only all properies from the agreggate-state and entities array is empty.
Looks like ("propertyName": [])

What i do wrong?

What can i do? Repopulate all entities?
I need do some changes to "CreateSnapshotAsync" and "LoadSnapshotAsync" and ISnapshot-Implementation Class?

PS: It the documentation i cant find information about entities. Only about ValueObject and Agreggate.

**Comment by rasmus** [comment]
Closing, old question
