### ISSUE TITLE
How to test snapshots

### ISSUE THREAD

**Issue by dennisfabri** [eventflow/EventFlow#558]
In my example projekt I use a _SnapshotAggregateRoot_ with the functions _CreateSnapshotAsync_ and _LoadSnapshotAsync_ (See [CompetitionAggregate](https://github.com/dennisfabri/Eventflow.Example.Racetimes/blob/master/src/Racetimes.Domain/Aggregate/CompetitionAggregate.cs)). I have been able to add tests for the eventhandling but I have not found a way to test the snapshot.

Is there an easy way to test the snapshot methods?

**Comment by rasmus** [comment]
The load methods of snapshots are triggered on every aggregate load when a snapshot is present and the save every time the strategy says a new snapshot is needed.

As everything on the aggregate is interfaces (as well as everything else in EventFlow) you can create a unit test that tests the load and save methods directly. If you want to create an integration test gives a good warm feeling (and I personally like those), create an aggregate with some events and a snapshot. Maybe create a snapshot strategy that forces a snapshot every 10 events and then create 11 events. Then forcefully delete the first 10 events from the event store and verify that that aggregate loads correctly.

**Comment by dennisfabri** [comment]
That's a good point. The interface is not needed there and I just removed it from the code. 

Thank you.

**Comment by dennisfabri** [comment]
I just implemented a simple test for my snapshots and I guess it should be ok this way.
