### ISSUE TITLE
Questions on sagas using commands

### ISSUE THREAD

**Issue by bedej** [eventflow/EventFlow#561]
What is the expected usage flow with sagas when publishing commands?

My scenario is such that I have a saga which will issue various commands to other domain aggregates. In response to a single domain event (say E), the saga may issue an event, and also issue commands to N multiple other aggregates. So far so good.

My concern is what happens when one (but not all) of the N commands fails. Because of the way that events and commands are published separately in EventFlow sagas (events are committed first, and then commands are run afterwards), the event representing this action in the saga flow was still published. The only remediation available in this case appears to be to try to handle the situation in a registered ISagaErrorHandler - it looks to be difficult due to the fact that you're now outside the saga context itself, and the event describing the action has already committed - meaning you have to write another event saying that the event just committed is inaccurate.

Given this, it seems desirable from my point of view to be able to publish commands and get responses right there inline with the saga handler for event E, then be able to emit events that represent what actually happened. @HistoricallyCorrect mentions in passing in #462 that they've injected the CommandBus into the aggregate to be able to dispatch commands directly. Assuming this is possible, is this a good idea for my scenario above? I'm thinking I could publish the commands in my handler for event E, then know based on whether they succeeded or failed, which event/events to emit from the saga to correctly capture the current resolved saga state. Does anyone see any pitfalls with this approach?

Since sagas are meant to manage potentially long running processes between aggregates, and to be able to deal with failure cases in a graceful way, it seems to me that the existing design in EventFlow doesn't support this scenario well. I guess I don't really understand why the Publish method in AggregateSaga queues up the commands to be published after event committal. Is this to avoid potential reentrancy issues into the same saga? Some other use case I'm not seeing?

I know that sagas haven't received as much love as other areas of EF (@rasmus has said as much in other issues), but that being the case, I'm just trying to figure out reasonable possible approaches to take.

I've looked through the saga issues (both open and closed), and while some are related (#424, #460), I don't think there's any direct treatment of this question. I've also read through the docs and sample and haven't found the answer either - the docs site mentions that commands are published after the saga event handler, but it doesn't explain _why_.

**Comment by bedej** [comment]
Thanks @rasmus for the detailed explanation about why the current implementation is the way it is! This is what I was looking for.
 
One of the reasons I chose EventFlow is that everything is how easy to change with custom implementations, as you describe - this is a huge benefit that I've already taken advantage of. Now that I understand the design intent for sagas/commands here, I'll ponder what makes sense for my use case and come back to this thread once I've solved it, so hopefully others in future can benefit from the discussion.

Thanks for all your hard work, both on the code and on answering questions here 👍

**Comment by bedej** [comment]
To close the loop here, for my use case I ended up injecting the ICommandBus into my saga via a constructor, and created a helper class to submit commands and log failures. I have a general pattern of idempotent commands that I'm adhering to as much as possible, so duplicated commands are not generally a problem.

This works for me for the case I care about now, but wouldn't be robust to all use cases. In future I may yet implement my own saga store that's not an aggregate, to better align with other future use cases.

@rasmus feel free to close or leave open, depending what your policy is for question/discussion issues. Thanks!

**Comment by rasmus** [comment]
Closing, old question
