### ISSUE TITLE
This version is not for produce yet?

### ISSUE THREAD

**Issue by marjezhang** [eventflow/EventFlow#565]
This version is not for produce yet? 
i watch the version is v0.6

**Comment by rasmus** [comment]
We have been using it in production for the last three years. The 0.x version is merely to signify that the api isn't stable yet according to semantic versioning. The api surface is rather stable, especially the core api.

I hope to be able to release 1.0 next year, but that would just be locking the api's.

**Comment by marjezhang** [comment]
> We have been using it in production for the last three years. The 0.x version is merely to signify that the api isn't stable yet according to semantic versioning. The api surface is rather stable, especially the core api.
> 
> I hope to be able to release 1.0 next year, but that would just be locking the api's.

By the way， May I have your uml of this project's sagas section . Beacause I wanner use this eventflow, special sagas section.  I don't understand how use sagas.  
And I need to put this version  to my boss for technological verification . I need to get some flow chat for eventflow. 
I like the eventflow's code style and some technological point like event store , sagas, cqrs.
But It's troublesome to draw this uml by myself.  
Could you give some simple uml chat about sagas\ evevt store to me .

**Comment by rasmus** [comment]
@marjezhang Sorry, no such diagram currently exists.

**Comment by rasmus** [comment]
Closing, old question
