### ISSUE TITLE
[Question] Event filtering and Readmodels

### ISSUE THREAD

**Issue by montella1507** [eventflow/EventFlow#567]
Hello, what is your recommended best practice to create ReadModel for concrete user, based on event metadata - like "create user", "change user", etc. in effective way?

I woud like to have for example - DashboardReadModel (with information connected to concrete user, like last 10 edited items) =  consisting of: 
```
{
 user: GUID,
 last10ItemEdited: [],  
}
```

i will have  "ItemEdited" event with metadata about "user"... 
Now i want to query "DashboardReadModel" for "current user" with GUID as user id.

What i have: 
CurrentUser.Id

What i need (readmodel):
```
{
 user: CurrentUserId,
 last10ItemEdited: array of last 10 items edited by User with ID = CurrentUserId
}
```

Is there a better way to create this ReadModel than iterate over ALL (may be billions of) ItemEdited events in event store and compute with them or skip them in my ReadModel like this:
`if (event.Metadata.User == .... ) { ...  reduce read model }`   ??

I think it would be nice to have a chance how to filter Events in ReadModel creation with some predicate - i think it is supported in EventStore and it may be way more effective than iterate all events in code (in memory).

I am asking if there is any way to filter events with predicate, not only by type. 

Thank you very much, your work is much appreciated!

**Comment by dennisfabri** [comment]
You can write a query for the readmodel that only returns the last editited items, which means filtering within the sql-server. There is no need to iterate through all read model entries.

**Comment by montella1507** [comment]
I do not tak about interation over all readmodels, but over all Events od concrete type. I just want to be able to filter events not ONLY by type but by predicate as well

**Comment by montella1507** [comment]
One solution May be to use retetences to items in user aggregate?

**Comment by dennisfabri** [comment]
Ok, but I am quite sure that you should not access the events in this situation. If you need a special representation, you should update the readmodel when events are fired. Accessing the readmodel should only rely on a simple query to a datasource.

My basic understanding is the following:
1. Updating the AggregateRoot **may** be **complicated** (e.g. applying business logic) and **slow** (e.g. applying a lot of events and updating readmodels).
2. Reading should **always** be **simple** and **fast**.

**Comment by montella1507** [comment]
@dennisfabri 

Hmm... so i would use  UserId from metadata of an event as a key in ReadModelLocator.  
`public class DashboardReadModelLocator : IReadModelLocator
{
  public IEnumerable<string> GetReadModelIds(IDomainEvent domainEvent)
  {
    var ItemCreated = domainEvent as
      IDomainEvent<ItemAggregade, ItemIdentity, ItemCreated>;
    if (ItemCreated == null)
    {
      yield break;
    }
    
    yield return ItemCreated.Metadata.UserId;
  }
}`


Then i will create common ReadModel that includes  events like ItemCreated, ItemEdited...

`public class DashboardReadModel : IReadModel,
  IAmReadModelFor<ItemAggregate, ItemIdentity, ItemCreated>
{
  public List<ItemDTO> Last10Items{ get; set; }

  public void Apply(
    IReadModelContext context,
    IDomainEvent<ItemAggregate, ItemIdentity, ItemCreated> domainEvent)
  {
   ... logic - add to Last10Items...sort..take 10...
  }
}

...
`

When i want to read that read model i will use User identity as key to find readmodel, right..? 

queryProccessor(new GetByModelIdQuery(ID_OF_CURRENT_USER)

Am i right, or on the correct way?

**Comment by rasmus** [comment]
@montella1507 You could have a look at how the `ThingyMessage` is handled in the integration tests. That's a read model that has a one-to-many relationship to the aggregate. Create a row for each item (append only), create a query that returns the last ten items and then create a scheduled cleanup that deletes all but the latest ten read models.

In short, create small immutable read models instead of updating existing ones.

**Comment by wgtmpeters** [comment]
What @rasmus  means is also the only way that is supported right now, most if not all of the current readstore implementation do not support persisting lists of array properties for a readmodel. So 1-many relation should always result in multiple read models.

**Comment by montella1507** [comment]
@rasmus  well yeah.. i have seen that.. if you mean ReadModelAB + ReadModelLocatorAB.. 

if i got you right..  example domain :
**Aggregates**
ParentAggregate
ChildAggregate 
where it is 1:M

**Events**
ParentAggregateCreated
ChildAggregateCreated
ChildAggregateDeleted

** ReadModel**
{ 
Id: // parent ID
Name: // parentName
Children: [] // list of children
}


**Locators**
```
ParentChildModelLocator : IReadModelLocator {
          public IEnumerable<string> GetReadModelIds(IDomainEvent domainEvent)
        {
               var ev= domainEvent as IDomainEvent<ParentAggregate, ParentId, ParentAggregateCreatedEvent>;
                if (ev== null)
                {
                    yield break;
                }

                yield return ev.AggregateEvent.Id; // return ID of the Parent.
        }
}
```

** ReadModel** 

```
 private class ParentChildrenReadModel: IReadModel,
            IAmReadModelFor<ParentAggregate, ParentId, ParentAggregateCreatedEvent>,
            IAmReadModelFor<ChildAggregate, ChildId, ChildAggregateCreatedEvent>,
            IAmReadModelFor<ChildAggregate, ChildId, ChildAggregateDeletedEvent>,
        {
             /// other properties
            List<ChildVM> Children  = new List<ChildVM>();
            
            public void Apply(IReadModelContext context, IDomainEvent<ParentAggregate, ParentId, ParentAggregateCreatedEvent> domainEvent)
            {
               this.Name = ....; 
               this.Id = ....;
            }

            public void Apply(IReadModelContext context, IDomainEvent<ChildAggregate, ChildId, ChildAggregateCreatedEvent> domainEvent)
            {
                _if (domainEvent.AggregateEvent.ParentId == this.Id) {   <<< DO I NEED TO CHECK? 
                        Children.Add(domainEvent.AggregateEvent.ToVM());
                  }
            }
        }

```

My question actually is "Do i need to check ParentID in Apply method for ChildCreatedEvent?".  
Is Apply method called for every readmodel? 

10x ParentAggregate created event
1x  ChildAggregate created event
=>  Apply for ChildAggregateCreatedEvent called 10 times? (on every Parent Read Model?)

**Comment by montella1507** [comment]
Well.. i think i just got IT Wrong... I should have created (designed) Aggregate ,,DASHBOARD" listening for these 3 events, then query Simple DASHBOARD readmodel...

**Comment by rasmus** [comment]
Seems to be answered, open again if not
