### ISSUE TITLE
Saga do double execution and cannot complete.

### ISSUE THREAD

**Issue by PhatHoang21** [eventflow/EventFlow#569]
I'm using version 0.67.3697. I made a saga to handle creating device process. The code is simple as below:
`public class CreateDeviceSaga : AggregateSaga<CreateDeviceSaga, CreateDeviceSagaId, CreateDeviceLocator>,
    ISagaIsStartedBy<DeviceAggregate, DeviceAggregateId, DeviceAddedEvent>,
    ISagaHandles<UserAggregate, UserAggregateId, DeviceListUpdatedEvent>
{
    public CreateDeviceSaga(CreateDeviceSagaId id) : base(id)
    {
    }

    public Task HandleAsync(IDomainEvent<DeviceAggregate, DeviceAggregateId, DeviceAddedEvent> domainEvent, 
        ISagaContext sagaContext, CancellationToken cancellationToken)
    {
        Publish(new UpdateDeviceListCommand(UserAggregateId.New, "123"));
        return Task.CompletedTask;
    }

    public Task HandleAsync(IDomainEvent<UserAggregate, UserAggregateId, DeviceListUpdatedEvent> domainEvent, 
        ISagaContext sagaContext, CancellationToken cancellationToken)
    {
        Complete();
        return Task.CompletedTask;
    }
}`

When I took a debugger, I was facing 2 problems.
1. The start event handler(DeviceAddedEvent) was executed double times.
2. Event though I emitted DeviceListUpdatedEvent from UserAggregate, but HandleAsync for that event was not reached, so the Saga cannot execut Complete() function and finish it.

**Comment by rasmus** [comment]
@PhatHoang21 update to latest `0.68.3728`, it has a fix that protects against registering sagas more than once.

**Comment by PhatHoang21** [comment]
Thanks @rasmus. I already fixed my first issue by updating the latest version. The second one hasn't resolved. Do you have any idea?

**Comment by rasmus** [comment]
@PhatHoang21 Could you try to create an isolated test case? If would be perfect if you had a repo or could reproduce it using the EventFlow test suite. It's really hard to fix a bug that I can't reproduce.

**Comment by rasmus** [comment]
No response for almost a year
