### ISSUE TITLE
EventFlow and GDPR encrypted data demo

### ISSUE THREAD

**Issue by EriksonBahr** [eventflow/EventFlow#572]
I'm wondering if people are planning to add to the EventFlow framework capabilities to deal with GDPR requirements.

The worst requirement would be the ‘right to be forgotten’. How would that fit in an architecture paradigm that its base is a set of events to build up the 'current' state (which means I'm not supposed to hard delete events).

Any ideas if CQRS and Event Flow are suitable in an application that needs to be in compliance to GDPR requirements?

**Comment by rasmus** [comment]
@EriksonBahr In our case all events create are on item directly related to the user, i.e., when a user asks to be forgotten, we simply delete all aggregates they created. There's a lot of different aspect and some argue that timing of events and activity on sites are enough to identify a person, it may even be defined by law (not sure here if it is or just our strict interpretation). As you aren't allowed to keep  anything, your only option is simply to delete everything.

Our department spent quite a lot of time digging though our event sourcing applications as well as old legacy code to make sure we delete everything when we get a GDPR DDR.

**Comment by i-dentify** [comment]
As I am currently evaluating a similar question, I just want to drop another idea here which is based on a statement of a speaker on a developer conference I've attended lately.
Basically the "right to be forgotten" does not necessarily need to mean, that data has to be deleted. It may also mean, that data is not readable/resolvable anymore. This now may lead to another - more simple - approach, which (as mentioned speaker noted) fits perfectly into the way how data is stored within an event store. Basically an event (e.g. as in EventFlow by ```ICommittedDomainEvent```) simply consists of a (somewhat) "meaningless" aggregate id, data and metadata. Assignable/Resolvable data may be kept in ```Data``` and ```Metadata``` as a serialized JSON string. For (de-)serialization there is ```IEventJsonSerializer``` with its default registration ```EventJsonSerializer```. You now may also register your own serializer, which extends the (de-)serialization by encrypting/decrypting ```Data``` and ```Metadata``` with a key kept externally within a key vault (be it Azure Key Vault, Google Cloud KMS, ...). "Forgetting" data then can also mean to just "throw away" the encryption key and thereby make the data unreadable.

**Comment by rasmus** [comment]
I think it would be a great idea to demo this in a test

**Comment by rasmus** [comment]
Don't think I want to provide recommendations on handling GDPR data, think that would open a can of worms I'm not able to handle.
