### ISSUE TITLE
ElasticSearch auto-update mapping

### ISSUE THREAD

**Issue by marcelpiva** [eventflow/EventFlow#573]
Hi @rasmus  and collaborators, we have two problems here. Could give us a solution?

1. My mapping of ElasticSearch is creating automatically using my class of ReadModel.
But when i change by ReadModel, i need to update my mapping manually.

2. When ElasticSearch creates my ProductId, it creates as text, and creates fields as keyword, so, when i make a search using term or match, doesn't found, because the comparsion are text vs keyword.

There are an existent in EventFlow solution for it?

Thanks guys.
Marcel

**Comment by rasmus** [comment]
Hi @marcelpiva 

1) In our department we have made a custom "refeed" functionality that repopulates a new index with the updated field will all data we have while users are editing their aggregates. Its rather complex and spans several deplorable units. I would recommend you to do something similar, or create a new read model.

2) That's a pure Elasticsearch/NEST "problem". I can highly recommend their attribute documentation here https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/attribute-mapping.html

**Comment by rasmus** [comment]
Closing this as there hasn't been an response for almost a year
