### ISSUE TITLE
Async ReadModels (IAmReadModelFor)

### ISSUE THREAD

**Issue by JackHerring** [eventflow/EventFlow#577]
Is there any support for `async` ReadModels? The `IAmReadModelFor<TAggregate, in TIdentity, in TEvent>` interface has only a `void` returning method -> I am loathe to implement as `async void` (not least because fire-and-forget with DB access will inevitably cause problems, but also error-handling and order of execution). I need to do some `async` work before applying my ReadModel changes, though.

Is there a way to do this or is this a case of roll-your-own?

**Comment by JackHerring** [comment]
It looks like `async void` isn't even an option here as the caller of `Apply` will expect the Model to be in a Db-writable state immediately after the call returns which will be at the point of the first `await`. Only way to do this at the moment appears to be blocking on the Task completing with `Wait()`/`GetAwaiter().GetResult()`

**Comment by rasmus** [comment]
@JackHerring the original idea as not to have any complex operations in the read model updates. However, as you have pointed out, this is not always the case and indeed `async void` is a no go as the read model update will continue without the async operation being awaited.

I'll add it as a feature request as see if its possible to do anything about it. It might be that an additional interface as I would really dislike having to introduce such a breaking change to the API.

**Comment by JackHerring** [comment]
@frankebersoll thank you for adding this feature, very much appreciated.

**Comment by rasmus** [comment]
Closing this as its implemented in #585
