### ISSUE TITLE
Event Registration with ServiceCollection

### ISSUE THREAD

**Issue by wenkepaul** [eventflow/EventFlow#580]
I receive the following message when trying to emit an event. `ArgumentException: No definition for type 'MyEvent', have you remembered to load it during EventFlow initialization`.  While stepping through the Startup process, I can see `MyEvent` being loaded.  

`
services.AddEventFlow(ef => {
    ef.UseServiceCollection(services);
    ef.AddCommands(new[] {typeof(MyCommand)});
    ef.AddCommandHandlers(new[] {typeof(MyCommandHandler)});
    ef.AddEvents(new[] {typeof(MyEvent)});
});
`

What's the proper method for registering event? [Here's](https://github.com/wenkepaul/eventflow-myapp) a sample repo which reproduces the error.

**Comment by MongkonEiadon** [comment]
May be you can use AddDefaults instead no need to install all componenets

**Comment by rasmus** [comment]
Hi @wenkepaul did you get it working?

**Comment by wenkepaul** [comment]
@rasmus , nope.  I change the `ConfigureServices` to the following, but still received the same error.
```
services.AddEventFlow(ef =>
{
    ef.AddDefaults(typeof(Startup).Assembly);
});
```

**Comment by MongkonEiadon** [comment]
Hey I've check it out you need to install

``` javascript
EventFlow.AspNetCore
```
and following this configuration should be like this;
``` javascript

services.AddEventFlow(cfg =>
                cfg.AddDefaults(typeof(Startup).Assembly)
                     .AddAspNetCoreMetadataProviders());
``` 

and it's will worked : )

**Comment by wenkepaul** [comment]
@MongkonEiadon , your recommendations fixed my problem.  Thank you.

**Comment by PiekJ** [comment]
Even though this issue is closed, I came here with the same error. However I wasn't pleased with the provided answer, because I don't need support for ASP.NET. 

After searching around I came across the [HostedBootstrapper](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.AspNetCore/ServiceProvider/HostedBootstrapper.cs). It seems like you need to call `IBootstrapper.StartAsync(...)` in order to get it working.

Below the minimum configuration for using `EventFlow.DependencyInjection`:
```
public static async Task Main(string[] args)
{
    var serviceCollection = new ServiceCollection();

    serviceCollection.AddEventFlow(eventFlowOptions => 
        eventFlowOptions
            .AddDefaults(typeof(Program).Assembly));

    await using var serviceProvider = serviceCollection.BuildServiceProvider();

    var bootstrapper = serviceProvider.GetRequiredService<IBootstrapper>();

    await bootstrapper.StartAsync(CancellationToken.None);

    var commandBus = serviceProvider.GetRequiredService<ICommandBus>();

    var userId = UserId.New;

    await commandBus.PublishAsync(new ChangeNameUserCommand(userId, "Joopie"), CancellationToken.None)
        .ConfigureAwait(false);
}
```

**Comment by ppilev** [comment]
I had the same issue and didn't like the accepted answer so in my solution I'm using custom service provider factory:

    public class EventFlowProviderFactory : IServiceProviderFactory<IEventFlowOptions>
    {
        public IEventFlowOptions CreateBuilder(IServiceCollection services)
        {
            return EventFlowOptions.New.UseServiceCollection(services);
        }

        public IServiceProvider CreateServiceProvider(IEventFlowOptions containerBuilder)
        {
            return containerBuilder.CreateServiceProvider();
        }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            new HostBuilder()
            .UseServiceProviderFactory(new EventFlowProviderFactory())
            .ConfigureContainer<IEventFlowOptions>(options => 
            {
                options
                .RegisterModule<DomainModule>()
                .PublishToRabbitMq(RabbitMqConfiguration.With(new Uri("amqp://guest:guest@localhost:5672/")));
            })
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            });
    }
