### ISSUE TITLE
Load in memory ReadModel from MsSql

### ISSUE THREAD

**Issue by adrienpeiffer** [eventflow/EventFlow#581]
Hi,

I tried to use an InMemory ReadModel for performance and query purpose.
In my understanding, InMemoryModel should be created/loaded/reloaded from events (stored in MsSql eventflow table).
But It doesn't work. I had no more record after application restart. Is my understanding bad?

**Comment by rasmus** [comment]
Hi @adrienpeiffer 

In-memory read models are, in-memory, that's their persistence model and thus if you do a reboot they disappear (or use multiple instances). If you need to have your read models persisted, you need one of the other read model types, e.g. MSSQL as you suggested.

**Comment by frankebersoll** [comment]
@adrienpeiffer You can use the `IReadModelPopulator` to repopulate your read models at application startup. Just create a new class and implement `IBootstrap`, register your class as `IBootstrap` in the DI container, inject an `IReadModelPopulator` and use it to recreate your read models.

Please note that this has impact on the startup time of your application and probably shouldn't be used in production.

**Comment by adrienpeiffer** [comment]
Ok. Thanks for clarification guys 😄
