### ISSUE TITLE
Does EventFlow have to build all aggregate roots via events?

### ISSUE THREAD

**Issue by colinccook** [eventflow/EventFlow#582]
In a project at work, we use CQRS and "event sourcing" is an unexplored avenue. In my reading of the subject, I've come to realise the ability of building up state from a series of events has many practical applications in our domain.

I found EventFlow a little under two weeks ago. I've been playing with it and love how aggregate roots, commands, events etc hang together.

There's still something I'm unsure of, which may or may not be a gap in my DDD/CQRS knowledge.

Take a simple DDD design of two aggregate roots, a PurchaseOrder and a Supplier. Every PurchaseOrder has a supplier.

A PurchaseOrder goes through various states. It's created, invoice(s) are applied, the purchase order lines are reconciled, paid, etc. This seems like a candidate for event sourcing.

Suppliers, however, are far simpiler. I'd have a single command to create a supplier. This would contain the supplier name, telephone number, etc. Perhaps a second command to archive a supplier to no longer order from it. 

In any case, it doesn't seem like I'd want to use event sourcing to build the Supplier aggregate root, and would rather use a repository (nosql object store etc).

If I created a PuchaseOrderAggregate and SupplierAggregate using EventFlow's AggregateRoot<> class, do they both have to be read from events? Or is it possible to have an AggregateRoot<> but persisted as a whole object somewhere?

Hope this makes sense...

**Comment by rasmus** [comment]
Hi @colinccook 

If you model your purchase orders and suppliers as two different bounded context, then you should leak any internal details on how they are implemented, i.e., one could use event sourcing and the other simple CRUD operations.

One solution doesn't fit everything, but I have found that integrating different contexts using events becomes easier if they both a using event sourcing. If you use traditional CRUD, you still need some method for integrating the two context, for CRUD (depending on your internal infrastructure and developer discipline) you might end up with a architecture that's hard to comprehend, not the core CRUD operations, but how the integrations are managed.

Hope it makes sense.

**Comment by colinccook** [comment]
Hi @rasmus,

Thanks for your timely reply.

I think I overlooked the complexity of combining different methodologies, especially within the same bounded context.

Also a very interesting concept that different bounded contexts shouldn't leak their implentations. However communicating via the same eventing mechanism would have the advantage of a simpler architecture.

I believe my questions has been answered to continue my dummy project. You may see my name in the future :)

Kind regards,

Colin
