### ISSUE TITLE
EventFlow.Owin: Issue with hangfire + metadata providers

### ISSUE THREAD

**Issue by tabro** [eventflow/EventFlow#586]
Ran into this issue while trying to add the metadata providers from the EventFlow.Owin packages:

Issue:
The various MetadataProviders take in IOwinContext as a dependency. This is all fine and dandy for events that occur based on a web request.

However when we do defered events, scheduled by HangFire, resolution of IOwinContext fails, since there is no owin context when hangfire fires exectues the scheduled job.

Possible solution:

Somehow check if there is a context available at the point of time (through servicelocation maybe) - if no context - dont try to resolve it.

**Comment by tabro** [comment]
I solved this locally for my self implemented MetadataProvider by injceting IEnumerable<IOwinContext> and then yield breaking out of the provider when there is no OwinContext.

**Comment by rasmus** [comment]
Personally I would move the Hangfire job to either another service or create a separate IoC container along with a separate EventFlow configuration and leave out the Owin context meta data proversider

**Comment by rasmus** [comment]
Closing this as solved
