### ISSUE TITLE
Using EventFlow in distributed application - how to update data models

### ISSUE THREAD

**Issue by johnny-chan** [eventflow/EventFlow#590]
Hi, 

I have a long-term goal of building an application using EventFlow using Serverless approach (using AWS Lambda)

What i am struggling to work out at the moment is the API to trigger an update on the uncommitted events. I will have separate domain services hosted within each Lambda, which in turn will persist events 
to the event stream. 

What i am looking for is a mechanism which will update all data read models whether they are registered in it owns domain service or in a different service. Data models should only update when an event has been appended to the event stream so it needs to be triggered by a notification. 

I've seen an API to replay all data models, but not one that performs an update. Any help would be really appreciative, as i plan to create a example template to be shared before i build my personal project. Ive already shared a web api with .net core 2.2 example.

Many thanks,

Johnny

**Comment by rasmus** [comment]
There is an API, simply invoke the [`IDomainEventPublisher.PublishAsync`](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/Subscribers/IDomainEventPublisher.cs) with any events and any subscribers and/or read models within your context wil be updated.

**Comment by rasmus** [comment]
If you need to send and receive events in a JSON format, have a look at the `IEventJsonSerializer` which has all this functionality. If you this, remember to register events.

**Comment by johnny-chan** [comment]
ok thank you, i will try this out. I will keep this open for now in case i have further questions. Many thanks @rasmus

**Comment by johnny-chan** [comment]
So if i understand this correctly, you couldn't add an event in one domain service, and then in a different service (say Service B), register for that same event and update Service B data models accordingly. 

Only data models that are registered within each service can be be updated.

**Comment by rasmus** [comment]
Closing this, no follow up for almost a year
