### ISSUE TITLE
using eventflow in multi tenant environment

### ISSUE THREAD

**Issue by kwemou** [eventflow/EventFlow#592]
Dear all,
I am experimenting with EventFlow.
What i found out is that all the events are stored in a single table.
I wants to know if is it possible to store Events of every tenant in a separate table.
If not, would this enhancement requires an API changes?
regards
Kwemou 
 #457

**Comment by rasmus** [comment]
Personally I would split it into multiple micro services or containers to make sure to have hard boundaries between tenants. If that isn't possible, using different IoC containers is will an option and recommended as you still have the issue of subscribers, read models etc. thus if the event store _was_ split, the tenants would still leak via the IoC container.

**Comment by kwemou** [comment]
Hi @rasmus ,
thank you for the quick answer.
Managing IoC containers per user is also difficult in a distributed environment.
The simplest way to go here is multi tenancy using a single table and logical separation of data.
Thank you for the important informations.
Best regards
Kwemou
