### ISSUE TITLE
Creating ReadModel with collection property

### ISSUE THREAD

**Issue by cjstremick** [eventflow/EventFlow#595]
I have a ReadModel implementation that has two properties.  One is a string and the other is an ICollection of strings.  It looks like this:

        public class MyReadModel : IReadModel,
            IAmReadModelFor<MyAggregate, MyId, MyCreatedEvent>,
            IAmReadModelFor<MyAggregate, MyId, MyItemAddedEvent>
        {
            [MsSqlReadModelIdentityColumn] public string Id { get; private set; }
            [MsSqlReadModelVersionColumn] public int Version { get; set; }
            public string MyName { get; private set; }
            public readonly ICollection<string> MyItems = new List<string>();

            public void Apply(IReadModelContext context, IDomainEvent<MyAggregate, MyId, MyItemAddedEvent> domainEvent)
            {
                Id = domainEvent.GetIdentity().Value;
                MyItems .Add(domainEvent.AggregateEvent.MyItem);
            }

            public void Apply(IReadModelContext context, IDomainEvent<MyAggregate, MyId, MyCreatedEvent> domainEvent)
            {
                Id = domainEvent.GetIdentity().Value;
                MyName = domainEvent.AggregateEvent.MyName;
            }
        }

So I have an aggregate that I can create and add items to.  I want the ReadModel to relect just that.  The MyName of it and the list of things that have been added to it.

I can see that when I add something to the aggregate, it calls the events on the ReadModel and the state of it looks good.  Then when it's persisted into my ReadModel table, the MyItems property is always null.

In my case, I would love to have the MyItems collection persisted right on the ReadModel.  How it's stored doesn't really matter, but I would have expected it to be a json array or something, like this:

`["My first item", "My second item"]`

This feels like it's got to be a common use case so hopefully I am just missing something obvious.

**Comment by rasmus** [comment]
Hi @cjstremick the MSSQL read model only supports value types. If you need a more complex read model, you'll have to use the `EventFlow.EntityFramework` and use Entity Framework as the MSSQL is only intended for those very basic read models.

**Comment by rasmus** [comment]
Closing this issue as the focus of the raw MSSQL read models is simplicity and there's a solution by using the `EventFlow.EntityFramework` NuGet package.
