### ISSUE TITLE
Separating events and aggregates

### ISSUE THREAD

**Issue by rsmythe** [eventflow/EventFlow#596]
I would like to house my `Events` in a separate project from my `Aggregates`. I plan to have event handlers running on various microservices and it would be nice if I could share the `Events` library without necessarily sharing the whole domain implementation. Unfortunately this currently creates circular dependency since, my `Aggregates` obviously need to know about the `Events` and for some reason my `Events` need to know what `Aggregate` they were raised by. 

Is there any reason why an `Event` can't just be a really simple, dumb object akin to a DTO? I don't understand why an `Event` would need to know what `Aggregate` it was raised by.

**Comment by jediwarpraptor** [comment]
Great question.  This doesn't make sense to me either.

**Comment by kwemou** [comment]
Maybe it would be sufficient to define interfaces on top of entities and just share the interfaces with the events together? Therefore it would not be necessary to share the entity itself.
Not sure whether it would work indeed.
regards

**Comment by rasmus** [comment]
The reason for the reference in the interface is to make all the generics "link" (lack a better word) and make sure you don't have to upcast in your code. However, I agree it would be a nice cleanup if the amount of arguments to generics could be a bit more loose, but I think this would require a large set of breaking changes and not something I think I would do for a version 1.0

**Comment by promontis** [comment]
@rasmus I have exactly the same issue. What would you suggest for the time being?

**Comment by promontis** [comment]
@rsmythe did you end up with something workable?
