### ISSUE TITLE
MongoDB: Concurrently execute 2 commands against the same aggregate does not throw OptimisticConcurrencyException for persistence component

### ISSUE THREAD

**Issue by yauheniparshiniou** [eventflow/EventFlow#598]
**Affects**
MongoDb persistence storage component.

**What I'm trying to do**
Concurrently execute 2 commands against the same aggregate.

**What I'd expect to happen**
An instance of OptimisticConcurrencyException to be thrown.

**What actually happens**
2 events with the same _aggregate_sequence_number_ are found in a database. 

**Cause**
In this case when the aggregate is instantiated with the next command a System.InvalidOperationException is thrown and nothing can be done rather than manually delete the last record in the database.

**Comment by rasmus** [comment]
@yauheniparshiniou Can you reproduce this in the EventFlow test suite? We have the tests in [MongoDbEventStoreTests](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.MongoDB.Tests/IntegrationTests/EventStores/MongoDbEventStoreTests.cs) which should test it. If they don't, then there might be a bug in the test itself

**Comment by eldstrom** [comment]
I have this problem also with the mongodb store. 

For me it is two requests from frontend for the same aggregate that arrives at different times to the event store backend and it seems if the events are pretty large (like 40kb+ in size, i know they are too big but i am stuck with it currently) and the amount of events for the aggregate goes above 30-40 in the sequence, it might take long time to store the event and another for the same aggregate gets added with same sequence number. 

Did you figure out a solution for the issue? I am currently trying to figure out a workaround myself but have not gotten anywhere yet.
