### ISSUE TITLE
Failed saga commands are silently ignored

### ISSUE THREAD

**Issue by mbican** [eventflow/EventFlow#599]
AggregateSaga.PublishAsync() doesn't check execution results.
If there is no exception thrown ISagaErrorHandler is not called.
Therefore I suggest to thrown an exception if saga command fails.
I am also creating pull request with my solution.
The Exception Type is open to discussion to integrate it into the framework.

**Comment by rasmus** [comment]
Old issue that has already been fixed. The `PublishAsync` now throws `SagaPublishException` if any commands failed

**Comment by rasmus** [comment]
Fixed in #603
