### ISSUE TITLE
Version 1.0 milestone discussion

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#601]
EventFlow is closing in on its fourth anniversary (initial comment is Mar 17, 2015) without a 1.0 release.

A while back I created the [1.0 milestone](https://github.com/eventflow/EventFlow/milestone/1) and I would like some input from the community on what should be in the release for it to have the 1.0 stamp.

I already put in a few issues based on request I got on e-mail, discussions found on Gitter and here on GitHub. Of these the #439 crash resilience is at the very top.

**Comment by mbican** [comment]
my thoughts about sagas #607 especially #605 seems easy to implement but kind of confusing from the design point of view because I don't actually know what saga should exatly be

**Comment by wgtmpeters** [comment]
@rasmus we are still planning on continuing the work on the crash resilience. But it will be a while before we can finish it.

**Comment by rasmus** [comment]
@wgtmpeters I'm happy that you are considering doing a PR with it as there's a lot of demand for the feature

**Comment by rasmus** [comment]
Copied from #607, written by @mbican 

>Since we are talking about milestones I want to share my thoughts on Saga Improvements (referencing separate issues from here)
> 
> #604 after reliable event redelivery in case of crash #439 is implemented we could use it for reliable saga published commands redelivery. That would require to atomically store saga produced commands together with saga produced events e.g. wrap commands into some saga meta-events. Then reuse mechanism for event redelivery to redeliver saga produced commands
> #605 resolve AggregateSaga dychotomy where if AggregateSaga receives command it can't publish commands properly
> #606 is topic for discussion about saga error handling. Seeing saga as a simple state machine
> #608 Actually implement saga-id in metadata as mentioned in the documentation. And also create default SagaLocator

**Comment by DavidRouyer** [comment]
What is the state of all of this, particularly #439?

**Comment by rasmus** [comment]
@wgtmpeters did you find a good solution for #439?

**Comment by rasmus** [comment]
Created #724 which outlines a plan for moving forward and I'll try to update that.
