### ISSUE TITLE
Community support

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#602]
During the recent months the EventFlow community has grown, both in the number of people participating in discussions on Gitter, but also through the number of issues and pull requests created. While the growth is fantastic, I also wan't to make sure that the right support and tooling is in place to allow the community to grow even further.

If you have suggestions on how the support for the community might be improved, please post it here.

**Comment by DureSameen** [comment]
some of these discussion should be channeled to other media or forums ..like stackoverflow... it will increase the overall reach coverage. 

I have also created suggested skill on upwork, to help to classify this platform as new thing to learn.

**Comment by bartelink** [comment]
Make a room in the DDD-CQRS-ES slack; suggest discussion questions be asked there (it also has a general and a eventsourcing place where general "how do I model this kinda thing" can be discussed) - having that _and_ a gitter allows the gitter to be more code-focused, and Issues to be well, issues

**Comment by rasmus** [comment]
Created the an initial channel named "EventFlow" at the DDD-CQRS-ES Slack https://ddd-cqrs-es.slack.com/messages/CHPAQKUGY/

**Comment by DureSameen** [comment]
how to join?

**Comment by bartelink** [comment]
Here's an [invite link](https://t.co/MRxpx0rLH2) (NB These things expire so search up invite link ddd-cqrs-es if that's the case)

**Comment by rasmus** [comment]
Their GitHub is here which contains the invite link https://github.com/ddd-cqrs-es/slack-community

**Comment by FinalFortune** [comment]
Is this channel still available? all links are expired

**Comment by DureSameen** [comment]
Hi , What  are you searching for?

**Comment by bartelink** [comment]
@FinalFortune replenishing with [updated](http://j.mp/ddd-es-cqrs) link now. Thanks for the heads up. The eventflow room has not seen much traffic, but the slack as a whole remains extremely useful and ehlpful
