### ISSUE TITLE
Reliable saga published commands redelivery after crash

### ISSUE THREAD

**Issue by mbican** [eventflow/EventFlow#604]
after reliable event redelivery in case of crash #439 is implemented we could use it for reliable saga published commands redelivery. That would require to atomically store saga produced commands together with saga produced events e.g. wrap commands into some saga meta-events. Then reuse mechanism for event redelivery to redeliver saga produced commands

**Comment by rasmus** [comment]
Good input and definitely relevant for a 1.0 release
