### ISSUE TITLE
Saga Improvements Summary

### ISSUE THREAD

**Issue by mbican** [eventflow/EventFlow#607]
Since we are talking about milestones I want to share my thoughts on Saga Improvements (referencing separate issues from here)
* #604 after reliable event redelivery in case of crash #439 is implemented we could use it for reliable saga published commands redelivery. That would require to atomically store saga produced commands together with saga produced events e.g. wrap commands into some saga meta-events. Then reuse mechanism for event redelivery to redeliver saga produced commands
* #605 resolve AggregateSaga dychotomy where if AggregateSaga receives command it can't publish commands properly
* #606 is topic for discussion about saga error handling. Seeing saga as a simple state machine
* #608 Actually implement saga-id in metadata as mentioned in the documentation. And also create default SagaLocator

Anyway that's all I have for today. Enjoy :-)

edited 16 mar 2019: added #608

**Comment by rasmus** [comment]
Nice cleanup. I have added #604, #606, and #608 to the 1.0 milestone and added a few comments to #605. I'll close this issue as its merely referencing the other issues and we can continue the discussion for each issues or in the #601 milestone discussion.

Thanks for the input.
