### ISSUE TITLE
DomainEventPublisher shouldn't stop at exception

### ISSUE THREAD

**Issue by mbican** [eventflow/EventFlow#609]
Since IDomainEventPublisher.PublishAsync() is called after events are already successfully persisted into eventStore all event subscribers should be notified about event. Currently if the first subscriber throws an exception the other subscribers don't receive the event. Better solution would be:
1) catch exceptions from each subscriber
2) collect those exception in an array
3) throw AggregateException() after all subscribers are notified

**Comment by rasmus** [comment]
Think this will be a good candidate for 1.0 as it might rely on changing the code significantly.

Considerations
- I a subscriber throws an exception on the first event, should it still receive the next 
- How should this interact with the `IDispatchToSubscriberResilienceStrategy`
