### ISSUE TITLE
Dead letter event queue

### ISSUE THREAD

**Issue by mbican** [eventflow/EventFlow#610]
(Relates to #439 "Reliable event redelivery") When event handler throws an exception it should be atomically persisted into event store together with the confirmation that the event has been published to all subscribers.

For transient errors it would be nice to have an scheduled job which would try to redeliver events theirs handler has thrown an exception. e.g.: when the handler is suppose to send an email but the smpt server is temporarily down

**Comment by rasmus** [comment]
Now possible to implement with the `I*ResilienceStrategy` interfaces
