### ISSUE TITLE
Interface for aggregates - how to unit test the Command Handlers?

### ISSUE THREAD

**Issue by RTodorov** [eventflow/EventFlow#616]
Hello @rasmus,

I'm trying to unit test my CommandHandlers, for that I had to make them use an interface for the Aggregate instead of the aggregate itself. Tests works fine but for EventFlow crashes when I try to publish the command with the following error:

```
System.ArgumentException: Aggregate type 'IMyAggregate' doesn't have just one constructor
   at EventFlow.Aggregates.AggregateFactory.CreateAggregateConstruction[TAggregate,TIdentity]()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at EventFlow.Aggregates.AggregateFactory.CreateNewAggregateAsync[TAggregate,TIdentity](TIdentity id)
   at EventFlow.Aggregates.AggregateStore.LoadAsync[TAggregate,TIdentity](TIdentity id, CancellationToken cancellationToken)
   at EventFlow.Aggregates.AggregateStore.<>c__DisplayClass11_0`3.<<UpdateAsync>b__0>d.MoveNext()
```

This is my IMyAggregate:

```
public interface IMyAggregate : IAggregateRoot<MyId>
```

This is MyAggregate:

```
public class MyAggregate : AggregateRoot<MyAggregate, MyId>, IMyAggregate
```

This is one of the commands:

```
public class MyExampleCommand : Command<IMyAggregate, MyId, IExecutionResult>
```

And finally, the command handler:

```
public class MyExampleCommandHandler : CommandHandler<IMyAggregate, MyId, IExecutionResult, MyExampleCommand>
```

I'm using the AspNetCore package with `Microsoft.Extensions.DependencyInjection` instead of Autofac.

Any idea how can I tell the `AggregateFactory` to use the implementation instead of the interface?

Thank you very much

**Comment by rasmus** [comment]
@RTodorov your spinning up the aggregate store in a unit test, I would start by stubbing that and maybe a few others. But if you wan't to fix the exception you are seeing, then the default implementation of `IAggregateFactory` uses classes directly and can't create the aggregate. Create your own implementation that resolves the aggregate using IoC and parses the aggregate ID to it.

**Comment by RTodorov** [comment]
@rasmus yeap, I played around with that idea and it worked but for now I found it easier to just mark the methods as `virtual` in the AggregateRoot itself. Works fine and I don't have to maintain my own implementation of `IAggregateFactory`.

Also, my Unit test is as simple as this:

```
            var aggMock = new Mock<MyAggregate>(MyId.New);
            var command = new DoSomethingCommand(MyId.New, "something");

            new DoSomethingCommandHandler()
                .ExecuteCommandAsync(aggMock.Object, command, CancellationToken.None);

            aggMock.Verify(mock => mock.DoSomething(command.SomeParameter), Times.Once());
```

I'm simply stating that the command handler called the right method with the right parameters on the aggregate.

**Comment by bryanscheele** [comment]
@rasmus and @RTodorov I don't like the idea that everything is virtual. So I like to implement the `IAggregateFactory` solution. 

Unfortunately I can't get it to work, when I register `ConcreteAggregate` as `IAggregate` the resolver throws an exception not being able to create `ConcreteAggregate` because it can 't instantiate `AggregateId`.

Could you please provide an example on how to "Create your own implementation that resolves the aggregate using IoC and parses the aggregate ID to it."?

**Comment by rasmus** [comment]
@bryanscheele The specific ID that are being passed to the aggregate factory for it to use in its created isn't in the IoC container (naturally). The [aggregate factory](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/Aggregates/AggregateFactory.cs) in EventFlow tries to resolve everything BUT the ID in the IoC. Maybe you could do something similar using the mocks.

**Comment by rasmus** [comment]
No response, closing as old
