### ISSUE TITLE
Ship PDB files with Nuget package

### ISSUE THREAD

**Issue by RTodorov** [eventflow/EventFlow#617]
Would be nice to have the PDB files shipped with the nuget package to help with debugging.

For reference: https://github.com/aspnet/Universe/issues/131#issuecomment-363269268

**Comment by DavidRouyer** [comment]
See https://github.com/eventflow/EventFlow/pull/501, I'll try to work on it this week

**Comment by RTodorov** [comment]
Nice, SourceLink would also solve the problem, thanks for the good work!

**Comment by wgtmpeters** [comment]
Is there anything planned for this? It seems like with the latest version I am not able to load the symbols in the module view during debugging.
And that is needed to be able to use sourcelink to step into the code right?

**Comment by rasmus** [comment]
Source link is added https://github.com/eventflow/EventFlow/pull/626

**Comment by DavidRouyer** [comment]
@rasmus Have you published the symbol package on NuGet?

**Comment by rasmus** [comment]
@DavidRouyer yes, the changes went out in release [v0.70.3824](https://github.com/eventflow/EventFlow/blob/develop/RELEASE_NOTES.md#new-in-0703824-released-2019-04-11] that went on NuGet org the 2019-04-11

**Comment by rasmus** [comment]
But we could add the PDB files as well

**Comment by rasmus** [comment]
Trying it out in #638

**Comment by DavidRouyer** [comment]
@rasmus You merged the changes but you have to publish the symbols package (`.snupkg`) along with the `.nupkg`.
Once it's done, you should see this:
![Capture](https://user-images.githubusercontent.com/1556750/57799076-88ee8c00-774e-11e9-9346-7f39f9e477a9.PNG)

On your package page https://www.nuget.org/packages/EventFlow

**Comment by rasmus** [comment]
Yes, the issue are the AppVeyor built-in support for uploading NuGet packages that EventFlow uses: 
https://github.com/appveyor/ci/issues/2753

**Comment by rasmus** [comment]
May have found a simple workaround

**Comment by rasmus** [comment]
The source link integration is broken. I opened https://github.com/eventflow/EventFlow/issues/644 to reflect it. Closing this issue as the original idea is implemented (although broken).

**Comment by rasmus** [comment]
The PDB files will be in the normal package and in the snupkg as well after https://github.com/eventflow/EventFlow/pull/645 is done

**Comment by rasmus** [comment]
Released in v0.72.3914 along with corrected source link support. Remember to disable "just my code"

**Comment by rasmus** [comment]
![image](https://user-images.githubusercontent.com/18956/58489442-956dde00-816b-11e9-8f61-638efd0aea07.png)

snupkg files are also released
