### ISSUE TITLE
Explicit Interface Implementation of IEmit<> is not supported

### ISSUE THREAD

**Issue by jinhong-** [eventflow/EventFlow#618]
I noticed that explicit implementation of the IEmit interface will not be picked up by the system. Probably because of the way it detects the Apply method. I am not sure if you want to deem this as a bug or feature, since from C# perspective, this is still considered a valid implementation of the interface. Below is an example of a explicit IEmit<> implementation

void IEmit<ExampleEvent>.Apply(ExampleEvent exampleEvent){
}

**Comment by rasmus** [comment]
The `IEmit<>` is meant merely as a helper to make sure that the method signature is correct to be picked up by the reflection.

Have a look at the documentation, EventFlow supports a few different ways of saving state as there are many, many different opinions on what is "best".
http://docs.geteventflow.net/Aggregates.html#applying-events

**Comment by jinhong-** [comment]
Not trying to argue about "best", just wanted to suggest a possible improvement

**Comment by rasmus** [comment]
Sorry, neither was I. I try to in include different ways to do the same thing's

I think I misunderstood your description. Are you saying that any IEmit implementations aren't picked up by the aggregate?

**Comment by jinhong-** [comment]
@rasmus yes. If I were to explicitly implement IEmit<> it will not be picked up

Explicit
```
class ExampleAggregate : IEmit<ExampleEvent>
{
  void IEmit.Apply(ExampleEvent exampleEvent)
  {
  }
}
```

Implicit
```
class ExampleAggregate : IEmit<ExampleEvent>
{
  public void Apply(ExampleEvent exampleEvent)
  {
  }
}
```

**Comment by rasmus** [comment]
Darn, its a bug then
