### ISSUE TITLE
[BUG] MongoDbReadModelStore GetAsync throws exception for unknown id's

### ISSUE THREAD

**Issue by bryanscheele** [eventflow/EventFlow#625]
I found a bug when using the `ReadModelByIdQuery` on a `MongoDbReadModelStore`. When you query for a not existing id an exception is thrown: `System.InvalidOperationException: Sequence contains no elements`.

This is due to the `FirstAsync` here: https://github.com/eventflow/EventFlow/blob/9000c945b7b7fc1dec4cb95298c1bf61c61e0361/Source/EventFlow.MongoDB/ReadStores/MongoDbReadModelStore.cs#L66

We should change it to `FirstOrDefaultAsync`. I'd make a pull request, but I don't have any permission to push my branch

**Comment by wgtmpeters** [comment]
this can be closed?

**Comment by rasmus** [comment]
Yes, just forgot all about it after releasing
