### ISSUE TITLE
Eventflow.ElasticSearch required Enhancements 

### ISSUE THREAD

**Issue by DureSameen** [eventflow/EventFlow#627]
1. Support of RoutingKey for multi tenancy. #621 
                           https://www.elastic.co/blog/found-multi-tenancy
2. Parent-Child mapping 
              https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child-mapping.html
3. Better Exception throwing/handling  #620 
4. Global Serilog support. 

NEST is so powerful, we need to leverage it proper usage. If there is a suggestion for more changes other than above, do let me know. I am going to develop enhanced package.

**Comment by rasmus** [comment]
I'm going to close this issue. Each point is addressed below

1) please create a separate issue for this with detailed examples of the change. linking to an article consisting of multiple pages makes it hard to understand the specific need at a glance
2) has been discontinued after 2
3) already an issue
4) EventFlow will not reference Serilog directly, but rather implement the structured loggin already mentioned in #591
