### ISSUE TITLE
Distinct Command And Documentation

### ISSUE THREAD

**Issue by KoriSeng** [eventflow/EventFlow#628]
There is discrepancy between the source and the documentation i think.

https://github.com/eventflow/EventFlow/blob/3ae504fdddac3ef66befe524210e393e37e8936e/Source/EventFlow/Commands/DistinctCommand.cs#L35

**Comment by rasmus** [comment]
@7thcubic in what way? specifically?

**Comment by rasmus** [comment]
Closing, unsure

**Comment by wenkepaul** [comment]
@rasmus , The source code has a third type parameter (`TExecutionResult`) which doesn't exist in the documentation.

[Documentation](https://docs.geteventflow.net/Commands.html) has
```
public class UserUpdatePasswordCommand : DistinctCommand<UserAggregate, UserId>
{
  // ...
}
```

And the source code (at least version 0.81.4483) has:
```
public abstract class DistinctCommand<TAggregate, TIdentity, TExecutionResult> : ICommand<TAggregate, TIdentity, TExecutionResult>
{
  // ...
}
```

**Comment by wenkepaul** [comment]
`CommandHandler` accepts both three and four type parameters.  The implementation with three type parameters passes `IExecutionResult` to the implementation with four type parameters.  Could the same be done for `DistinceCommand`?
```
public abstract class CommandHandler<TAggregate, TIdentity, TResult, TCommand>
```
and
```
public abstract class CommandHandler<TAggregate, TIdentity, TCommand> : CommandHandler<TAggregate, TIdentity, IExecutionResult, TCommand>
```

**Comment by rasmus** [comment]
Thanks @wenkepaul for clarifying

**Comment by wenkepaul** [comment]
If you think following the example from the `CommandHandler` is the ideal solution, I can implement it.
