### ISSUE TITLE
Async ExecuteAfterValidation

### ISSUE THREAD

**Issue by hvidgaard** [eventflow/EventFlow#630]
I am implementing an EventFlow system, and one of the things that seemed odd, is that in the examples, the CommandHandler implementations return a Task, but the calls are for all intents and purposes synchronous. So I was pondering to make the specification checks async to flow the pattern to the bottom, rather than just returning Task.FromResult. It's a rather simple modification:

```
private async Task<IExecutionResult> ExecuteAfterValidation(Func<IAggregateEvent<MyAggregate, MyId>> evt, params Func<IExecutionResult>[] checks)
{
    IExecutionResult ir = null;
    //foreach (var check in checks)
    foreach (var check in checks.Select(check => Task.Run(() => check())))
    {
        if (cancellationToken.IsCancellationRequested)
        {
            return ExecutionResult.Failed();
        }
        ir = await check;
        if (!ir.IsSuccess)
        {
            return ir;
        }
    }
           
    IAggregateEvent<MyAggregate, MyId> @event = evt();
    if (@event != null)
    {
        Emit(@event);
        return ir ?? ExecutionResult.Success();
    }
    else
    {
        return ExecutionResult.Failed();
    }
}
```
I can however not at this point in time figure out if it's a bad idea or not. It's offloading a probably small amount of work to the threadpool, On the other hand, it seems that the "best practice" is to use the commands that way, so why does it return a task? Is it because you can and should use commands for IO?

**Comment by rasmus** [comment]
EventFlow uses async/await throughout the entire framework, not to make it asynchronous, but to use the utilize resource better.

I think this article describes some of the aspects: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/

Or else basically any article written by Stephen Cleary on the subject. Be careful if reading articles not on MSDN or not by Stephen, many don't get it quite right.

**Comment by hvidgaard** [comment]
I'm aware of that. But the documentation explicitly use `return Task.FromResult(executionResult);` which makes the handling of a command synchronous . What is the intended use case where you would actually make the commandhandlers perform an async operation?

**Comment by rasmus** [comment]
Hi @hvidgaard so does any method that has async/await in it, or at least until an unfinished task is returned, typically when some IO operation is hit. Adding the async keyword to a method that very simple, saves the compiler from generating the async/await state machine.

Please note that [Stephen Cleary does suggest](https://blog.stephencleary.com/2016/12/eliding-async-await.html) that the async/await keywords should always be used, but that's more to minimize the amounts of mistakes.

I can recommend this video by Bart De Smet from Microsoft. It very nicely explains the async/await state machine.
https://channel9.msdn.com/Events/TechDays/Techdays-2014-the-Netherlands/Async-programming-deep-dive

**Comment by rasmus** [comment]
As for your example, EventFlow _never_ invokes `Task.Run(() => ...)` as it basically put your work on a new thread (for .NET Core and in most other cases anyway).

If your application has a UI, then it makes perfect sense to send the publishing of commands to a worker threads instead of starting them on the UI thread.

Any validation errors, in case of failed commands, could then be dispatched to the UI threads to update it with any errors.

Sorry for not being precise, I was reading a lot of issues and must have gotten them mixed up.

**Comment by hvidgaard** [comment]
@rasmus So, the signature of CommandHandler is so I can choose to do it synchronously or put it in a Task if that suits my use case better?

**Comment by rasmus** [comment]
Yes, basically
