### ISSUE TITLE
Entity Framework Context

### ISSUE THREAD

**Issue by 7thcubic** [eventflow/EventFlow#632]
Is there any reason why the EF core uses  the context provider instead of the context directly, and use the autofac/DI to just control and inject the context and therefore the usage would allow the context to be fulfilled in a separate location of the project? 

https://github.com/eventflow/EventFlow/blob/25611e8181c32be1b76c2ed08585c8d33bab3cf2/Source/EventFlow.EntityFramework/EventStores/EntityFrameworkEventPersistence.cs#L48

**Comment by frankebersoll** [comment]
The intention was that EventFlow should be able to control the lifetime of the DbContext. I‘m not sure if this was possible if it used an injected instance - I probably wouldn‘t want to call Dispose on an object that Got injected by a container. In some way, it „forces“ the user to think about how EventFlow should get its DbContext, as there is no good default that works all the time. For example, if you use `AddDbContext<T>` it will lead to issues on startup or jobs or whenever there is no explicit DI scope: https://github.com/aspnet/EntityFrameworkCore/issues/4988

Maybe there is a better or easier solution, I‘m happy to discuss this.

**Comment by i-dentify** [comment]
> Maybe there is a better or easier solution, I‘m happy to discuss this.

Afaik the problem with injecting the DbContext directly is, that in usual cases the resolved context is cached and reused (e.g. within a lifetime scope on a per-request base). When running multiple parallel handlers or whatsoever, this could cause some weird issues.
So far I've only read about two solutions to overcome such issues. The one is by using a factory, as YOU did and opening/disposing the context where it is needed. The other one I know from AutoFac, where `Owned<T>` (or: `Func<Owned<T>>`) is a way to go. I don't know how this can be done in other DI containers. One thing I like about EventFlow is that you are not bound to a certain component (like: AutoFac)

**Comment by 7thcubic** [comment]
The initial plan for me was to write a class lib that has its own internal DI, that can be injected into a net core project, where there could be specifications requirements determined by the client.

So my initial plan was to initialise the event flow within the class lib's DI, but after fiddling with it a while, i figured that it would be easier for me to just make an extension into eventflow allow the DI to be mostly handled on the net core project.

As it was a migration from EF based + Identity server, the methodology used when handling the injection of the context was different and that confused me.

Nevertheless i have found the solution, which is to either specify a interface and resolve within the class lib, or as said create extension on the eventflow options.

So i think i am at peace with the library's choice of handling the db context.
