### ISSUE TITLE
Why State Aggregate is not apply in event incomming order ?

### ISSUE THREAD

**Issue by poumup** [eventflow/EventFlow#633]
I have several event applied to an aggregate.
I have state aggregate.
When one aggregate is load event aren't applied to the aggregateState in events incomming order.
Why ?

**Comment by poumup** [comment]
I am using Potgresql backend, but with eventstore, i have the same issue.
I am thinking about have valueobjet in aggregate instead of AggregateState.
It is a good way ?

**Comment by poumup** [comment]
@rasmus any idea ?

**Comment by rasmus** [comment]
@poumup Sorry, I haven't worked on the PostgreSQL implementation. The integration tests should verify that the events are loaded, I can't remember if its validated that the order is correct though. Can you reproduce the problem using the EventFlow integration tests? It would make fixing the problem a lot easier.
