### ISSUE TITLE
Emitting multiple events

### ISSUE THREAD

**Issue by hvidgaard** [eventflow/EventFlow#635]
I'm working on an implementation of an EventFlow system for sending notifications, I'm struggling figuring out the best approach to emitting multiple events. 

The notifications have multiple deliveries in one package, and multiple packages in one bundle. To avoid a Bundle "GodObject", Bundles and Packages are both aggregate roots, and linked together via a ShipmentSaga. Everything interesting happens in the PackageAggregate, but the Bundles should be committed in an all or nothing fashion.

When a Bundle is created, the Saga will start and send 1 or more "CreatePackage" commands. When a Package is created one or more deliveries will have to be queued but I cannot figure out where to emit the events. I want the "PackageCreatedEvent" to positively be recieved by all subscribers before any "DeliveryQueuedEvent" reaches them. If I just emit the events in order from the PackageAggerate is that guaranteed?

Alternatively the saga can react the the PackageCreatedEvent by emitting 1 or more "QueueDeliveryCommand" but that seems like the saga is doing what the PackageAggerate should be doing?

**Comment by 7thcubic** [comment]
Basically what you need is more Another saga for packagecreated.

Basically you can create a new event for package create requested, which will create a new package in package aggregate.

After which the package aggregate will emit a new package created event.

And the package delivery saga which starts in package created event will then call the command for delivery queue command.

Delivery queue command will then start a delivery queue requested on delivery aggregate

Which then the delivery aggregate will then emit a delivery queued event.

Pretty sure that is it.

**Comment by hvidgaard** [comment]
@7thcubic That seems so obvious now. What is needed is a process manager to handle the state and actions according to the nitty gritty details outside of the aggregate. I assume that is to be done in a saga in EventFlow.

**Comment by rasmus** [comment]
You can emit multiple events from with the same aggregate method, merely invoke the `Emit` multiple times. As you said, they makes sense in several cases, e.g. a simple case we have is changing pictures in a list. Here we have both `PicturesAddedEvent` and `PicturesRemoveEvent`, both are emitted (if applicable).

**Comment by hvidgaard** [comment]
@rasmus Is it guranteed that if I emit event1 and event2 from the same aggregate in that order, then all subscribers of both events will recieve them in that order?

**Comment by rasmus** [comment]
Yes, the code for it is right here

https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/Subscribers/DispatchToEventSubscribers.cs#L67

Please note that if you have nested subscriptions (agg1 -> event 1 -> agg2 -> event 2), then the order of received events might not be as expected as described here http://docs.geteventflow.net/Subscribers.html#out-of-order-event-subscribers

**Comment by rasmus** [comment]
Also note that subscribers are invoked after the events have been committed to the event store, thus if you have multiple threads/requests accessing the same aggregate, you will experience out of order events.
