### ISSUE TITLE
support for querying for collections

### ISSUE THREAD

**Issue by Yaevh** [eventflow/EventFlow#646]
What is the recommended way to query for a collection of aggregate roots/read models? Right now EventFlow seems to only support querying for a single aggregate root.
Let's say, I have a User entity, which exposes the user's `FirstName` and `LastName`. How can I use EventFlow's infrastructure to query for read models of all users which `FirstName == Rasmus`?
Or, broadening the question - how can I query for a read model that I don't know the AggregateId or other unique ID (for example, querying for user entity by a part of their name/email)?

EDIT: disregard that, it's as easy as implementing `IQueryHandler<UserByFirstNameQuery, IEnumerable<UserReadModel>>`, you may delete this question; though it'd be helpful to add a note about this in documentation

**Comment by rasmus** [comment]
Hi @Yaevh aggregates can only be fetched by their ID and only one at a time. For reading multiple instances you should use specialized read models. EventFlow only provides some very basic support for reading read models, as that part will in most cases be unique to the application/service.

If you e.g. want every aggregate with a specific first name, you would have to create a read model that makes querying the first name easy. Then use that to get the ID of the corresponding aggregates.

**Comment by rasmus** [comment]
Closing as this is very old and no response
