### ISSUE TITLE
Same identity in different domains

### ISSUE THREAD

**Issue by DaGrisa** [eventflow/EventFlow#653]
Hello, I have a question about the `Identiy<>` concept. 

A quick explanation of my problem: I have an User-Aggregate with an `UserId : Identity<UserId>` in Domain A and an Employee-Aggreate in Domain B. Employee is just an User, but with only its name.

How does the ID of Employee should look like in the EventFlow concept?
Should i use the UserId in the Empoyee-Aggregate?
What about `EmployeeId : Identity<UserId>`? Or `EmployeeId : UserId`?
Maybe just a simple string-replacement ("user" to "employee") when an Event of User is handled in Domain B?

And why does the ID contain the entity name, e.g. "user-guid", and not just the plain guid?

Thanks in advance,
Daniel

**Comment by mbican** [comment]
I would use independent classes for UserId and EmployeeId because the Identity<> class is designed in a way that it cannot be inherited. You can easily convert the id by static method `Identity<T>.With(Guid)`: `EmployeeId.With(userId.GetGuid())`

**Comment by DaGrisa** [comment]
Thank you, that did the trick.

**Comment by rasmus** [comment]
Closing as answered
