### ISSUE TITLE
Listen to all AggregateEvents

### ISSUE THREAD

**Issue by DaGrisa** [eventflow/EventFlow#663]
Hello,

We have the case, that we need to listen to all AggregatgeEvents of an specific domain (in that domain).
How are we able to implement this with EventFlow? We've tried to use a subscriber for that, but there we are not able to listen to all AggregateEvents, only to specific ones.

Best regards,
Daniel

**Comment by MongkonEiadon** [comment]
You could use `ISubscribeSynchronousToAll` to listening all events

**Comment by DaGrisa** [comment]
Thank you, we created a test subscriber: 
`public class TestSubscriber : ISubscribeSynchronousToAll
  {
    /// <inheritdoc />
    public Task HandleAsync(IReadOnlyCollection<IDomainEvent> domainEvents, CancellationToken cancellationToken)
    {
      throw new NotImplementedException();
    }
  }`
and added the assembly to the eventFlow options: `eventFlowOptions.AddDefaults(assembly);`

But still nothing happens in the "HandleAsync" method.

**Comment by DaGrisa** [comment]
We think we found the problem and created a fix for it: https://github.com/eventflow/EventFlow/pull/665

**Comment by rasmus** [comment]
@DaGrisa thanks for the bugfix!
