### ISSUE TITLE
MetadataProviders scope

### ISSUE THREAD

**Issue by Cream256** [eventflow/EventFlow#667]
Hi all! I have a question about MetadataProviders scope.

I have an `AuthenticatedUser` metadata provider, which sets the information about authenticated user from the bearer token. The problem is, after I change the bearer token, I still get the old one for each new event.

It seems that for every new event, the same `AuthenticatedUser` metadata provider is run, hence the old data. I have tried to play with `Lifetime`, but to no results. 

When I was debugging it, it seems that EventFlow is creating new metadata providers, but still uses the old one. Is this expected?

**Comment by rasmus** [comment]
It isn't expected. If EventFlow is creating the new provider every time it seems OK. Have a look at how the token is read from within the provider and make sure its lifetime is correct.

**Comment by rasmus** [comment]
Need to test this
