### ISSUE TITLE
Events in different domains with same name

### ISSUE THREAD

**Issue by DaGrisa** [eventflow/EventFlow#668]
We think that we found a problem with deserializing events that have the same name, but live in different domains. When deserializing EventFlow mixes up the classes.

**Example**
Domain A => A.DataCreatedEvent
Domain B => B.DataCreatedEvent
Deserializing A.DataCreatedEvent results in B.DataCreatedEvent

Maybe you can investigate a little bit more, we don't have the issue anymore, because the requirements changed so that we don't have the events with the same name anymore.

**Comment by rasmus** [comment]
@DaGrisa as a work around you could have a look at the `EventVersion` attribute for events. It makes it possible to use different string names for events, e.g. prefix each event name with the domain.

Here's an example on usage
https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.Tests/UnitTests/EventStores/EventDefinitionServiceTests.cs

**Comment by rasmus** [comment]
Related to #907

**Comment by rasmus** [comment]
Closing this as its a duplicate
