### ISSUE TITLE
Replace reflection magic

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#68]
Have a look at this to see if some of EventFlows reflection code can be simplified.

https://github.com/ploeh/Albedo

**Comment by rasmus** [comment]
Maybe also cache compiled expressions instead of calls to e.g. `MethodInfo.Invoke` to improve performance

http://stackoverflow.com/questions/2933221/can-you-get-a-funct-or-similar-from-a-methodinfo-object

**Comment by rasmus** [comment]
Another performance article http://blogs.msmvps.com/jonskeet/2008/08/09/making-reflection-fly-and-exploring-delegates/

**Comment by rasmus** [comment]
Another performance article http://www.palmmedia.de/Blog/2012/2/4/reflection-vs-compiled-expressions-vs-delegates-performance-comparision

**Comment by frankebersoll** [comment]
This seems to be implemented via compiled lambda expressions since 9d3cf98f.

**Comment by rasmus** [comment]
agree
