### ISSUE TITLE
Read data from the Aggregate in ReadModel Apply

### ISSUE THREAD

**Issue by hvidgaard** [eventflow/EventFlow#680]
Lets assume that we have an aggregate with multiple properties: Created, Title, Creator, and multiple other properties.

It's possible to "soft delete" an aggregate, in the sense that it has been put in the "recycle bin" but still possible to recover.

It's required to be able to read a list of all soft deleted items, and you need the Created, Title, and Creator properties for filtering and showing in a list.

I have to put those properties in the SoftDeletedEvent which does not seems like the right way. Can I query the aggregate store to get the current aggregate and lift the values from there, that doesn't seem like the right way either? Subscribing to all aggregate updating the relevant state result in significantly more overhead, and my readmodel table would contain all aggregates and not just the delete ones.

Is there a more dogmatic way to do this?

**Comment by rutgervanwilligen** [comment]
One way I could think of is adding a 'SoftDeleted' field (`bool` or `DateTime?`) to the read model, initializing all values to `false` or `null` (indicating they are not deleted), updating an aggregate's value based on the SoftDeletedEvent, and using this value when querying the read model.

**Comment by hvidgaard** [comment]
@rutgervanwilligen Is that not my last suggestion?

That would have all, potentially millions, of aggregates that are not deleted in the table, and they are not likely to be deleted ever. The vast majority will be straight up be deleted from the eventstore due to GDPR. The only soft deleted aggregates are the ones a user have decides should be deleted, which is only a fraction of the total.

**Comment by rasmus** [comment]
Another possible idea is to  take a snapshot of all the properties that you want to be able to recover, create a new read model with these values and then delete the aggregate. Then if you wanted to recreate the aggregate, you would created a `ImportedFromDeletedEvent` that would contain all the properties and be the first event in a new aggregate.

**Comment by 7thcubic** [comment]
My implementation is a bit more straightforward.

I implement a datetime nullable deletedAt.

When a user delete the aggregate (let's call it square), the aggregate will set a deletedAt date and the read models will too.

When querying for squares using the read models, just ignore those that has a deletedAt set. Thus the aggregate is never really deleted.

You could implement context mark for deletion as per normal. And change your mind and rebuild the read models? Not sure if it make sense.

I find read/querying aggregate directly a tad overkill.

**Comment by hvidgaard** [comment]
@rasmus That's a possibility, but there is a hard requirement of aggregate history. I think I've settled on just including all the search and filtering properties in the deleted event. It's the least friction. One other possibility could be splitting the "deletedWithProperties" event into a deleted event and deletedreadmodelupdated event with the properties. Both solutions pollutes the event stream, but are acceptable.

@7thcubic That would require reacting to multiple events on the aggregate, and have a very large table where only a handful of rows are actually deleted aggregates. If the system needs a large table with all aggregate properties it makes sense, but do far it does not.
