### ISSUE TITLE
Event publishing

### ISSUE THREAD

**Issue by Adam-MagmaSw** [eventflow/EventFlow#689]
Hi,
In the Readme it mentions 'Event publishing'

> Event publishing: Sometimes you want other applications or services to consume and act on domains. For this EventFlow supports event publishing.

However there doesn't seem to be a section for it in the documentation - is there any way of doing this currently?

**Comment by rasmus** [comment]
That's a wrong indention in the read-me file.

Before:
![image](https://user-images.githubusercontent.com/18956/66065954-d1191a00-e548-11e9-83e8-c044f4ef616c.png)

Now:
![image](https://user-images.githubusercontent.com/18956/66065971-dc6c4580-e548-11e9-8438-a1a1c3fa1ec4.png)

Its currently only RabbitMQ that's supported, but you can register an implementation on `ISubscribeSynchronousToAll` to get all events and publish the events to a custom location.

**Comment by rasmus** [comment]
Closing as answered
