### ISSUE TITLE
Mocking: Virtual Members For Baseclasses

### ISSUE THREAD

**Issue by DaGrisa** [eventflow/EventFlow#690]
Today i tried to write an unit test for a derivation of the AggregateRoot base-class. But I wasn't able to set the "IsNew" flag, because it is not virtual.
Neither Moq, nor NSubstitute were able to override a non virtual class member.

Is there some known workaround for mocking members of those base-classes in an unit test?
Or do we have to make all of these members virtual in EventFlow?

Thank you in advance,
Daniel

**Comment by rasmus** [comment]
If there's a need, then I can see no reason why these shouldn't be virtual. Just submit a PR with the change and updated release notes.
