### ISSUE TITLE
Question: Is LoadAllCommittedEvents guaranteed to return results in aggregate version order

### ISSUE THREAD

**Issue by rnilsark** [eventflow/EventFlow#691]
Evaluating using Eventflow with the EF.Core provider. When streaming all events from the event store using LoadAllCommittedEvents; events are ordered in GlobalSequenceNumber order.

From what I can see, committing events are done using DbContext.AddRange which should not guarantee to preserve order when passing multiple events to it. 
With AggregateSequenceNumber  set in code while GlobalSequenceNumber is managed by database, it sounds like AggregateSequenceNumber may be returned out of order when streaming. 
 
Is this handled some way?

**Comment by rasmus** [comment]
@frankebersoll do you have a comment?

**Comment by frankebersoll** [comment]
I'm sorry it took me so long to get back to you. Maybe the topic is still relevant - I think you found a bug.

[There are several issues in the EF Core Repository](https://github.com/dotnet/efcore/issues/7894) which indicate that the order is actually not guaranteed at insert time. This is somehow logical if you think about it.

Hoping that it doesn't make much of a difference from a performance perspective, we could call "SaveChanges" per event.
