### ISSUE TITLE
Incompatibility with .net core 3.0

### ISSUE THREAD

**Issue by jonnybi** [eventflow/EventFlow#694]
Hosting EventFlow in a .net core 3.0 web application fails with this exception:

```
System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'

```

It seems EventFlow having the same problems NSwag had with .net core 3.0
and caused by a reference to EventFlow.DependencyInjection
Create a .net core 3 web api application and add a reference to EventFlow.DependencyInjection to reproduce.

Similar issues:
- https://github.com/RicoSuter/NSwag/issues/1961
- https://github.com/aspnet/AspNetCore/issues/7220
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1030

**Comment by ProH4Ck** [comment]
I'm working on it here: #686
