### ISSUE TITLE
Saga with distributed services

### ISSUE THREAD

**Issue by promontis** [eventflow/EventFlow#695]
Hi there!

I was wondering how this library publishes commands to other bounded contexts that are distributed when using sagas. 

Sagas subscribe to events from several bounded contexts. If my bounded contexts are distributed, I can use the out-of-the-box RabbitMQ implementation as a message transport between those distributed services, right?

Bu what about commands?

From what I've read in the docs, I can publish commands like this:
```
Publish(new MakeReservation(/*...*/));
```

However, as far as I know, this only works within the same process. Am I missing something?
Should I be using the commandbus only within the same process?

**Comment by rasmus** [comment]
That's correct commands only work within the same service provider. For that you need to do something custom. I haven't see anyone coupling different contexts using commands before, usually you react to events from other contexts.

**Comment by promontis** [comment]
@rasmus mmm... that's actually what I want to achieve... react to events from other contexts.

I've noticed there are some implementations to publish events to a message bus (RabbitMQ, Kafka), but not yet subscribing from it. There is this PR #384, but AFAIK it is far from complete. 

Is this something that's still unsupported?

**Comment by FinalFortune** [comment]
> @rasmus mmm... that's actually what I want to achieve... react to events from other contexts.
> 
> I've noticed there are some implementations to publish events to a message bus (RabbitMQ, Kafka), but not yet subscribing from it. There is this PR #384, but AFAIK it is far from complete.
> 
> Is this something that's still unsupported?

Not sure what the future of that PR is, but from @MongkonEiadon's VehicleTracker project you can see how to add a consumer service to relay to your IAsynchronousSubcriberTo implementations -
[Consume Service](https://github.com/MongkonEiadon/VehicleTracker/blob/master/src/Infrastructures/Infrastructure/RabbitMq/RabbitConsumePersistenceService.cs)
[Usage](https://github.com/MongkonEiadon/VehicleTracker/blob/master/src/Apps/EventConsumer.App/Program.cs)

**Comment by promontis** [comment]
@FinalFortune @MongkonEiadon mmm... from what I can see, the most interesting part is the `HandleAsync` (https://github.com/MongkonEiadon/VehicleTracker/blob/master/src/Apps/EventConsumer.App/Program.cs#L87)... its implementation is a `Console.WriteLine`.

**Comment by FinalFortune** [comment]
> @FinalFortune @MongkonEiadon mmm... from what I can see, the most interesting part is the `HandleAsync` (https://github.com/MongkonEiadon/VehicleTracker/blob/master/src/Apps/EventConsumer.App/Program.cs#L87)... its implementation is a `Console.WriteLine`.

Well not sure why the `Console.WriteLine' would be that interesting but I was answering to 

> @rasmus mmm... that's actually what I want to achieve... react to events from other contexts.

From there you have the event passed from context A and can use `ICommandBus` to update or apply the logic to context B.
