### ISSUE TITLE
Event snapshots in EventStore

### ISSUE THREAD

**Issue by FinalFortune** [eventflow/EventFlow#703]
Using extension provided from _Eventflow.EventStores.EventStore_ I am able to save events to [EventStore](https://geteventstore.com/),
but it does not seem to use it as a snapshot store as my event store is reported as null for snapshots:
`[Warning]: Trying to store aggregate snapshot 'EventAggregate' with ID 'event-677c06bf-c482-4b7a-b012-b96a45566358' in the NULL store. Configure another store!` 
is that yet to be implemented?

**Comment by rasmus** [comment]
No, there's no snapshot support for EventStore. You could either use in-memory or some other store

**Comment by rasmus** [comment]
Have a look at the documentation here https://docs.geteventflow.net/Snapshots.html#snapshot-store-implementations

**Comment by rasmus** [comment]
Snapshots are merely a cache, thus you could also use Redis or Memcached. There's no current implementation though

**Comment by rasmus** [comment]
Closing as answered
