### ISSUE TITLE
RFC: Remove .NET Framework

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#713]
As .NET Framework is rather hard to maintain as it requires Windows to build, I would like some input on whether or not removing .NET Framework from the produced NuGet packages is a good idea at this point.

👍 good idea
👎  bad idea

If you have any comments, please post them below.

**Comment by ckoehler-pillar** [comment]
👍 This is a good idea and only prepares people for dotnet 5 sooner.

**Comment by blilley** [comment]
I think it is an excellent idea.
It looks like the only .NET Framework support is from test projects.
It looks like all dependency are .Net Standard, so I do not see a reason to specifically test Framework.

**Comment by rasmus** [comment]
Will be handled as described in #724
