### ISSUE TITLE
Lots of verbose logging from evenupgraders while not using them

### ISSUE THREAD

**Issue by WiseSewaTroll** [eventflow/EventFlow#714]
Hi,
Were using eventflow v0.76.4014. When our commandserver starts up we see lots of verbose logging like:
...
12:36:52:042 [Verbose]: Upgrading 1 events and found these event upgraders to use:
12:36:52:044 [Verbose]: Upgrading 2 events and found these event upgraders to use:
...
The weird thing is we are not using any event upgraders. Any thoughts on this, a workaround for this?

**Comment by rasmus** [comment]
No need for the logging if there's no events to upgrade. I'll add a check

**Comment by WiseSewaTroll** [comment]
The logging suggests that it is trying to upgrade (Upgrading 2 events...). But is isn't actually trying to upgrade something? Am I correct on this?

**Comment by WiseSewaTroll** [comment]
Aah...I glimpsed at the code. In EventUpgradeManager when there are no event upgraders registered shouldn't you return directly in this method?

**Comment by rasmus** [comment]
Yes, it should be a simple fix
