### ISSUE TITLE
Eventually consistent read model projections

### ISSUE THREAD

**Issue by dvanherten** [eventflow/EventFlow#715]
Hi there, been using the platform for a little while now and it has been great to use. I've only used SQLStreamStore in the past and built up a lot of the surrounding bits myself so it is from that perspective that my question comes.

From what I can tell so far, Read models are projected to within the same thread context as the command itself is handled. This means that if the read model update fails for some reason due to an exception (#577 would open this up more probably) that the user (web request) would be returned an error (maybe, implementation detail) yet the read model would now be out of sync.

Essentially what I was looking for in Event Flow is similar to what this [comment](https://github.com/eventflow/EventFlow/issues/439#issuecomment-549315499) is looking for. Truly eventual consistent updates where the projections would be their own subscriptions. If one fails, I can fix it and it'll pick up where it left off.

Which leads me to my question, is this a common desire? Has this not been an issue for others using Event Flow? Am I making a mountain out of a mole hill? What sorts of patterns are people applying to avoid any of the above I mention.

Also looking for feedback related to the approach that those more familiar with Event Flow might take to implement something like this (Subscription based read model projections). Should I end up trying to go down a route to solve this for myself it would be better if it was a way that would fit with the mental models of those more familiar with Event Flow than myself.

**Comment by ckoehler-pillar** [comment]
Currently I do not use eventflow read models for this and the problems mentioned in #577. Instead I use an eventflow synchronous subscriber to ship everything off to azure eventgrid.

**Comment by trancefreak77** [comment]
I think if you implement the interface IAmAsyncReadModelFor<> then the Apply method is not called within the context of the command.

**Comment by dvanherten** [comment]
> I think if you implement the interface IAmAsyncReadModelFor<> then the Apply method is not called within the context of the command.

That would be great if it is. I thought it was an async wrapper but still in the same thread context for exceptions bubbling. I'll take a closer look at it and see if it fits.

**Comment by dvanherten** [comment]
> Currently I do not use eventflow read models for this and the problems mentioned in #577. Instead I use an eventflow synchronous subscriber to ship everything off to azure eventgrid.

Interesting take on how to work around it. Thanks for sharing.

**Comment by rasmus** [comment]
@dvanherten I you are looking to handling subscribers completely out of the current context, you could have a look at the `ISubscribeAsynchronousTo`.

https://docs.geteventflow.net/Subscribers.html#asynchronous-subscribers

**Comment by dvanherten** [comment]
Yeah was looking into that a bit and will continue to do so. Will dive more into the EventFlow code to see if I can wire up something the way I'm hoping to.

Thanks.
