### ISSUE TITLE
Injecting ICommandBus leads to failure with injection of ILog

### ISSUE THREAD

**Issue by ChristianHaase** [eventflow/EventFlow#716]
Getting following error when injecting `ICommandBus` into my controller:

    Unable to resolve service for type 'EventFlow.Logs.ILog' while attempting to activate 'EventFlow.AspNetCore.Middlewares.CommandPublishMiddleware'.

I'm using dotnet core 3.0, and the latest version from NuGet, that you released yesterday.

This is my setup in `ConfigureServices`

    var eventFlowOptions = EventFlowOptions.New
                .UseConsoleLog()
                .RegisterModule<Module1>()
                .RegisterModule<Module2>()
                .AddAspNetCore();

If you need more info, please let me know :)

**Comment by ProH4Ck** [comment]
I had similar problem some weeks ago... 
Try to AddAspNetCore() before everything else:

```
var eventFlowOptions = EventFlowOptions.New
  .AddAspNetCore()
  .UseConsoleLog()
  .RegisterModule<Module1>()
  .RegisterModule<Module2>()          
```

**Comment by ChristianHaase** [comment]
Doesn't seem to work. Still getting the same error.

**Comment by ChristianHaase** [comment]
Are you also setting the following in `Configure`?

    app.UseMiddleware<CommandPublishMiddleware>();

**Comment by ProH4Ck** [comment]
This is my working code:

```csharp
services.AddEventFlow(options =>
  options.AddDefaults(typeof(Startup).Assembly)
    .AddAspNetCore(aspnetcoreopts => aspnetcoreopts.UseDefaults())
    .ConfigureMongoDb(Configuration["MongoConnectionString"], Configuration["MongoDbName"])
    .UseMongoDbEventStore()
    .UseMongoDbReadModel<ReadModelA, ReadModelALocator>();
```

**Comment by ChristianHaase** [comment]
Did you create the extension `AddEventFlow` yourself?

**Comment by ProH4Ck** [comment]
It's in package `EventFlow.DependencyInjection`

**Comment by ChristianHaase** [comment]
Yep, that seems to do the trick. Perhaps this should be in the documentation somewhere? I only looked at the examples from this repo, and tried to find a solution from those.

But nevertheless, it seems to work now. Thank you :)
