### ISSUE TITLE
The question about "Task.FromResult"

### ISSUE THREAD

**Issue by Li7ye** [eventflow/EventFlow#722]
I don't understand why need to use `Task.FromResult`  to implement `Task<T>` . For example , the 'IMemoryCache' interface has `GetOrAddAsync()` function. But all implementations use the wrapper of `Task.FromResult` and the caller to call this function with using `await` to create 'State Machine'. Because of the 'State Machine' will generate`var awaiter=GetOrAddAsync().GetAwaiter()` , then the code will check `if(awaiter.IsCompleted)`. So `awaiter.IsCompleted ` always return `true` as using the wrapper `Task.FromResult.`  The code will run synchronously , so why isn't the `GetOrAddAsync()` function designed to be synchronous `GetOrAdd()`?  If this function is to test 'Task<T>' in unit test, I can understand. But how to understand this scenario? Please give me some suggestion , thank you very much.

**Comment by rasmus** [comment]
EventFlow tries to use async/await for every API to allow proper async/await if any developer needs to provide a custom implementation.

I the case for the `IMemoryCache`, this would allow you to do async/await semaphores.

But, it might also have been a over-engineered API.
