### ISSUE TITLE
eventdatamodel_list_type why it's required?

### ISSUE THREAD

**Issue by leotsarev** [eventflow/EventFlow#730]
Hi, from the documentation and code I can't understand what's the reason of `eventdatamodel_list_type`. It's constructed and never used...

**Comment by leotsarev** [comment]
I found some answer in MS SQL documentation
`If you utilize user permission in your application, then you need to grant the event writer access to the user defined table type``eventdatamodel_list_type``. EventFlow uses this type to pass entire    batches of events to the database.`
Still, I couldn't find usage of this in code.

**Comment by rasmus** [comment]
@leotsarev it's not obvious, but the code is here https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.MsSql/Integrations/TableParameter.cs#L109

```csharp
sqlParameter.TypeName = $"{typeof(TRow).Name.ToLowerInvariant()}_list_type";
```

**Comment by rasmus** [comment]
Normally Dapper inserts multiple rows of a complex type by executing an `INSERT` statement for each row. By creating a custom type, all rows are transferred and executed in a single `INSERT` statement. This is to minimize database locking and removes the need for an explicit transaction. If one row fails to insert (e.g. if someone already committed a event on the aggregate), then all the rows fail.

**Comment by leotsarev** [comment]
Thanks for answer!
It seems, however, that table parameters are not used in PostgreSQL persistence. 
I compared
https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.PostgreSql/Connections/PostgresSqlConnection.cs
with https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.MsSql/MsSqlConnection.cs

but eventdatamodel_list_type is mentioned in migrating scripts.

**Comment by rasmus** [comment]
That does seem a bit weird, might be an error. We'll have to get hold of one of the contributors that implemented PostgreSQL. Or test it out. I'm on vacation and have limited access to a computer these days.

**Comment by rasmus** [comment]
answerd
