### ISSUE TITLE
Question: table per aggregate type — why not?

### ISSUE THREAD

**Issue by leotsarev** [eventflow/EventFlow#735]
Hi, during discussions with our DBA it seems to be good idea to split table in SQL storage per aggregate type.
It will allow i.e. partition heavily used aggregate types while keeping other aggregate types simple.

I wondered why it's not by default and what problems will we encounter if we try to implement our own persistense layer with table per aggregate type.

**Comment by rasmus** [comment]
We have been running everything from the same table for years and we have a few TB of aggregate events and haven’t yet have any problems.

Splitting events into separate tables is a good idea, but I haven’t done it as not to introduce breaking any changes.

If you implement your own event persistence, I recommend using the EventFlow.TestHelper package and use the test suite for event persistence.

**Comment by rasmus** [comment]
Might be added as an additional option for e.g. the MSSQL package by allowing you to select how you would like to store events.

**Comment by leotsarev** [comment]
Should I worry about `LoadAllCommittedEvents` query being perfomance bottleneck or it could be implemented in naive way by reading every aggregate table?

**Comment by rasmus** [comment]
That method is for rebuilding all read models and isn’t very performant. I recommend implementing your own persistence or start using the bundled one and then migrate if you see a problem

**Comment by frankebersoll** [comment]
It appears that your question has been answered. Since we haven't heard anything about it for a while, we hope that your problem is solved - if not, please reopen the issue. Thanks!
