### ISSUE TITLE
Concurrency on ReadModel updates

### ISSUE THREAD

**Issue by MaxShoshin** [eventflow/EventFlow#740]
I have ReadModel which stores how many new objects is created on the specific date.

So i have read model locator, which extracts date from the specific events and this date is used as part of Read Model identifier.

I have an issue when two commands try to create new objects simultainously:
- Both commands commit events.
- Then they try to update read models
- Each of command try to load existing Read Model (there is no read model for this date), so both of them decide to insert new one.
- One of command update and sucessfully commit read model to Sql store (we use Postgres, but i don't think that it is really matters)
- The second command fails with update as the read model with the same Id already exists in DB.

I understand that I can retry process of 'read model update'. In my particular case order of events doesn't matter and it will work. But what if order of events for updating Read Model is really matter?

Do you have any ideas how to workaround this issue?

Thank you!

**Comment by rasmus** [comment]
You are correct, looking through the code I can’t find any retry regarding creation of read models. This seems like something pretty obvious to have and should be added.

**Comment by MaxShoshin** [comment]
It seems that it is not so simple.

In case of possible event reordering. We need to guarantee that repopulating read model from event store will produce the same state of read model like we have.

So i'm thinking about catch error on read model create and repopulate it from the store. To be sure that read model applies events in correct order.

As I understand this situation is applicable only for read models which listens events on several aggregate roots and only during creation. 

What do you thing about it?
