### ISSUE TITLE
ReadModelPopulator should ignore query filters

### ISSUE THREAD

**Issue by chrisjainsley** [eventflow/EventFlow#743]
I'm running the read model populator on an entity framework read store.

It's attempting to insert a new duplicate record, I'm thinking this is due to the HasQueryFilter option because the record it complains about is filtered and removing the query filter fixes the issue.

The IgnoreQueryFilters extension should be used by the populator.

Happy to put a pull request in.

**Comment by rasmus** [comment]
@cja100 that would be great! please add a test that verifies it was well to make sure it doesn't happen again

**Comment by frankebersoll** [comment]
@cja100 You proposed to contribute a PR. If you are still interested or need any help in doing so, please let us know!
