### ISSUE TITLE
New external example

### ISSUE THREAD

**Issue by craignicol** [eventflow/EventFlow#744]
Just highlighting this in case you're interested, I took a fork of @dennisfabri racetimes example and extended it to run with Azure Functions and then extended again to publish to Azure EventGrid as a new extension inspired by the RabbitMQ example. Might be of interest to others.

https://github.com/craignicol/Eventflow.Example.Racetimes/tree/feature/event-grid-as-extension

**Comment by dennisfabri** [comment]
I like to see that some people learn something from this example or do
their own thing with it.

**Comment by rasmus** [comment]
@craignicol you are more than welcome to create a PR with an update to the read-me with the external examples

**Comment by craignicol** [comment]
@rasmus OK, submitted.

**Comment by rasmus** [comment]
Merged
