### ISSUE TITLE
ReadModel should be DB-agnostic

### ISSUE THREAD

**Issue by nZeus** [eventflow/EventFlow#745]
I would like to keep my domain to be db-agnostic.

E.g. read models should not know _anything_ about the database they are stored in. 
They just describe the structure, and the infrastructure layer can define the db types that needs to be used for my read model.

But the `MsSqlReadModelIdentityColumn` breaks it.
That means if I decide to switch from 1 db to another, I have to add/remove db-specific attributes (like `MsSqlReadModelIdentityColumn`) to my models.

Would be nice if there can be another attribute (~`ReadModelIdentityColumn`) instead. This column should be part of the `EvenFlow` library itself, not the `EventFlow.SomeDatabase`.

**Comment by rasmus** [comment]
Hi @nZeus, I disagree. Read models are highly optimized reads that rely heavily on the underlying technology. If you want to use our read models and represent them in a way that doesn't contain information regarding e.g. MSSQL or Elasticsearch, use the `IQueryProcessor`. Then in a query handler you would map the MSSQL model to a read-only domain entity, which doesn't contain anything about MSSQL.

This is how we do it, it enables us to implement in-memory query handlers that are easy to mock in unit, domain and/or integration tests and then test the query handlers in a different setup which focuses on the how the queries perform in regards to the underlying technology, e.g. check that MSSQL index fragmentation doesn't explode after inserting read models.

**Comment by rasmus** [comment]
Its actually in the shipping example

https://github.com/eventflow/EventFlow/tree/develop/Source/EventFlow.Examples.Shipping.Queries.InMemory

**Comment by frankebersoll** [comment]
It appears that your question has been answered. Since we haven't heard anything about it for a while, we hope that your problem is solved - if not, please reopen the issue. Thanks!
