### ISSUE TITLE
IEventUpgrader usage differs for aggregate loading and read model repopulation

### ISSUE THREAD

**Issue by radiosterne** [eventflow/EventFlow#747]
Let's take a sneak peak at the docs, namely at the page explaining the process of event upgrading: https://eventflow.readthedocs.io/EventUpgrade.html. The relevant excerpt reads as follows:

> A new instance of an event upgrader is created each time an aggregate is loaded. This enables you to store information from previous events on the upgrader instance to be used later, e.g. to determine an action to take on a event or to provide additional information for a new event.

Whilst the first part of this statement is completely correct, and new instance is, in fact, created for an aggregate loading process in its entirety, the latter part — the one establishing one's ability to store information from previous events on upgrader instance — is partially incorrect.

`EventUpgradeManager` is resolving new instance of corresponding upgraders for every [batch](https://github.com/eventflow/EventFlow/blob/56cd52eb38843a90c350d3fc119c0fd10fb7fc5f/Source/EventFlow/EventStores/EventUpgradeManager.cs#L85) of events it's asked to update. When aggregate is being loaded, this batch would consist of all the corresponding events, all right.

But when read models are [being populated](https://github.com/eventflow/EventFlow/blob/e7f9250fd4b79c1271490a2b4022745f10db5676/Source/EventFlow/ReadStores/ReadModelPopulator.cs#L128), no such mechanism exist — events belonging to one aggregate can (and, in fact, inevitably will, when aggregates are long-living and changing for a long period of time) be upgraded using two separate instances of upgrader.

Ergo, docs are, as of now, misleading.

The proposed solution is either to clarify this finer point in docs, or possibly change read model population mechanism so that this invariant still holds — @rasmus, what do you think? I may be able to draft up a PR later this week, if you're interested.

**Comment by rasmus** [comment]
Hi @radiosterne this is clearly bug, as stated it yourself, its unexpected behavior. At work we don't use that part of EventFlow as we typically have read models in separate micro services.

**Comment by frankebersoll** [comment]
@radiosterne Did you happen to draft a PR for this? We would really appreciate your help on this issue.
