### ISSUE TITLE
Cannot apply aggregate event of type

### ISSUE THREAD

**Issue by cja100** [eventflow/EventFlow#750]
I'm trying to remove an event as per the docs.

https://eventflow.readthedocs.io/EventUpgrade.html#example-removing-a-damaged-event

However when applying the events it's complaining that the sequence number does not match the version+1: 

`Cannot apply aggregate event of type 'DomainEvent<WorkflowItemAggregate,WorkflowItemId,TeamMembersAmended>' with SequenceNumber 4 on aggregate with version 2`

**Comment by rasmus** [comment]
the answer is in the big box 😄 the easy solution is to create a dummy event to replace it

![image](https://user-images.githubusercontent.com/18956/80272382-fb8b1a00-86c8-11ea-9835-2e5775ebfb20.png)

**Comment by frankebersoll** [comment]
It appears that your question has been answered. Since we haven't heard anything about it for a while, we hope that your problem is solved - if not, please reopen the issue. Thanks!
