### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow#751]
Its clear that I need help maintaining this project.

EventFlow is used in a lot of production environments today and the complexity of the solution, the size of the code base, as well as the tasks that lie ahead, deserve more attention that its currently getting from me.

My idea is that two, preferable three, additional maintainers would be great. Then if there's agreement with the course of action or a PR a has been reviewed, I'll support their decision.

Initially there won't be any additional permissions on the repositories, there has been too many examples of malignant additions to open-source projects that have been given over to new maintainers. Initially, any will be added to the EventFlow GitHub organization and we'll take it from there.

I'm also evaluating the current members as you haven't been active on EventFlow, i.e., even less than me, for the last year. If your still interested, let me know. If not, no hard feelings and a big thanks for your critical contributions.

- @frankebersoll
- @edwardwilson
- @warren-pieterse
- @janfeyen

Note that I will not be withdrawing from the project at all. EventFlow is very dear to me, but I need help.

If you have any comments or alternative solutions, let me know.

**Comment by rasmus** [comment]
@mbican and @leotsarev is this something you would be interested in?

**Comment by frankebersoll** [comment]
I love this project and have great interest, still, I'd like to defer to other applicants if available. We use EventFlow in many production systems at our company. For private projects, I recently moved away from it, because there is no real interop with F# and no "functional way" of modeling the Domain with EventFlow.

**Comment by leotsarev** [comment]
Hey @rasmus !
We (me, @MaxShoshin and other guys from our team) like Eventflow a lot, and we are ready to contribute, but we don't have enough Event Sourcing experience to maintain something. Our whole reason to use Eventflow is to learn good architectural patterns from established project. So, we could contribute only if we still have guidance from matured "event sourcers".
We are interested in following areas:
 - Crash resilience https://github.com/eventflow/EventFlow/issues/439 
 - Moving to MS.Extensions abstractions (especially in Logging area)
 - PostgreSQL persistence

**Comment by rasmus** [comment]
@leotsarev very nice. All those areas require some love and care.

**Comment by rasmus** [comment]
I'll go ahead and remove all members except @frankebersoll from the list of EventFlow members as I haven't heard from anyone of them. Note that this is not shutting the door on anyone, just making it easier for others to see who is maintaining the project.

**Comment by rasmus** [comment]
@leotsarev are you up for getting some progress on #439?

**Comment by hvidgaard** [comment]
We're launching a product refresh using EventFlow soon, and another will follow later this year. So I'm willing to allocate some resources to ensure the stability and progress of this. If you have some issues that ought to get attention I can see if they're suitable for one in my team to look at, but the initial interest is:

- PostgreSQL persistence
- Automatic generation/update of sql read model schemas.
- Better DI abstractions. We use SimpleInjector, and I've not been able to cross wire them. But I haven't looked at it in depth.
- Various saga improvements

**Comment by Teides** [comment]
Hi Rasmus,

I have been following your work for a long time and let  me tell you that, if need help I will be ther for you. 

Best Regards

Enviado desde mi iPhone

**Comment by rasmus** [comment]
Hi @hvidgaard and @Teides that sounds great 😄 help out with answering questions (if you can), find an issue to do a PR for or do a small PR with cleanup. Every little thing helps!

**Comment by rasmus** [comment]
@frankebersoll has been promoted to maintainer and will be helping out with planning and issue triage. Frank has a long history with EventFlow and has contributed to several of the core features.

If anyone else is interested, then its easy. Just start by being part of the community and helping out.

**Comment by frankebersoll** [comment]
Thanks a lot @rasmus! I feel honoured and it is very important to me to be able to support this project. I look forward to working with you to tackle the important pain points that are lying ahead and to clear the way to version 1.0.

**Comment by promontis** [comment]
@rasmus would it be possible to add me to the maintainers list?

**Comment by WardenUnleashed** [comment]
@rasmus I would be willing to become a contributor! I'm working with EventFlow almost every day at my job and have been using for quite some time now!
