### ISSUE TITLE
RabbitMQ Integration for .Net Core 3

### ISSUE THREAD

**Issue by i-dentify** [eventflow/EventFlow#755]
The .Net-RabbitMQ-Client seems to have published Version 6.0, which is to be used for .Net Core 3.x ([https://www.rabbitmq.com/dotnet.html](url))

The EventFlow-RabbitMQ-Integration calls a method `BasicPublish(string exchange, string routingKey, bool mandatory, IBasicProperties basicProperties, byte[] body)` which has been removed according to [https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/ed3e56a7f27e39501c2d19b165789c7e7762dcd9#diff-2bacc96f1a40128b86a990a644e6ed8f](url)

Having integrated the RabbitMQ.Client package into a solution (e.g. for other custom stuff) and updating this to 6.0 results in an exception for the EventFlow RabbitMqPublisher: `System.MissingMethodException: Method not found: 'Void RabbitMQ.Client.IModel.BasicPublish(System.String, System.String, Boolean, RabbitMQ.Client.IBasicProperties, Byte[])'`

**Comment by frankebersoll** [comment]
@rasmus Would we simply update our reference or do we need to support multiple major versions?

**Comment by rasmus** [comment]
I'll update the reference for the 1.0 release
