### ISSUE TITLE
Add support for Azure Event Hubs

### ISSUE THREAD

**Issue by tedvanderveen** [eventflow/EventFlow#756]
Hi! Are you guys open for a contribution that adds support for Azure Event Hubs integration? Or is this something that is already being worked on? This could be a welcome addition for organizations that target Azure for application workloads and look for a fully managed event stream/storage solution.

Azure Event Hubs is quite similar to Kafka: https://azure.microsoft.com/nl-nl/blog/azure-event-hubs-for-kafka-ecosystems-in-public-preview/

Is an integration with Event Hubs something can be part of the EventFlow library (just like RabbitMQ integration is part of this repo)? Or should this be an separate/new integration library?

**Comment by frankebersoll** [comment]
This certainly sounds interesting, although I don't really understand whether Event Hubs is really the right service for this purpose. [Considering this comparison](https://docs.microsoft.com/de-de/azure/event-grid/compare-messaging-services#comparison-of-services), an Azure Service Bus integration seems closer to what we might need for EventFlow.

What would the test concept look like? For RabbitMq we have a local installation that we can use in automated tests. Is there an easy way to do this in Azure?

Would you also like to use your contribution productively and want to maintain it in the longer term?

@rasmus What do you think about introducing more extensions to our repository? I still think that the advantages of the mono repository outweigh the costs, especially for things like refactoring and joint versioning.

Translated with www.DeepL.com/Translator (free version)

**Comment by ahernandez-allegion** [comment]
Second EventHub integration, although if  you supported **Kafka** you'd essentially get EventHub for free as @tedvanderveen pointed out. Not sure how the integration testing would work. Microsoft does have tooling for lots of local Azure services and there are Azure Edge components that might expose EventHub. For Kafka there are [Docker images provided by Confluent](https://docs.confluent.io/current/quickstart/ce-docker-quickstart.html).

**Comment by jessemillerrev** [comment]
I already have an integration for Azure Service Bus that I am working on cleaning up for a possible PR.
