### ISSUE TITLE
[Question] Sample usage of PostgreSqlReadModel

### ISSUE THREAD

**Issue by michalSolarz** [eventflow/EventFlow#766]
I'm trying to figure out how to plug my PostgreSqlReadModel to ASP.Net core app but I cannot find any example usage of PostgreSqlReadModel. I've that, very simple ReadModel (based on REST Airlines example):

```c#
    public class BookingReadModel: PostgreSqlReadModel, IAmReadModelFor<Booking, BookingId, JourneysSelectedEvent>
    {

        public List<Passenger> Passengers { get; set; }

        public List<Journey> Journeys { get; set; }
        
        public void Apply(IReadModelContext context, IDomainEvent<Booking, BookingId, JourneysSelectedEvent> domainEvent)
        {
            var journeys = domainEvent.AggregateEvent.Journeys;

            Journeys = journeys.ToList();
        }
    }
```

But after applying JourneysSelectedEvent on my Aggreagate I get exception about missing ReadModel table. I'm aware that that table is missing but I've no idea how to generate it. Is it possible to automatically generate it like snapshot/event stores?

I've following DB migrations plugged in my app startup:
```c#
            using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                var context = serviceScope.ServiceProvider.GetService<IPostgreSqlDatabaseMigrator>();
                EventFlowEventStoresPostgreSql.MigrateDatabase(context);
                EventFlowSnapshotStoresPostgreSql.MigrateDatabase(context);
            }
```
but I wasn't able to find any method designated for read model store creation, am I missing something? Do I need to create that tables by hand like here: https://qiita.com/kwhrkzk/items/93e01a9da9514061df24 ?

Here is my Eventflow configuration:
```c#
            EventFlowOptions.New
                .UseAutofacContainerBuilder(builder)
                .ConfigurePostgreSql(psql)
                .AddDefaults(typeof(Startup).Assembly)
                .AddSnapshots(typeof(Startup).Assembly)
                .UsePostgreSqlEventStore()
                .UsePostgreSqlSnapshotStore()
                .UsePostgreSqlReadModel<BookingReadModel>()
                .RegisterServices(sr => sr.Register(i => SnapshotEveryFewVersionsStrategy.Default))
                .UseLibLog(LibLogProviders.Serilog)
                ;
```

**Comment by frankebersoll** [comment]
You need to manually craft the SQL for your Read Models. This way, you can optimize them any way you want and add indexes as needed - the framework wouldn't be able to figure out your needs there.

If you add your scripts as embedded resources, you can then use the migrator to update your database:

```csharp
var context = serviceScope.ServiceProvider.GetService<IPostgreSqlDatabaseMigrator>();
// ...
context.MigrateDatabaseUsingEmbeddedScripts(GetType().Assembly);
```

Please have a look [over here](https://github.com/eventflow/EventFlow/tree/develop/Source/EventFlow.PostgreSql.Tests/IntegrationTests/ReadStores) where you will find an example how to do this, together with an [example migration script](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow.PostgreSql.Tests/IntegrationTests/ReadStores/Scripts/0001%20-%20Create%20table%20ReadModel-ThingyAggregate.sql). You need to add the files as [embedded resource](https://stackoverflow.com/a/26584991/4317569) to make it work.

**Comment by michalSolarz** [comment]
OK, thanks for reply, I'll try to follow with your instructions and migrate my read models store manually :smiley:
