### ISSUE TITLE
allow FilesEventPersistence to use relative paths

### ISSUE THREAD

**Issue by Yaevh** [eventflow/EventFlow#771]
Currently `FilesEventPersistence` is using absolute paths to store events. If the user changes `IFilesEventStoreConfiguration.StorePath` and copies the DB to the new locations (for example while deploying to another server or reorganizing data paths during development), events are not deserialized properly, as the event files no longer exist in the old location - all the events are effectively unreadable and lost. Furthermore, there are no warnings raised, which makes debugging the missing events difficult.
This could be easily fixed if the paths were relative to `IFilesEventStoreConfiguration.StorePath` - the `StorePath` is used to point to both event log (`Log.store` file) and events themselves, so they'll always reside in the same location.

I will probably submit a PR for this, but I'd like to hear your comments, especially if you think this is a bad idea.

BTW, I'm aware that `FilesEventPersistence` shouldn't be used in production environment, but it's sometimes more convenient during development - at least until you reorganize your data paths, which can happen during development cycle.

**Comment by frankebersoll** [comment]
This sounds like a really good idea, and we would be happy about a PR! Please let us know if you need any help.
