### ISSUE TITLE
[Documentation] Gettings Started Feedback

### ISSUE THREAD

**Issue by eluchsinger** [eventflow/EventFlow#784]
I have been reading through the documentation and found a couple things that probably should be refreshed. If I find time for it, I might be able to make a PR.

- I found no information about the DependencyInjection Nuget package needed to support ASP.NET Core in the documentation. The docs only mention the `EventFlow.AspNetCore` package.
- The code example in the Getting Started section could use a refactoring to help understanding. For example an event should notify that something *has already* happened. So the name of the event should not be `ExampleEvent`, but rather `ExampleHappenedEvent` (or even better `MagicNumberSetEvent`). Actually, it might be a good idea to rewrite the example using a "real-world" use case, like a shop or a restaurant and maybe even showing the whole integration with ASP.NET Core and a folder structure as inspiration.
- More specialized sections, like the Apply Events section could use a bit deeper information. It is not very clear to me which one I should pick and what the pro's and con's are from each one.

**Comment by jwillmer** [comment]
I looked into the project and the documentation and my biggest question marks are:

- Lot's of technology options to use for specific functions but I don't find a comparison which one to pick - pro and contra?
- Some options are defined in the README but not in the documantation - documentation has three explained EventStore implementations but 7 mentioned in the README
- Why RabbitMQ integration and not Mosquitto or any other MQTT broker?
